
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 11.04.24 AM


CREATE or REPLACE PACKAGE RP_ACTION_INSTANCE
IS

   FUNCTION ISOLATED_TX_IND(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION EXEC_ORDER(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION SCHEDULE_NO(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION RECORD_STATUS(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN DATE;
   FUNCTION DESCRIPTION(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2;
      TYPE REC_ROW_BY_PK IS RECORD (
         ACTION_INSTANCE_NO NUMBER ,
         SCHEDULE_NO NUMBER ,
         BUSINESS_ACTION_NO NUMBER ,
         EXEC_ORDER NUMBER ,
         ISOLATED_TX_IND VARCHAR2 (1) ,
         DESCRIPTION VARCHAR2 (240) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN REC_ROW_BY_PK;
   FUNCTION REC_ID(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION BUSINESS_ACTION_NO(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN NUMBER;

END RP_ACTION_INSTANCE;

/



CREATE or REPLACE PACKAGE BODY RP_ACTION_INSTANCE
IS

   FUNCTION ISOLATED_TX_IND(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.ISOLATED_TX_IND      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END ISOLATED_TX_IND;
   FUNCTION APPROVAL_BY(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.APPROVAL_BY      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.APPROVAL_STATE      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION EXEC_ORDER(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.EXEC_ORDER      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END EXEC_ORDER;
   FUNCTION SCHEDULE_NO(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.SCHEDULE_NO      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END SCHEDULE_NO;
   FUNCTION RECORD_STATUS(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.RECORD_STATUS      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.APPROVAL_DATE      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION DESCRIPTION(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.DESCRIPTION      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END DESCRIPTION;
   FUNCTION ROW_BY_PK(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.ROW_BY_PK      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION REC_ID(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.REC_ID      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END REC_ID;
   FUNCTION BUSINESS_ACTION_NO(
      P_ACTION_INSTANCE_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_ACTION_INSTANCE.BUSINESS_ACTION_NO      (
         P_ACTION_INSTANCE_NO );
         RETURN ret_value;
   END BUSINESS_ACTION_NO;

END RP_ACTION_INSTANCE;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_ACTION_INSTANCE TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 11.04.27 AM


