
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 11.04.14 AM


CREATE or REPLACE PACKAGE RP_ACTION_JOB_CONFIG
IS

   FUNCTION APPROVAL_BY(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION PARAM_VALUE(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION JOB_ACTION_NO(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION TRANSPORT_COMPONENT_IND(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION JOB_ACTION_CLASS(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION PARAM_NAME(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION RECORD_STATUS(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         JOB_CONFIG_NO NUMBER ,
         JOB_ID VARCHAR2 (240) ,
         JOB_ACTION_NO NUMBER ,
         JOB_ACTION_CLASS VARCHAR2 (2000) ,
         PARAM_NAME VARCHAR2 (240) ,
         PARAM_VALUE VARCHAR2 (240) ,
         TRANSPORT_COMPONENT_IND VARCHAR2 (1) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN REC_ROW_BY_PK;
   FUNCTION JOB_ID(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION REC_ID(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2;

END RP_ACTION_JOB_CONFIG;

/



CREATE or REPLACE PACKAGE BODY RP_ACTION_JOB_CONFIG
IS

   FUNCTION APPROVAL_BY(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.APPROVAL_BY      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.APPROVAL_STATE      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION PARAM_VALUE(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.PARAM_VALUE      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END PARAM_VALUE;
   FUNCTION JOB_ACTION_NO(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.JOB_ACTION_NO      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END JOB_ACTION_NO;
   FUNCTION TRANSPORT_COMPONENT_IND(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.TRANSPORT_COMPONENT_IND      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END TRANSPORT_COMPONENT_IND;
   FUNCTION JOB_ACTION_CLASS(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.JOB_ACTION_CLASS      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END JOB_ACTION_CLASS;
   FUNCTION PARAM_NAME(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.PARAM_NAME      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END PARAM_NAME;
   FUNCTION RECORD_STATUS(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.RECORD_STATUS      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.APPROVAL_DATE      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.ROW_BY_PK      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION JOB_ID(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.JOB_ID      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END JOB_ID;
   FUNCTION REC_ID(
      P_JOB_CONFIG_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_ACTION_JOB_CONFIG.REC_ID      (
         P_JOB_CONFIG_NO );
         RETURN ret_value;
   END REC_ID;

END RP_ACTION_JOB_CONFIG;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_ACTION_JOB_CONFIG TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 11.04.17 AM


