
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.00.23 AM


CREATE or REPLACE PACKAGE RP_CLASS_TRIGGER_ACTN_CNFG
IS

   FUNCTION APPROVAL_BY(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION DB_SQL_SYNTAX(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION RECORD_STATUS(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         CLASS_NAME VARCHAR2 (24) ,
         TRIGGERING_EVENT VARCHAR2 (250) ,
         TRIGGER_TYPE VARCHAR2 (30) ,
         SORT_ORDER NUMBER ,
         APP_SPACE_CNTX VARCHAR2 (32) ,
         DB_SQL_SYNTAX VARCHAR2 (4000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN REC_ROW_BY_PK;
   FUNCTION APP_SPACE_CNTX(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION REC_ID(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;

END RP_CLASS_TRIGGER_ACTN_CNFG;

/



CREATE or REPLACE PACKAGE BODY RP_CLASS_TRIGGER_ACTN_CNFG
IS

   FUNCTION APPROVAL_BY(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.APPROVAL_BY      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.APPROVAL_STATE      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION DB_SQL_SYNTAX(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (4000) ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.DB_SQL_SYNTAX      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END DB_SQL_SYNTAX;
   FUNCTION RECORD_STATUS(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.RECORD_STATUS      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.APPROVAL_DATE      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.ROW_BY_PK      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION APP_SPACE_CNTX(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.APP_SPACE_CNTX      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END APP_SPACE_CNTX;
   FUNCTION REC_ID(
      P_CLASS_NAME IN VARCHAR2,
      P_TRIGGERING_EVENT IN VARCHAR2,
      P_TRIGGER_TYPE IN VARCHAR2,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CLASS_TRIGGER_ACTN_CNFG.REC_ID      (
         P_CLASS_NAME,
         P_TRIGGERING_EVENT,
         P_TRIGGER_TYPE,
         P_SORT_ORDER );
         RETURN ret_value;
   END REC_ID;

END RP_CLASS_TRIGGER_ACTN_CNFG;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CLASS_TRIGGER_ACTN_CNFG TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.00.25 AM


