
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.49.25 AM


CREATE or REPLACE PACKAGE RP_CNTR_QUALITY_COMP
IS

   FUNCTION TEXT_4(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_7(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_7(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION TEXT_10(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_5(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_6(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_3(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION DATE_5(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION TEXT_1(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_12(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_6(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_2(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_15(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION DATE_6(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         QUALITY_HANDLING_NO NUMBER ,
         COMPONENT_NO VARCHAR2 (16) ,
         VALUE NUMBER ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         VALUE_11 NUMBER ,
         VALUE_12 NUMBER ,
         VALUE_13 NUMBER ,
         VALUE_14 NUMBER ,
         VALUE_15 NUMBER ,
         TEXT_1 VARCHAR2 (240) ,
         TEXT_2 VARCHAR2 (240) ,
         TEXT_3 VARCHAR2 (2000) ,
         TEXT_4 VARCHAR2 (2000) ,
         TEXT_5 VARCHAR2 (2000) ,
         TEXT_6 VARCHAR2 (2000) ,
         TEXT_7 VARCHAR2 (2000) ,
         TEXT_8 VARCHAR2 (2000) ,
         TEXT_9 VARCHAR2 (2000) ,
         TEXT_10 VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         DATE_6  DATE ,
         DATE_7  DATE ,
         DATE_8  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION TEXT_2(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_9(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_13(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_2(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_4(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION REC_ID(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_7(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION DATE_8(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE;
   FUNCTION TEXT_3(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_8(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_11(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_14(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER;

END RP_CNTR_QUALITY_COMP;

/



CREATE or REPLACE PACKAGE BODY RP_CNTR_QUALITY_COMP
IS

   FUNCTION TEXT_4(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_4      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION TEXT_7(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_7      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_7;
   FUNCTION APPROVAL_BY(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.APPROVAL_BY      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.APPROVAL_STATE      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION VALUE_5(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_5      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION DATE_7(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_7      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_7;
   FUNCTION TEXT_10(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_10      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_10;
   FUNCTION TEXT_5(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_5      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION TEXT_6(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_6      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_6;
   FUNCTION DATE_3(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_3      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_5      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_5;
   FUNCTION TEXT_1(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_1      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION VALUE_12(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_12      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_12;
   FUNCTION VALUE_6(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_6      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION DATE_2(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_2      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_2;
   FUNCTION RECORD_STATUS(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.RECORD_STATUS      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_1      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION VALUE_15(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_15      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_15;
   FUNCTION APPROVAL_DATE(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.APPROVAL_DATE      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION DATE_6(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_6      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_6;
   FUNCTION ROW_BY_PK(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.ROW_BY_PK      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION TEXT_2(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_2      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION TEXT_9(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_9      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_9;
   FUNCTION VALUE_13(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_13      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_13;
   FUNCTION VALUE_2(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_2      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_3      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_4      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION DATE_4(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_4      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_4;
   FUNCTION REC_ID(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.REC_ID      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END REC_ID;
   FUNCTION VALUE(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE;
   FUNCTION VALUE_7(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_7      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_9      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION DATE_1(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_1      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_1;
   FUNCTION DATE_8(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.DATE_8      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END DATE_8;
   FUNCTION TEXT_3(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_3      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_8(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.TEXT_8      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END TEXT_8;
   FUNCTION VALUE_10(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_10      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_11(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_11      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_11;
   FUNCTION VALUE_14(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_14      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_14;
   FUNCTION VALUE_8(
      P_QUALITY_HANDLING_NO IN NUMBER,
      P_COMPONENT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTR_QUALITY_COMP.VALUE_8      (
         P_QUALITY_HANDLING_NO,
         P_COMPONENT_NO );
         RETURN ret_value;
   END VALUE_8;

END RP_CNTR_QUALITY_COMP;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CNTR_QUALITY_COMP TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.49.34 AM


