
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.45.56 AM


CREATE or REPLACE PACKAGE RP_CHOKE_MODEL_LIP_CHILD
IS

   FUNCTION MATH_VALUE_26(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_39(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_42(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_16(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_18(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_21(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_27(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_30(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_37(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_47(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_48(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION FROM_DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_22(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_30(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_31(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_47(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION TO_DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION VALUE_23(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_28(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_42(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_46(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION CHANGE_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_19(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_20(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_21(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_23(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_28(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_32(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_38(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_41(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_44(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_45(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_50(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_29(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_31(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_32(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_36(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION COUNT_ROWS(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_25(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_29(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_36(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_22(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_26(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_45(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_49(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_18(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_27(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_40(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_48(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_19(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_33(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_34(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION LIP_OPP_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MATH_CHANGE_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_17(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_49(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         CHOKE_MODEL_ID VARCHAR2 (32) ,
         LIP_OPP_ID NUMBER ,
         FROM_DAY  DATE ,
         TO_DAY  DATE ,
         CHANGE_QTY NUMBER ,
         COMMENTS VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         VALUE_11 NUMBER ,
         VALUE_12 NUMBER ,
         VALUE_13 NUMBER ,
         VALUE_14 NUMBER ,
         VALUE_15 NUMBER ,
         VALUE_16 NUMBER ,
         VALUE_17 NUMBER ,
         VALUE_18 NUMBER ,
         VALUE_19 NUMBER ,
         VALUE_20 NUMBER ,
         VALUE_21 NUMBER ,
         VALUE_22 NUMBER ,
         VALUE_23 NUMBER ,
         VALUE_24 NUMBER ,
         VALUE_25 NUMBER ,
         VALUE_26 NUMBER ,
         VALUE_27 NUMBER ,
         VALUE_28 NUMBER ,
         VALUE_29 NUMBER ,
         VALUE_30 NUMBER ,
         VALUE_31 NUMBER ,
         VALUE_32 NUMBER ,
         VALUE_33 NUMBER ,
         VALUE_34 NUMBER ,
         VALUE_35 NUMBER ,
         VALUE_36 NUMBER ,
         VALUE_37 NUMBER ,
         VALUE_38 NUMBER ,
         VALUE_39 NUMBER ,
         VALUE_40 NUMBER ,
         VALUE_41 NUMBER ,
         VALUE_42 NUMBER ,
         VALUE_43 NUMBER ,
         VALUE_44 NUMBER ,
         VALUE_45 NUMBER ,
         VALUE_46 NUMBER ,
         VALUE_47 NUMBER ,
         VALUE_48 NUMBER ,
         VALUE_49 NUMBER ,
         VALUE_50 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         TEXT_9 VARCHAR2 (240) ,
         TEXT_10 VARCHAR2 (240) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         CHOKE_MODEL_ID VARCHAR2 (32) ,
         LIP_OPP_ID NUMBER ,
         FROM_DAY  DATE ,
         TO_DAY  DATE ,
         CHANGE_QTY NUMBER ,
         COMMENTS VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         VALUE_11 NUMBER ,
         VALUE_12 NUMBER ,
         VALUE_13 NUMBER ,
         VALUE_14 NUMBER ,
         VALUE_15 NUMBER ,
         VALUE_16 NUMBER ,
         VALUE_17 NUMBER ,
         VALUE_18 NUMBER ,
         VALUE_19 NUMBER ,
         VALUE_20 NUMBER ,
         VALUE_21 NUMBER ,
         VALUE_22 NUMBER ,
         VALUE_23 NUMBER ,
         VALUE_24 NUMBER ,
         VALUE_25 NUMBER ,
         VALUE_26 NUMBER ,
         VALUE_27 NUMBER ,
         VALUE_28 NUMBER ,
         VALUE_29 NUMBER ,
         VALUE_30 NUMBER ,
         VALUE_31 NUMBER ,
         VALUE_32 NUMBER ,
         VALUE_33 NUMBER ,
         VALUE_34 NUMBER ,
         VALUE_35 NUMBER ,
         VALUE_36 NUMBER ,
         VALUE_37 NUMBER ,
         VALUE_38 NUMBER ,
         VALUE_39 NUMBER ,
         VALUE_40 NUMBER ,
         VALUE_41 NUMBER ,
         VALUE_42 NUMBER ,
         VALUE_43 NUMBER ,
         VALUE_44 NUMBER ,
         VALUE_45 NUMBER ,
         VALUE_46 NUMBER ,
         VALUE_47 NUMBER ,
         VALUE_48 NUMBER ,
         VALUE_49 NUMBER ,
         VALUE_50 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         TEXT_9 VARCHAR2 (240) ,
         TEXT_10 VARCHAR2 (240) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_17(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_20(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_25(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_LIP_OPP_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_16(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_24(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_34(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_35(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_37(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_46(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_38(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_39(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_40(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_43(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_44(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_33(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_43(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION TEXT_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_24(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_35(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_41(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_50(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;

END RP_CHOKE_MODEL_LIP_CHILD;

/



CREATE or REPLACE PACKAGE BODY RP_CHOKE_MODEL_LIP_CHILD
IS

   FUNCTION MATH_VALUE_26(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_26      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_26;
   FUNCTION MATH_VALUE_39(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_39      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_39;
   FUNCTION MATH_VALUE_42(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_42      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_42;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION VALUE_16(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_16      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_16;
   FUNCTION VALUE_18(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_18      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_18;
   FUNCTION VALUE_21(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_21      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_21;
   FUNCTION VALUE_27(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_27      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_27;
   FUNCTION VALUE_30(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_30      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_30;
   FUNCTION VALUE_37(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_37      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_37;
   FUNCTION VALUE_47(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_47      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_47;
   FUNCTION VALUE_48(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_48      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_48;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.APPROVAL_BY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION FROM_DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.FROM_DAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END FROM_DAY;
   FUNCTION MATH_VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_15      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_15;
   FUNCTION MATH_VALUE_22(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_22      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_22;
   FUNCTION MATH_VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_3      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_3;
   FUNCTION MATH_VALUE_30(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_30      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_30;
   FUNCTION MATH_VALUE_31(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_31      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_31;
   FUNCTION MATH_VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_4      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_4;
   FUNCTION MATH_VALUE_47(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_47      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_47;
   FUNCTION MATH_VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_8      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_8;
   FUNCTION TO_DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TO_DAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TO_DAY;
   FUNCTION VALUE_23(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_23      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_23;
   FUNCTION VALUE_28(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_28      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_28;
   FUNCTION VALUE_42(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_42      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_42;
   FUNCTION VALUE_46(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_46      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_46;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_5      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION CHANGE_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.CHANGE_QTY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END CHANGE_QTY;
   FUNCTION MATH_VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_11      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_11;
   FUNCTION MATH_VALUE_19(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_19      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_19;
   FUNCTION MATH_VALUE_20(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_20      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_20;
   FUNCTION MATH_VALUE_21(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_21      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_21;
   FUNCTION MATH_VALUE_23(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_23      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_23;
   FUNCTION MATH_VALUE_28(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_28      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_28;
   FUNCTION MATH_VALUE_32(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_32      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_32;
   FUNCTION MATH_VALUE_38(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_38      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_38;
   FUNCTION MATH_VALUE_41(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_41      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_41;
   FUNCTION MATH_VALUE_44(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_44      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_44;
   FUNCTION MATH_VALUE_45(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_45      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_45;
   FUNCTION MATH_VALUE_50(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_50      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_50;
   FUNCTION MATH_VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_6      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_6;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.NEXT_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.PREV_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_7      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_7;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_8      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_8;
   FUNCTION VALUE_29(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_29      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_29;
   FUNCTION VALUE_31(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_31      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_31;
   FUNCTION VALUE_32(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_32      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_32;
   FUNCTION VALUE_36(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_36      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_36;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.COMMENTS      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION COUNT_ROWS(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.COUNT_ROWS      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY );
         RETURN ret_value;
   END COUNT_ROWS;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.DATE_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.DATE_5      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_5;
   FUNCTION MATH_VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_1      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_1;
   FUNCTION MATH_VALUE_25(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_25      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_25;
   FUNCTION MATH_VALUE_29(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_29      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_29;
   FUNCTION MATH_VALUE_36(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_36      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_36;
   FUNCTION MATH_VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_5      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_5;
   FUNCTION MATH_VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_7      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_7;
   FUNCTION MATH_VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_9      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_9;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.NEXT_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_6      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_6;
   FUNCTION TEXT_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_9      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_9;
   FUNCTION VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_12      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_12;
   FUNCTION VALUE_22(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_22      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_22;
   FUNCTION VALUE_26(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_26      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_26;
   FUNCTION VALUE_45(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_45      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_45;
   FUNCTION VALUE_49(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_49      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_49;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_6      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.DATE_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_2;
   FUNCTION MATH_VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_13      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_13;
   FUNCTION MATH_VALUE_18(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_18      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_18;
   FUNCTION MATH_VALUE_27(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_27      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_27;
   FUNCTION MATH_VALUE_40(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_40      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_40;
   FUNCTION MATH_VALUE_48(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_48      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_48;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.PREV_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.RECORD_STATUS      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_15      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_15;
   FUNCTION VALUE_19(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_19      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_19;
   FUNCTION VALUE_33(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_33      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_33;
   FUNCTION VALUE_34(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_34      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_34;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION LIP_OPP_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.LIP_OPP_ID      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END LIP_OPP_ID;
   FUNCTION MATH_CHANGE_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_CHANGE_QTY      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_CHANGE_QTY;
   FUNCTION MATH_VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_12      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_12;
   FUNCTION MATH_VALUE_17(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_17      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_17;
   FUNCTION MATH_VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_2      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_2;
   FUNCTION MATH_VALUE_49(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_49      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_49;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.ROW_BY_PK      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.ROW_BY_REL_OPERATOR      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_5      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_13      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_13;
   FUNCTION VALUE_17(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_17      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_17;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_20(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_20      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_20;
   FUNCTION VALUE_25(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_25      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_25;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.DATE_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_4;
   FUNCTION MATH_LIP_OPP_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_LIP_OPP_ID      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_LIP_OPP_ID;
   FUNCTION MATH_VALUE_16(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_16      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_16;
   FUNCTION MATH_VALUE_24(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_24      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_24;
   FUNCTION MATH_VALUE_34(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_34      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_34;
   FUNCTION MATH_VALUE_35(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_35      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_35;
   FUNCTION MATH_VALUE_37(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_37      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_37;
   FUNCTION MATH_VALUE_46(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_46      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_46;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.REC_ID      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_38(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_38      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_38;
   FUNCTION VALUE_39(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_39      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_39;
   FUNCTION VALUE_40(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_40      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_40;
   FUNCTION VALUE_43(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_43      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_43;
   FUNCTION VALUE_44(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_44      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_44;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_7      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_9      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.DATE_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_1;
   FUNCTION MATH_VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_10      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_10;
   FUNCTION MATH_VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_14      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_14;
   FUNCTION MATH_VALUE_33(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_33      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_33;
   FUNCTION MATH_VALUE_43(
      P_OBJECT_ID IN VARCHAR2,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.MATH_VALUE_43      (
         P_OBJECT_ID,
         P_CHOKE_MODEL_ID,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_43;
   FUNCTION TEXT_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.TEXT_10      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_10;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_10      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_11      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_11;
   FUNCTION VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_14      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_14;
   FUNCTION VALUE_24(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_24      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_24;
   FUNCTION VALUE_35(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_35      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_35;
   FUNCTION VALUE_41(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_41      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_41;
   FUNCTION VALUE_50(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_50      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_50;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CHOKE_MODEL_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CHOKE_MODEL_LIP_CHILD.VALUE_8      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CHOKE_MODEL_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_8;

END RP_CHOKE_MODEL_LIP_CHILD;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CHOKE_MODEL_LIP_CHILD TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.46.23 AM


