
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.14.05 AM


CREATE or REPLACE PACKAGE RP_CT_STAGE_PLANT_FORECAST
IS

   FUNCTION DATE_10(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION GAS_TO_DOMGAS_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION HC_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION RAWGAS_DRYBASIS_TONNES(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION RAW_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION TEXT_4(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_7(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION LNG_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION RAW_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_5(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COND_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COND_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_7(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DATE_9(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DOMGAS_ENERGY_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DOMGAS_IMO(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DOMGAS_OPMAX_ENERGY(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DOMGAS_OPMAX_MASS(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DOMGAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION FUEL_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION TEXT_10(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_5(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_6(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION CO2_VENT_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COND_STAB_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DATE_5(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION FUEL_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION LNG_MASS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION LNG_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PLAT_OUTPUT_GAS_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION RAWGAS_DRYBASIS_MMSCF(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_6(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION CO2_INJ_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_2(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION HC_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION HYDROCARBON_VOLUME_SM3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION LNG_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PREV_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION WATER_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION CO2_PROD_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_6(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION RAWGAS_DRYBASIS_VOLUME_SM3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
      TYPE REC_ROW_BY_PK IS RECORD (
         DATA_STAGE_CODE VARCHAR2 (2000) ,
         DAYTIME  DATE ,
         OBJECT_CODE VARCHAR2 (32) ,
         FORECAST_TYPE VARCHAR2 (32) ,
         PROBABILITY_TYPE VARCHAR2 (32) ,
         LNG_RATE NUMBER ,
         LNG_MASS_RATE NUMBER ,
         LNG_SMPP NUMBER ,
         LNG_MASS_SMPP NUMBER ,
         COND_RATE NUMBER ,
         COND_MASS_RATE NUMBER ,
         COND_SMPP NUMBER ,
         COND_MASS_SMPP NUMBER ,
         DOMGAS_RATE NUMBER ,
         DOMGAS_MASS_RATE NUMBER ,
         DOMGAS_ENERGY_RATE NUMBER ,
         DOMGAS_SMPP NUMBER ,
         DOMGAS_MASS_SMPP NUMBER ,
         DOMGAS_OPMAX_MASS NUMBER ,
         DOMGAS_OPMAX_ENERGY NUMBER ,
         DOMGAS_IMO NUMBER ,
         CO2_PROD_RATE NUMBER ,
         CO2_VENT_RATE NUMBER ,
         CO2_INJ_RATE NUMBER ,
         WATER_RATE NUMBER ,
         WATER_MASS_RATE NUMBER ,
         FUEL_GAS_RATE NUMBER ,
         FUEL_GAS_MASS_RATE NUMBER ,
         FLARE_GAS_RATE NUMBER ,
         FLARE_GAS_MASS_RATE NUMBER ,
         RAW_GAS_RATE NUMBER ,
         RAW_GAS_MASS_RATE NUMBER ,
         HC_GAS_RATE NUMBER ,
         HC_GAS_MASS_RATE NUMBER ,
         TEXT_1 VARCHAR2 (2000) ,
         TEXT_2 VARCHAR2 (2000) ,
         TEXT_3 VARCHAR2 (2000) ,
         TEXT_4 VARCHAR2 (2000) ,
         TEXT_5 VARCHAR2 (2000) ,
         TEXT_6 VARCHAR2 (2000) ,
         TEXT_7 VARCHAR2 (2000) ,
         TEXT_8 VARCHAR2 (2000) ,
         TEXT_9 VARCHAR2 (2000) ,
         TEXT_10 VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         DATE_6  DATE ,
         DATE_7  DATE ,
         DATE_8  DATE ,
         DATE_9  DATE ,
         DATE_10  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (240) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32) ,
         RAWGAS_DRYBASIS_TONNES NUMBER ,
         RAWGAS_DRYBASIS_MMSCF NUMBER ,
         RAWGAS_DRYBASIS_VOLUME_SM3 NUMBER ,
         HYDROCARBON_TONNES NUMBER ,
         HYDROCARBON_MMSCF NUMBER ,
         HYDROCARBON_VOLUME_SM3 NUMBER ,
         PLAT_OUTPUT_GAS_FLOW NUMBER ,
         PLAT_OUTPUT_COND_FLOW NUMBER ,
         PLAT_OUTPUT_WATER_FLOW NUMBER ,
         GAS_TO_LNG_FLOW NUMBER ,
         GAS_TO_DOMGAS_FLOW NUMBER ,
         COND_STAB_FLOW NUMBER  );
   FUNCTION ROW_BY_PK(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         DATA_STAGE_CODE VARCHAR2 (2000) ,
         DAYTIME  DATE ,
         OBJECT_CODE VARCHAR2 (32) ,
         FORECAST_TYPE VARCHAR2 (32) ,
         PROBABILITY_TYPE VARCHAR2 (32) ,
         LNG_RATE NUMBER ,
         LNG_MASS_RATE NUMBER ,
         LNG_SMPP NUMBER ,
         LNG_MASS_SMPP NUMBER ,
         COND_RATE NUMBER ,
         COND_MASS_RATE NUMBER ,
         COND_SMPP NUMBER ,
         COND_MASS_SMPP NUMBER ,
         DOMGAS_RATE NUMBER ,
         DOMGAS_MASS_RATE NUMBER ,
         DOMGAS_ENERGY_RATE NUMBER ,
         DOMGAS_SMPP NUMBER ,
         DOMGAS_MASS_SMPP NUMBER ,
         DOMGAS_OPMAX_MASS NUMBER ,
         DOMGAS_OPMAX_ENERGY NUMBER ,
         DOMGAS_IMO NUMBER ,
         CO2_PROD_RATE NUMBER ,
         CO2_VENT_RATE NUMBER ,
         CO2_INJ_RATE NUMBER ,
         WATER_RATE NUMBER ,
         WATER_MASS_RATE NUMBER ,
         FUEL_GAS_RATE NUMBER ,
         FUEL_GAS_MASS_RATE NUMBER ,
         FLARE_GAS_RATE NUMBER ,
         FLARE_GAS_MASS_RATE NUMBER ,
         RAW_GAS_RATE NUMBER ,
         RAW_GAS_MASS_RATE NUMBER ,
         HC_GAS_RATE NUMBER ,
         HC_GAS_MASS_RATE NUMBER ,
         TEXT_1 VARCHAR2 (2000) ,
         TEXT_2 VARCHAR2 (2000) ,
         TEXT_3 VARCHAR2 (2000) ,
         TEXT_4 VARCHAR2 (2000) ,
         TEXT_5 VARCHAR2 (2000) ,
         TEXT_6 VARCHAR2 (2000) ,
         TEXT_7 VARCHAR2 (2000) ,
         TEXT_8 VARCHAR2 (2000) ,
         TEXT_9 VARCHAR2 (2000) ,
         TEXT_10 VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         DATE_6  DATE ,
         DATE_7  DATE ,
         DATE_8  DATE ,
         DATE_9  DATE ,
         DATE_10  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (240) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32) ,
         RAWGAS_DRYBASIS_TONNES NUMBER ,
         RAWGAS_DRYBASIS_MMSCF NUMBER ,
         RAWGAS_DRYBASIS_VOLUME_SM3 NUMBER ,
         HYDROCARBON_TONNES NUMBER ,
         HYDROCARBON_MMSCF NUMBER ,
         HYDROCARBON_VOLUME_SM3 NUMBER ,
         PLAT_OUTPUT_GAS_FLOW NUMBER ,
         PLAT_OUTPUT_COND_FLOW NUMBER ,
         PLAT_OUTPUT_WATER_FLOW NUMBER ,
         GAS_TO_LNG_FLOW NUMBER ,
         GAS_TO_DOMGAS_FLOW NUMBER ,
         COND_STAB_FLOW NUMBER  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_2(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_9(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_2(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION WATER_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COND_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_4(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DOMGAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DOMGAS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION GAS_TO_LNG_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION HYDROCARBON_TONNES(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PLAT_OUTPUT_WATER_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COND_MASS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DATE_8(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DOMGAS_MASS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION FLARE_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION FLARE_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION HYDROCARBON_MMSCF(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PLAT_OUTPUT_COND_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_8(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;

END RP_CT_STAGE_PLANT_FORECAST;

/



CREATE or REPLACE PACKAGE BODY RP_CT_STAGE_PLANT_FORECAST
IS

   FUNCTION DATE_10(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_10      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_10;
   FUNCTION GAS_TO_DOMGAS_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.GAS_TO_DOMGAS_FLOW      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END GAS_TO_DOMGAS_FLOW;
   FUNCTION HC_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.HC_GAS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END HC_GAS_RATE;
   FUNCTION RAWGAS_DRYBASIS_TONNES(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.RAWGAS_DRYBASIS_TONNES      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RAWGAS_DRYBASIS_TONNES;
   FUNCTION RAW_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.RAW_GAS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RAW_GAS_RATE;
   FUNCTION TEXT_4(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_4      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION TEXT_7(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_7      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_7;
   FUNCTION APPROVAL_BY(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.APPROVAL_BY      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.APPROVAL_STATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION LNG_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.LNG_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END LNG_MASS_RATE;
   FUNCTION RAW_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.RAW_GAS_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RAW_GAS_MASS_RATE;
   FUNCTION VALUE_5(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_5      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION COND_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.COND_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COND_MASS_RATE;
   FUNCTION COND_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.COND_SMPP      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COND_SMPP;
   FUNCTION DATE_7(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_7      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_7;
   FUNCTION DATE_9(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_9      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_9;
   FUNCTION DOMGAS_ENERGY_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_ENERGY_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_ENERGY_RATE;
   FUNCTION DOMGAS_IMO(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_IMO      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_IMO;
   FUNCTION DOMGAS_OPMAX_ENERGY(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_OPMAX_ENERGY      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_OPMAX_ENERGY;
   FUNCTION DOMGAS_OPMAX_MASS(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_OPMAX_MASS      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_OPMAX_MASS;
   FUNCTION DOMGAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_RATE;
   FUNCTION FUEL_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.FUEL_GAS_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END FUEL_GAS_MASS_RATE;
   FUNCTION NEXT_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.NEXT_DAYTIME      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.PREV_EQUAL_DAYTIME      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION TEXT_10(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_10      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_10;
   FUNCTION TEXT_5(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_5      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION TEXT_6(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_6      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_6;
   FUNCTION CO2_VENT_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.CO2_VENT_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END CO2_VENT_RATE;
   FUNCTION COND_STAB_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.COND_STAB_FLOW      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COND_STAB_FLOW;
   FUNCTION DATE_3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_3      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_5      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_5;
   FUNCTION FUEL_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.FUEL_GAS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END FUEL_GAS_RATE;
   FUNCTION LNG_MASS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.LNG_MASS_SMPP      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END LNG_MASS_SMPP;
   FUNCTION LNG_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.LNG_SMPP      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END LNG_SMPP;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.NEXT_EQUAL_DAYTIME      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION PLAT_OUTPUT_GAS_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.PLAT_OUTPUT_GAS_FLOW      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PLAT_OUTPUT_GAS_FLOW;
   FUNCTION RAWGAS_DRYBASIS_MMSCF(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.RAWGAS_DRYBASIS_MMSCF      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RAWGAS_DRYBASIS_MMSCF;
   FUNCTION VALUE_6(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_6      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION CO2_INJ_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.CO2_INJ_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END CO2_INJ_RATE;
   FUNCTION DATE_2(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_2      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_2;
   FUNCTION HC_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.HC_GAS_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END HC_GAS_MASS_RATE;
   FUNCTION HYDROCARBON_VOLUME_SM3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.HYDROCARBON_VOLUME_SM3      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END HYDROCARBON_VOLUME_SM3;
   FUNCTION LNG_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.LNG_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END LNG_RATE;
   FUNCTION PREV_DAYTIME(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.PREV_DAYTIME      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.RECORD_STATUS      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_1      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION WATER_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.WATER_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END WATER_MASS_RATE;
   FUNCTION APPROVAL_DATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.APPROVAL_DATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION CO2_PROD_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.CO2_PROD_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END CO2_PROD_RATE;
   FUNCTION DATE_6(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_6      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_6;
   FUNCTION RAWGAS_DRYBASIS_VOLUME_SM3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.RAWGAS_DRYBASIS_VOLUME_SM3      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RAWGAS_DRYBASIS_VOLUME_SM3;
   FUNCTION ROW_BY_PK(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.ROW_BY_PK      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.ROW_BY_REL_OPERATOR      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_2(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_2      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION TEXT_9(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_9      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_9;
   FUNCTION VALUE_2(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_2      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_3      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_4      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION WATER_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.WATER_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END WATER_RATE;
   FUNCTION COND_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.COND_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COND_RATE;
   FUNCTION DATE_4(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_4      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_4;
   FUNCTION DOMGAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_MASS_RATE;
   FUNCTION DOMGAS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_SMPP      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_SMPP;
   FUNCTION GAS_TO_LNG_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.GAS_TO_LNG_FLOW      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END GAS_TO_LNG_FLOW;
   FUNCTION HYDROCARBON_TONNES(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.HYDROCARBON_TONNES      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END HYDROCARBON_TONNES;
   FUNCTION PLAT_OUTPUT_WATER_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.PLAT_OUTPUT_WATER_FLOW      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PLAT_OUTPUT_WATER_FLOW;
   FUNCTION REC_ID(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.REC_ID      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_1      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION VALUE_7(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_7      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_9      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION COND_MASS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.COND_MASS_SMPP      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COND_MASS_SMPP;
   FUNCTION DATE_1(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_1      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_1;
   FUNCTION DATE_8(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DATE_8      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_8;
   FUNCTION DOMGAS_MASS_SMPP(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.DOMGAS_MASS_SMPP      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DOMGAS_MASS_SMPP;
   FUNCTION FLARE_GAS_MASS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.FLARE_GAS_MASS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END FLARE_GAS_MASS_RATE;
   FUNCTION FLARE_GAS_RATE(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.FLARE_GAS_RATE      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END FLARE_GAS_RATE;
   FUNCTION HYDROCARBON_MMSCF(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.HYDROCARBON_MMSCF      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END HYDROCARBON_MMSCF;
   FUNCTION PLAT_OUTPUT_COND_FLOW(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.PLAT_OUTPUT_COND_FLOW      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PLAT_OUTPUT_COND_FLOW;
   FUNCTION TEXT_3(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_3      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_8(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.TEXT_8      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_8;
   FUNCTION VALUE_10(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_10      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_DATA_STAGE_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_OBJECT_CODE IN VARCHAR2,
      P_FORECAST_TYPE IN VARCHAR2,
      P_PROBABILITY_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_STAGE_PLANT_FORECAST.VALUE_8      (
         P_DATA_STAGE_CODE,
         P_DAYTIME,
         P_OBJECT_CODE,
         P_FORECAST_TYPE,
         P_PROBABILITY_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_8;

END RP_CT_STAGE_PLANT_FORECAST;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CT_STAGE_PLANT_FORECAST TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.14.21 AM


