
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.19.16 AM


CREATE or REPLACE PACKAGE RP_CONT_TRANS_COMMENTS
IS

   FUNCTION SORT_ORDER(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION COLUMN_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION OBJECT_ID(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION COMMENTS(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_3(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION DATE_5(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION VALUE_6(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_2(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION DESCRIPTION(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         TRANSACTION_KEY VARCHAR2 (32) ,
         TRANS_COMMENTS_ID VARCHAR2 (32) ,
         COLUMN_1 VARCHAR2 (2000) ,
         CONT_TRANS_COMMENTS_TYPE VARCHAR2 (32) ,
         DESCRIPTION VARCHAR2 (240) ,
         SORT_ORDER NUMBER ,
         COMMENTS VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION VALUE_2(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_4(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION REC_ID(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION CONT_TRANS_COMMENTS_TYPE(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION VALUE_10(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER;

END RP_CONT_TRANS_COMMENTS;

/



CREATE or REPLACE PACKAGE BODY RP_CONT_TRANS_COMMENTS
IS

   FUNCTION SORT_ORDER(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.SORT_ORDER      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END SORT_ORDER;
   FUNCTION TEXT_3(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.TEXT_3      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.TEXT_4      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION APPROVAL_BY(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.APPROVAL_BY      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.APPROVAL_STATE      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION VALUE_5(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_5      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION COLUMN_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.COLUMN_1      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END COLUMN_1;
   FUNCTION OBJECT_ID(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.OBJECT_ID      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END OBJECT_ID;
   FUNCTION COMMENTS(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.COMMENTS      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION DATE_3(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.DATE_3      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.DATE_5      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END DATE_5;
   FUNCTION VALUE_6(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_6      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION DATE_2(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.DATE_2      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END DATE_2;
   FUNCTION RECORD_STATUS(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.RECORD_STATUS      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_1      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.APPROVAL_DATE      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION DESCRIPTION(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.DESCRIPTION      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END DESCRIPTION;
   FUNCTION ROW_BY_PK(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.ROW_BY_PK      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION VALUE_2(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_2      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_3      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_4      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION DATE_4(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.DATE_4      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END DATE_4;
   FUNCTION REC_ID(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.REC_ID      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.TEXT_1      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.TEXT_2      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_7(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_7      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_9      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION CONT_TRANS_COMMENTS_TYPE(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.CONT_TRANS_COMMENTS_TYPE      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END CONT_TRANS_COMMENTS_TYPE;
   FUNCTION DATE_1(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.DATE_1      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END DATE_1;
   FUNCTION VALUE_10(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_10      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_TRANSACTION_KEY IN VARCHAR2,
      P_TRANS_COMMENTS_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_TRANS_COMMENTS.VALUE_8      (
         P_TRANSACTION_KEY,
         P_TRANS_COMMENTS_ID );
         RETURN ret_value;
   END VALUE_8;

END RP_CONT_TRANS_COMMENTS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CONT_TRANS_COMMENTS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.19.23 AM


