
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.49.37 AM


CREATE or REPLACE PACKAGE RP_CARRIER_INSPECTION
IS

   FUNCTION CARRIER_TANK_NO(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_20(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION INSPECTION_TYPE(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_15(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_16(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION DIP_LEVEL_PORT(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION DIP_LEVEL_CENTER(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION TEXT_11(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_17(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_18(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_9(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION CARGO_NO(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_19(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN DATE;
   FUNCTION DIP_LEVEL_STARBOARD(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         INSPECTION_NO NUMBER ,
         INSPECTION_TYPE VARCHAR2 (32) ,
         CARRIER_TANK_NO VARCHAR2 (32) ,
         CARGO_NO NUMBER ,
         DIP_LEVEL_CENTER NUMBER ,
         DIP_LEVEL_PORT NUMBER ,
         DIP_LEVEL_STARBOARD NUMBER ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         VALUE_11 NUMBER ,
         VALUE_12 NUMBER ,
         VALUE_13 NUMBER ,
         VALUE_14 NUMBER ,
         VALUE_15 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         COMMENTS VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         TEXT_9 VARCHAR2 (240) ,
         TEXT_10 VARCHAR2 (240) ,
         TEXT_11 VARCHAR2 (240) ,
         TEXT_12 VARCHAR2 (240) ,
         TEXT_13 VARCHAR2 (240) ,
         TEXT_14 VARCHAR2 (240) ,
         TEXT_15 VARCHAR2 (240) ,
         TEXT_16 VARCHAR2 (240) ,
         TEXT_17 VARCHAR2 (240) ,
         TEXT_18 VARCHAR2 (240) ,
         TEXT_19 VARCHAR2 (240) ,
         TEXT_20 VARCHAR2 (240)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN REC_ROW_BY_PK;
   FUNCTION TEXT_12(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_13(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN DATE;
   FUNCTION TEXT_10(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_14(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER;

END RP_CARRIER_INSPECTION;

/



CREATE or REPLACE PACKAGE BODY RP_CARRIER_INSPECTION
IS

   FUNCTION CARRIER_TANK_NO(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.CARRIER_TANK_NO      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END CARRIER_TANK_NO;
   FUNCTION TEXT_20(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_20      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_20;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_3      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_4      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.APPROVAL_BY      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION INSPECTION_TYPE(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.INSPECTION_TYPE      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END INSPECTION_TYPE;
   FUNCTION TEXT_15(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_15      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_15;
   FUNCTION TEXT_16(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_16      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_16;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_5      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION DIP_LEVEL_PORT(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.DIP_LEVEL_PORT      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END DIP_LEVEL_PORT;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_7      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_7;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_8      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_8;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.COMMENTS      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION DIP_LEVEL_CENTER(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.DIP_LEVEL_CENTER      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END DIP_LEVEL_CENTER;
   FUNCTION TEXT_11(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_11      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_11;
   FUNCTION TEXT_17(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_17      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_17;
   FUNCTION TEXT_18(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_18      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_18;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_6      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_6;
   FUNCTION TEXT_9(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_9      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_9;
   FUNCTION VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_12      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_12;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_6      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION CARGO_NO(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.CARGO_NO      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END CARGO_NO;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.DATE_2      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END DATE_2;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.RECORD_STATUS      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION TEXT_19(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_19      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_19;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_1      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_15      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_15;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION DIP_LEVEL_STARBOARD(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.DIP_LEVEL_STARBOARD      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END DIP_LEVEL_STARBOARD;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.ROW_BY_PK      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION TEXT_12(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_12      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_12;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_5      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_13      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_13;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_2      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_3      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_4      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.REC_ID      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_1      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_13(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_13      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_13;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_2      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_7      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_9      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.DATE_1      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END DATE_1;
   FUNCTION TEXT_10(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_10      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_10;
   FUNCTION TEXT_14(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.TEXT_14      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END TEXT_14;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_10      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_11      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_11;
   FUNCTION VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_14      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_14;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_INSPECTION_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARRIER_INSPECTION.VALUE_8      (
         P_OBJECT_ID,
         P_INSPECTION_NO );
         RETURN ret_value;
   END VALUE_8;

END RP_CARRIER_INSPECTION;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CARRIER_INSPECTION TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.49.47 AM


