
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.32.32 AM


CREATE or REPLACE PACKAGE RP_CT_COND_INV
IS

   FUNCTION ADJUSTMENT(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION CLOSING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION OUTGOING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION INCOMING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION OPENING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION FLAG(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         LIFTING_ACCOUNT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         CLASS_NAME VARCHAR2 (32) ,
         OPENING NUMBER ,
         INCOMING NUMBER ,
         OUTGOING NUMBER ,
         ADJUSTMENT NUMBER ,
         CLOSING NUMBER ,
         FLAG VARCHAR2 (32) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (240) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         LIFTING_ACCOUNT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         CLASS_NAME VARCHAR2 (32) ,
         OPENING NUMBER ,
         INCOMING NUMBER ,
         OUTGOING NUMBER ,
         ADJUSTMENT NUMBER ,
         CLOSING NUMBER ,
         FLAG VARCHAR2 (32) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (240) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;

END RP_CT_COND_INV;

/



CREATE or REPLACE PACKAGE BODY RP_CT_COND_INV
IS

   FUNCTION ADJUSTMENT(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.ADJUSTMENT      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ADJUSTMENT;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CT_COND_INV.TEXT_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_COND_INV.TEXT_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CT_COND_INV.APPROVAL_BY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CT_COND_INV.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION CLOSING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.CLOSING      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END CLOSING;
   FUNCTION OUTGOING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.OUTGOING      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END OUTGOING;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_5      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_COND_INV.NEXT_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_COND_INV.PREV_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION INCOMING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.INCOMING      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END INCOMING;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_COND_INV.NEXT_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_6      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION OPENING(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.OPENING      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END OPENING;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_COND_INV.PREV_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CT_COND_INV.RECORD_STATUS      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_COND_INV.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION FLAG(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_COND_INV.FLAG      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END FLAG;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CT_COND_INV.ROW_BY_PK      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_CT_COND_INV.ROW_BY_REL_OPERATOR      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_COND_INV.REC_ID      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_CT_COND_INV.TEXT_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_COND_INV.TEXT_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_7      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_9      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_10      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_LIFTING_ACCOUNT_ID IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_COND_INV.VALUE_8      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_LIFTING_ACCOUNT_ID,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_8;

END RP_CT_COND_INV;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CT_COND_INV TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.32.38 AM


