
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.33.11 AM


CREATE or REPLACE PACKAGE RP_CTRL_SYSTEM_ATTRIBUTE
IS

   FUNCTION APPROVAL_BY(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION ATTRIBUTE_TEXT(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION NEXT_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION COMMENTS(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION ATTRIBUTE_VALUE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION END_DATE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION PREV_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         DAYTIME  DATE ,
         ATTRIBUTE_TYPE VARCHAR2 (24) ,
         ATTRIBUTE_TEXT VARCHAR2 (1000) ,
         ATTRIBUTE_VALUE NUMBER ,
         END_DATE  DATE ,
         USER_VISIBLE_IND VARCHAR2 (1) ,
         COMMENTS VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         DAYTIME  DATE ,
         ATTRIBUTE_TYPE VARCHAR2 (24) ,
         ATTRIBUTE_TEXT VARCHAR2 (1000) ,
         ATTRIBUTE_VALUE NUMBER ,
         END_DATE  DATE ,
         USER_VISIBLE_IND VARCHAR2 (1) ,
         COMMENTS VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION USER_VISIBLE_IND(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION REC_ID(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;

END RP_CTRL_SYSTEM_ATTRIBUTE;

/



CREATE or REPLACE PACKAGE BODY RP_CTRL_SYSTEM_ATTRIBUTE
IS

   FUNCTION APPROVAL_BY(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.APPROVAL_BY      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.APPROVAL_STATE      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION ATTRIBUTE_TEXT(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1000) ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.ATTRIBUTE_TEXT      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ATTRIBUTE_TEXT;
   FUNCTION NEXT_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.NEXT_DAYTIME      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.PREV_EQUAL_DAYTIME      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION COMMENTS(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.COMMENTS      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.NEXT_EQUAL_DAYTIME      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION ATTRIBUTE_VALUE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.ATTRIBUTE_VALUE      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ATTRIBUTE_VALUE;
   FUNCTION END_DATE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.END_DATE      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END END_DATE;
   FUNCTION PREV_DAYTIME(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.PREV_DAYTIME      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.RECORD_STATUS      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.APPROVAL_DATE      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.ROW_BY_PK      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.ROW_BY_REL_OPERATOR      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION USER_VISIBLE_IND(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.USER_VISIBLE_IND      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END USER_VISIBLE_IND;
   FUNCTION REC_ID(
      P_DAYTIME IN DATE,
      P_ATTRIBUTE_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CTRL_SYSTEM_ATTRIBUTE.REC_ID      (
         P_DAYTIME,
         P_ATTRIBUTE_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;

END RP_CTRL_SYSTEM_ATTRIBUTE;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CTRL_SYSTEM_ATTRIBUTE TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.33.15 AM


