
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.08.45 AM


CREATE or REPLACE PACKAGE RP_DISTRIBUTION_SET
IS

   FUNCTION APPROVAL_BY(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION FUNCTIONAL_AREA_ID(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_4(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_2(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_3(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION RECORD_STATUS(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_5(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN DATE;
   FUNCTION NAME(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_1(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;
      TYPE REC_ROW_BY_PK IS RECORD (
         DISTRIBUTION_SET_CODE VARCHAR2 (32) ,
         NAME VARCHAR2 (240) ,
         FUNCTIONAL_AREA_ID VARCHAR2 (32) ,
         REF_OBJECT_ID_1 VARCHAR2 (32) ,
         REF_OBJECT_ID_2 VARCHAR2 (32) ,
         REF_OBJECT_ID_3 VARCHAR2 (32) ,
         REF_OBJECT_ID_4 VARCHAR2 (32) ,
         REF_OBJECT_ID_5 VARCHAR2 (32) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION REC_ID(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2;

END RP_DISTRIBUTION_SET;

/



CREATE or REPLACE PACKAGE BODY RP_DISTRIBUTION_SET
IS

   FUNCTION APPROVAL_BY(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.APPROVAL_BY      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.APPROVAL_STATE      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION FUNCTIONAL_AREA_ID(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.FUNCTIONAL_AREA_ID      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END FUNCTIONAL_AREA_ID;
   FUNCTION REF_OBJECT_ID_4(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.REF_OBJECT_ID_4      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END REF_OBJECT_ID_4;
   FUNCTION REF_OBJECT_ID_2(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.REF_OBJECT_ID_2      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END REF_OBJECT_ID_2;
   FUNCTION REF_OBJECT_ID_3(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.REF_OBJECT_ID_3      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END REF_OBJECT_ID_3;
   FUNCTION RECORD_STATUS(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.RECORD_STATUS      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION REF_OBJECT_ID_5(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.REF_OBJECT_ID_5      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END REF_OBJECT_ID_5;
   FUNCTION APPROVAL_DATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.APPROVAL_DATE      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION NAME(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.NAME      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END NAME;
   FUNCTION REF_OBJECT_ID_1(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.REF_OBJECT_ID_1      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END REF_OBJECT_ID_1;
   FUNCTION ROW_BY_PK(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.ROW_BY_PK      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION REC_ID(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET.REC_ID      (
         P_DISTRIBUTION_SET_CODE );
         RETURN ret_value;
   END REC_ID;

END RP_DISTRIBUTION_SET;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_DISTRIBUTION_SET TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.08.48 AM


