
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.08.43 AM


CREATE or REPLACE PACKAGE RP_DISTRIBUTION_SET_CONTACT
IS

   FUNCTION APPROVAL_BY(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION FORMAT_CODE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION RECORD_STATUS(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         DISTRIBUTION_SET_CODE VARCHAR2 (32) ,
         COMPANY_CONTACT_ID VARCHAR2 (32) ,
         RECIPIENT_TYPE VARCHAR2 (32) ,
         EDI_ADDRESS_CODE VARCHAR2 (32) ,
         FORMAT_CODE VARCHAR2 (32) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION EDI_ADDRESS_CODE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REC_ID(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2;

END RP_DISTRIBUTION_SET_CONTACT;

/



CREATE or REPLACE PACKAGE BODY RP_DISTRIBUTION_SET_CONTACT
IS

   FUNCTION APPROVAL_BY(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.APPROVAL_BY      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.APPROVAL_STATE      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION FORMAT_CODE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.FORMAT_CODE      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END FORMAT_CODE;
   FUNCTION RECORD_STATUS(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.RECORD_STATUS      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.APPROVAL_DATE      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.ROW_BY_PK      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION EDI_ADDRESS_CODE(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.EDI_ADDRESS_CODE      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END EDI_ADDRESS_CODE;
   FUNCTION REC_ID(
      P_DISTRIBUTION_SET_CODE IN VARCHAR2,
      P_COMPANY_CONTACT_ID IN VARCHAR2,
      P_RECIPIENT_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_DISTRIBUTION_SET_CONTACT.REC_ID      (
         P_DISTRIBUTION_SET_CODE,
         P_COMPANY_CONTACT_ID,
         P_RECIPIENT_TYPE );
         RETURN ret_value;
   END REC_ID;

END RP_DISTRIBUTION_SET_CONTACT;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_DISTRIBUTION_SET_CONTACT TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 10.08.45 AM


