
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 09.32.29 AM


CREATE or REPLACE PACKAGE RP_FCTY_DAY_VESSEL
IS

   FUNCTION MATH_LOADED_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION MATH_VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION COUNT_ROWS(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVED_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         FROM_DAYTIME  DATE ,
         TO_DAYTIME  DATE ,
         VESSEL_ID VARCHAR2 (16) ,
         VESSEL_TYPE VARCHAR2 (16) ,
         LOADED_QTY NUMBER (4) ,
         APPROVED_BY VARCHAR2 (30) ,
         COMMENTS VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         FROM_DAYTIME  DATE ,
         TO_DAYTIME  DATE ,
         VESSEL_ID VARCHAR2 (16) ,
         VESSEL_TYPE VARCHAR2 (16) ,
         LOADED_QTY NUMBER (4) ,
         APPROVED_BY VARCHAR2 (30) ,
         COMMENTS VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION TO_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION LOADED_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;

END RP_FCTY_DAY_VESSEL;

/



CREATE or REPLACE PACKAGE BODY RP_FCTY_DAY_VESSEL
IS

   FUNCTION MATH_LOADED_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_LOADED_QTY      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_LOADED_QTY;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.TEXT_3      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.TEXT_4      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.APPROVAL_BY      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION MATH_VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_3      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_3;
   FUNCTION MATH_VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_4      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_4;
   FUNCTION MATH_VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_8      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_8;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_5      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION MATH_VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_6      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_6;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.NEXT_DAYTIME      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.PREV_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.COMMENTS      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION COUNT_ROWS(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.COUNT_ROWS      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY );
         RETURN ret_value;
   END COUNT_ROWS;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.DATE_3      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.DATE_5      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_5;
   FUNCTION MATH_VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_1      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_1;
   FUNCTION MATH_VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_5      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_5;
   FUNCTION MATH_VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_7      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_7;
   FUNCTION MATH_VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_9      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_9;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.NEXT_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_6      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION APPROVED_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.APPROVED_BY      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVED_BY;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.DATE_2      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_2;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.PREV_DAYTIME      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.RECORD_STATUS      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_1      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION MATH_VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_2      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_2;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.ROW_BY_PK      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.ROW_BY_REL_OPERATOR      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION TO_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.TO_DAYTIME      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TO_DAYTIME;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_2      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_3      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_4      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.DATE_4      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_4;
   FUNCTION LOADED_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER (4) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.LOADED_QTY      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END LOADED_QTY;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.REC_ID      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.TEXT_1      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.TEXT_2      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_7      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_9      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.DATE_1      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_1;
   FUNCTION MATH_VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.MATH_VALUE_10      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_10;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_10      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_VESSEL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_DAYTIME IN DATE,
      P_VESSEL_TYPE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_FCTY_DAY_VESSEL.VALUE_8      (
         P_OBJECT_ID,
         P_VESSEL_ID,
         P_DAYTIME,
         P_FROM_DAYTIME,
         P_VESSEL_TYPE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_8;

END RP_FCTY_DAY_VESSEL;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_FCTY_DAY_VESSEL TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 09.32.39 AM


