
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 08.16.43 AM


CREATE or REPLACE PACKAGE RP_PVTSIM_PROP
IS

   FUNCTION PROPNO_07(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION PROPNO_12(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_13(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_16(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PROPNO_14(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_15(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_18(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PROPNO_03(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_05(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_11(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_17(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION PROPNO_02(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_04(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_06(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         RESULT_NO VARCHAR2 (32) ,
         CODE VARCHAR2 (250) ,
         PROPNO_01 NUMBER ,
         PROPNO_02 NUMBER ,
         PROPNO_03 NUMBER ,
         PROPNO_04 NUMBER ,
         PROPNO_05 NUMBER ,
         PROPNO_06 NUMBER ,
         PROPNO_07 NUMBER ,
         PROPNO_08 NUMBER ,
         PROPNO_09 NUMBER ,
         PROPNO_10 NUMBER ,
         PROPNO_11 NUMBER ,
         PROPNO_12 NUMBER ,
         PROPNO_13 NUMBER ,
         PROPNO_14 NUMBER ,
         PROPNO_15 NUMBER ,
         PROPNO_16 NUMBER ,
         PROPNO_17 NUMBER ,
         PROPNO_18 NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         RESULT_NO VARCHAR2 (32) ,
         CODE VARCHAR2 (250) ,
         PROPNO_01 NUMBER ,
         PROPNO_02 NUMBER ,
         PROPNO_03 NUMBER ,
         PROPNO_04 NUMBER ,
         PROPNO_05 NUMBER ,
         PROPNO_06 NUMBER ,
         PROPNO_07 NUMBER ,
         PROPNO_08 NUMBER ,
         PROPNO_09 NUMBER ,
         PROPNO_10 NUMBER ,
         PROPNO_11 NUMBER ,
         PROPNO_12 NUMBER ,
         PROPNO_13 NUMBER ,
         PROPNO_14 NUMBER ,
         PROPNO_15 NUMBER ,
         PROPNO_16 NUMBER ,
         PROPNO_17 NUMBER ,
         PROPNO_18 NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION PROPNO_08(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION PROPNO_01(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION PROPNO_09(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;

END RP_PVTSIM_PROP;

/



CREATE or REPLACE PACKAGE BODY RP_PVTSIM_PROP
IS

   FUNCTION PROPNO_07(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_07      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_07;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.APPROVAL_BY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION PROPNO_12(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_12      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_12;
   FUNCTION PROPNO_13(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_13      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_13;
   FUNCTION PROPNO_16(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_16      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_16;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.NEXT_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PREV_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION PROPNO_14(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_14      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_14;
   FUNCTION PROPNO_15(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_15      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_15;
   FUNCTION PROPNO_18(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_18      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_18;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.NEXT_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PREV_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION PROPNO_03(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_03      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_03;
   FUNCTION PROPNO_05(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_05      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_05;
   FUNCTION PROPNO_11(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_11      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_11;
   FUNCTION PROPNO_17(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_17      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_17;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.RECORD_STATUS      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION PROPNO_02(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_02      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_02;
   FUNCTION PROPNO_04(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_04      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_04;
   FUNCTION PROPNO_06(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_06      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_06;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.ROW_BY_PK      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.ROW_BY_REL_OPERATOR      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION PROPNO_08(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_08      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_08;
   FUNCTION PROPNO_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_10      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_10;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.REC_ID      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION PROPNO_01(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_01      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_01;
   FUNCTION PROPNO_09(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RESULT_NO IN VARCHAR2,
      P_CODE IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PVTSIM_PROP.PROPNO_09      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RESULT_NO,
         P_CODE,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PROPNO_09;

END RP_PVTSIM_PROP;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_PVTSIM_PROP TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 08.16.50 AM


