
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 08.18.36 AM


CREATE or REPLACE PACKAGE RP_PRICE_CONCEPT
IS

   FUNCTION INCOTERM_CODE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_3(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REVN_JOU_ENT_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION REVN_TA_COST_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REVN_TA_INCOME_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION CONTRACT_AREA_CODE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TRAN_DATE_METHOD(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_6(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION RECORD_STATUS(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN DATE;
   FUNCTION DESCRIPTION(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION NAME(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REVN_INVENTORY_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
      TYPE REC_ROW_BY_PK IS RECORD (
         PRICE_CONCEPT_CODE VARCHAR2 (32) ,
         NAME VARCHAR2 (240) ,
         INCOTERM_CODE VARCHAR2 (32) ,
         CONTRACT_AREA_CODE VARCHAR2 (32) ,
         TRAN_DATE_METHOD VARCHAR2 (32) ,
         REVN_JOU_ENT_IND VARCHAR2 (1) ,
         REVN_PURCHASES_IND VARCHAR2 (1) ,
         REVN_SALES_IND VARCHAR2 (1) ,
         REVN_TA_COST_IND VARCHAR2 (1) ,
         REVN_TA_INCOME_IND VARCHAR2 (1) ,
         REVN_INVENTORY_IND VARCHAR2 (1) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         DESCRIPTION VARCHAR2 (240) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION VALUE_2(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION REVN_PURCHASES_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REVN_SALES_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER;

END RP_PRICE_CONCEPT;

/



CREATE or REPLACE PACKAGE BODY RP_PRICE_CONCEPT
IS

   FUNCTION INCOTERM_CODE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.INCOTERM_CODE      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END INCOTERM_CODE;
   FUNCTION TEXT_3(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.TEXT_3      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.TEXT_4      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION APPROVAL_BY(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.APPROVAL_BY      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.APPROVAL_STATE      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION REVN_JOU_ENT_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.REVN_JOU_ENT_IND      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END REVN_JOU_ENT_IND;
   FUNCTION VALUE_5(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_5      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION REVN_TA_COST_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.REVN_TA_COST_IND      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END REVN_TA_COST_IND;
   FUNCTION REVN_TA_INCOME_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.REVN_TA_INCOME_IND      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END REVN_TA_INCOME_IND;
   FUNCTION CONTRACT_AREA_CODE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.CONTRACT_AREA_CODE      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END CONTRACT_AREA_CODE;
   FUNCTION TRAN_DATE_METHOD(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.TRAN_DATE_METHOD      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END TRAN_DATE_METHOD;
   FUNCTION VALUE_6(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_6      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION RECORD_STATUS(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.RECORD_STATUS      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_1      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.APPROVAL_DATE      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION DESCRIPTION(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.DESCRIPTION      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END DESCRIPTION;
   FUNCTION NAME(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.NAME      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END NAME;
   FUNCTION REVN_INVENTORY_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.REVN_INVENTORY_IND      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END REVN_INVENTORY_IND;
   FUNCTION ROW_BY_PK(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.ROW_BY_PK      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION VALUE_2(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_2      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_3      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_4      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION REC_ID(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.REC_ID      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.TEXT_1      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.TEXT_2      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_7(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_7      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_9      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION REVN_PURCHASES_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.REVN_PURCHASES_IND      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END REVN_PURCHASES_IND;
   FUNCTION REVN_SALES_IND(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.REVN_SALES_IND      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END REVN_SALES_IND;
   FUNCTION VALUE_10(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_10      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_PRICE_CONCEPT_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_PRICE_CONCEPT.VALUE_8      (
         P_PRICE_CONCEPT_CODE );
         RETURN ret_value;
   END VALUE_8;

END RP_PRICE_CONCEPT;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_PRICE_CONCEPT TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 08.18.46 AM


