
 -- START PKG_GEN_PKGS.sf_get_functions at:11/15/2018 08.05.20 AM


CREATE or REPLACE PACKAGE RP_REPORT_GROUP_CONN
IS

   FUNCTION SORT_ORDER(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION END_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         OBJECT_CLASS VARCHAR2 (32) ,
         CHILD_OBJ_ID VARCHAR2 (32) ,
         START_DATE  DATE ,
         END_DATE  DATE ,
         SORT_ORDER NUMBER ,
         COMMENTS VARCHAR2 (2000) ,
         TEXT_1 VARCHAR2 (240) ,
         TEXT_2 VARCHAR2 (240) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (240) ,
         TEXT_5 VARCHAR2 (240) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN REC_ROW_BY_PK;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2;

END RP_REPORT_GROUP_CONN;

/



CREATE or REPLACE PACKAGE BODY RP_REPORT_GROUP_CONN
IS

   FUNCTION SORT_ORDER(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.SORT_ORDER      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END SORT_ORDER;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.TEXT_3      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.APPROVAL_BY      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.VALUE_5      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.COMMENTS      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.TEXT_1      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION END_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.END_DATE      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END END_DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.RECORD_STATUS      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.VALUE_1      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.ROW_BY_PK      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.TEXT_2      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.TEXT_4      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.TEXT_5      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.VALUE_2      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.VALUE_3      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.VALUE_4      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_OBJECT_CLASS IN VARCHAR2,
      P_CHILD_OBJ_ID IN VARCHAR2,
      P_START_DATE IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_REPORT_GROUP_CONN.REC_ID      (
         P_OBJECT_ID,
         P_OBJECT_CLASS,
         P_CHILD_OBJ_ID,
         P_START_DATE );
         RETURN ret_value;
   END REC_ID;

END RP_REPORT_GROUP_CONN;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_REPORT_GROUP_CONN TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/15/2018 08.05.24 AM


