
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 05.23.19 AM


CREATE or REPLACE PACKAGE RP_WEBO_INT_PRESSURE_TEST
IS

   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_16(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_18(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_21(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_27(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_30(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_37(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_47(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_48(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_51(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_59(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_67(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_71(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_76(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_78(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_23(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_28(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_42(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_46(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_56(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_60(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_61(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_68(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_74(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_77(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RBF_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_29(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_31(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_32(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_36(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_54(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_62(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_75(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_22(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_26(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_45(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_49(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_58(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_66(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_73(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_19(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_33(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_34(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_52(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_63(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_65(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_72(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         CLASS_NAME VARCHAR2 (24) ,
         PERF_INTERVAL_ID VARCHAR2 (32) ,
         TEST_TYPE VARCHAR2 (32) ,
         RBF_ID VARCHAR2 (32) ,
         COMMENTS VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         VALUE_11 NUMBER ,
         VALUE_12 NUMBER ,
         VALUE_13 NUMBER ,
         VALUE_14 NUMBER ,
         VALUE_15 NUMBER ,
         VALUE_16 NUMBER ,
         VALUE_17 NUMBER ,
         VALUE_18 NUMBER ,
         VALUE_19 NUMBER ,
         VALUE_20 NUMBER ,
         VALUE_21 NUMBER ,
         VALUE_22 NUMBER ,
         VALUE_23 NUMBER ,
         VALUE_24 NUMBER ,
         VALUE_25 NUMBER ,
         VALUE_26 NUMBER ,
         VALUE_27 NUMBER ,
         VALUE_28 NUMBER ,
         VALUE_29 NUMBER ,
         VALUE_30 NUMBER ,
         VALUE_31 NUMBER ,
         VALUE_32 NUMBER ,
         VALUE_33 NUMBER ,
         VALUE_34 NUMBER ,
         VALUE_35 NUMBER ,
         VALUE_36 NUMBER ,
         VALUE_37 NUMBER ,
         VALUE_38 NUMBER ,
         VALUE_39 NUMBER ,
         VALUE_40 NUMBER ,
         VALUE_41 NUMBER ,
         VALUE_42 NUMBER ,
         VALUE_43 NUMBER ,
         VALUE_44 NUMBER ,
         VALUE_45 NUMBER ,
         VALUE_46 NUMBER ,
         VALUE_47 NUMBER ,
         VALUE_48 NUMBER ,
         VALUE_49 NUMBER ,
         VALUE_50 NUMBER ,
         VALUE_51 NUMBER ,
         VALUE_52 NUMBER ,
         VALUE_53 NUMBER ,
         VALUE_54 NUMBER ,
         VALUE_55 NUMBER ,
         VALUE_56 NUMBER ,
         VALUE_57 NUMBER ,
         VALUE_58 NUMBER ,
         VALUE_59 NUMBER ,
         VALUE_60 NUMBER ,
         VALUE_61 NUMBER ,
         VALUE_62 NUMBER ,
         VALUE_63 NUMBER ,
         VALUE_64 NUMBER ,
         VALUE_65 NUMBER ,
         VALUE_66 NUMBER ,
         VALUE_67 NUMBER ,
         VALUE_68 NUMBER ,
         VALUE_69 NUMBER ,
         VALUE_70 NUMBER ,
         VALUE_71 NUMBER ,
         VALUE_72 NUMBER ,
         VALUE_73 NUMBER ,
         VALUE_74 NUMBER ,
         VALUE_75 NUMBER ,
         VALUE_76 NUMBER ,
         VALUE_77 NUMBER ,
         VALUE_78 NUMBER ,
         VALUE_79 NUMBER ,
         VALUE_80 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DAYTIME  DATE ,
         CLASS_NAME VARCHAR2 (24) ,
         PERF_INTERVAL_ID VARCHAR2 (32) ,
         TEST_TYPE VARCHAR2 (32) ,
         RBF_ID VARCHAR2 (32) ,
         COMMENTS VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         VALUE_11 NUMBER ,
         VALUE_12 NUMBER ,
         VALUE_13 NUMBER ,
         VALUE_14 NUMBER ,
         VALUE_15 NUMBER ,
         VALUE_16 NUMBER ,
         VALUE_17 NUMBER ,
         VALUE_18 NUMBER ,
         VALUE_19 NUMBER ,
         VALUE_20 NUMBER ,
         VALUE_21 NUMBER ,
         VALUE_22 NUMBER ,
         VALUE_23 NUMBER ,
         VALUE_24 NUMBER ,
         VALUE_25 NUMBER ,
         VALUE_26 NUMBER ,
         VALUE_27 NUMBER ,
         VALUE_28 NUMBER ,
         VALUE_29 NUMBER ,
         VALUE_30 NUMBER ,
         VALUE_31 NUMBER ,
         VALUE_32 NUMBER ,
         VALUE_33 NUMBER ,
         VALUE_34 NUMBER ,
         VALUE_35 NUMBER ,
         VALUE_36 NUMBER ,
         VALUE_37 NUMBER ,
         VALUE_38 NUMBER ,
         VALUE_39 NUMBER ,
         VALUE_40 NUMBER ,
         VALUE_41 NUMBER ,
         VALUE_42 NUMBER ,
         VALUE_43 NUMBER ,
         VALUE_44 NUMBER ,
         VALUE_45 NUMBER ,
         VALUE_46 NUMBER ,
         VALUE_47 NUMBER ,
         VALUE_48 NUMBER ,
         VALUE_49 NUMBER ,
         VALUE_50 NUMBER ,
         VALUE_51 NUMBER ,
         VALUE_52 NUMBER ,
         VALUE_53 NUMBER ,
         VALUE_54 NUMBER ,
         VALUE_55 NUMBER ,
         VALUE_56 NUMBER ,
         VALUE_57 NUMBER ,
         VALUE_58 NUMBER ,
         VALUE_59 NUMBER ,
         VALUE_60 NUMBER ,
         VALUE_61 NUMBER ,
         VALUE_62 NUMBER ,
         VALUE_63 NUMBER ,
         VALUE_64 NUMBER ,
         VALUE_65 NUMBER ,
         VALUE_66 NUMBER ,
         VALUE_67 NUMBER ,
         VALUE_68 NUMBER ,
         VALUE_69 NUMBER ,
         VALUE_70 NUMBER ,
         VALUE_71 NUMBER ,
         VALUE_72 NUMBER ,
         VALUE_73 NUMBER ,
         VALUE_74 NUMBER ,
         VALUE_75 NUMBER ,
         VALUE_76 NUMBER ,
         VALUE_77 NUMBER ,
         VALUE_78 NUMBER ,
         VALUE_79 NUMBER ,
         VALUE_80 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_17(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_20(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_25(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_55(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_70(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_38(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_39(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_40(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_43(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_44(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_69(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_79(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_80(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION PERF_INTERVAL_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEST_TYPE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_24(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_35(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_41(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_50(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_53(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_57(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_64(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;

END RP_WEBO_INT_PRESSURE_TEST;

/



CREATE or REPLACE PACKAGE BODY RP_WEBO_INT_PRESSURE_TEST
IS

   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION VALUE_16(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_16      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_16;
   FUNCTION VALUE_18(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_18      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_18;
   FUNCTION VALUE_21(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_21      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_21;
   FUNCTION VALUE_27(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_27      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_27;
   FUNCTION VALUE_30(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_30      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_30;
   FUNCTION VALUE_37(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_37      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_37;
   FUNCTION VALUE_47(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_47      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_47;
   FUNCTION VALUE_48(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_48      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_48;
   FUNCTION VALUE_51(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_51      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_51;
   FUNCTION VALUE_59(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_59      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_59;
   FUNCTION VALUE_67(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_67      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_67;
   FUNCTION VALUE_71(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_71      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_71;
   FUNCTION VALUE_76(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_76      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_76;
   FUNCTION VALUE_78(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_78      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_78;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.APPROVAL_BY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION VALUE_23(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_23      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_23;
   FUNCTION VALUE_28(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_28      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_28;
   FUNCTION VALUE_42(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_42      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_42;
   FUNCTION VALUE_46(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_46      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_46;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_5      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION VALUE_56(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_56      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_56;
   FUNCTION VALUE_60(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_60      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_60;
   FUNCTION VALUE_61(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_61      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_61;
   FUNCTION VALUE_68(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_68      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_68;
   FUNCTION VALUE_74(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_74      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_74;
   FUNCTION VALUE_77(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_77      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_77;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.NEXT_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.PREV_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION RBF_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.RBF_ID      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RBF_ID;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_7      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_7;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_8      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_8;
   FUNCTION VALUE_29(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_29      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_29;
   FUNCTION VALUE_31(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_31      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_31;
   FUNCTION VALUE_32(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_32      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_32;
   FUNCTION VALUE_36(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_36      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_36;
   FUNCTION VALUE_54(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_54      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_54;
   FUNCTION VALUE_62(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_62      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_62;
   FUNCTION VALUE_75(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_75      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_75;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.COMMENTS      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.DATE_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.DATE_5      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_5;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.NEXT_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_6      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_6;
   FUNCTION VALUE_12(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_12      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_12;
   FUNCTION VALUE_22(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_22      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_22;
   FUNCTION VALUE_26(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_26      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_26;
   FUNCTION VALUE_45(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_45      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_45;
   FUNCTION VALUE_49(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_49      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_49;
   FUNCTION VALUE_58(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_58      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_58;
   FUNCTION VALUE_6(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_6      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION VALUE_66(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_66      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_66;
   FUNCTION VALUE_73(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_73      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_73;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.DATE_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_2;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.PREV_DAYTIME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.RECORD_STATUS      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION VALUE_15(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_15      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_15;
   FUNCTION VALUE_19(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_19      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_19;
   FUNCTION VALUE_33(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_33      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_33;
   FUNCTION VALUE_34(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_34      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_34;
   FUNCTION VALUE_52(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_52      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_52;
   FUNCTION VALUE_63(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_63      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_63;
   FUNCTION VALUE_65(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_65      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_65;
   FUNCTION VALUE_72(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_72      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_72;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.ROW_BY_PK      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.ROW_BY_REL_OPERATOR      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_5      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION VALUE_13(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_13      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_13;
   FUNCTION VALUE_17(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_17      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_17;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_20(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_20      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_20;
   FUNCTION VALUE_25(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_25      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_25;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_3      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION VALUE_55(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_55      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_55;
   FUNCTION VALUE_70(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_70      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_70;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.DATE_4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_4;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.REC_ID      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEXT_2      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_38(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_38      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_38;
   FUNCTION VALUE_39(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_39      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_39;
   FUNCTION VALUE_40(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_40      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_40;
   FUNCTION VALUE_43(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_43      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_43;
   FUNCTION VALUE_44(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_44      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_44;
   FUNCTION VALUE_69(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_69      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_69;
   FUNCTION VALUE_7(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_7      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_79(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_79      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_79;
   FUNCTION VALUE_80(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_80      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_80;
   FUNCTION VALUE_9(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_9      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.DATE_1      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_1;
   FUNCTION PERF_INTERVAL_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.PERF_INTERVAL_ID      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END PERF_INTERVAL_ID;
   FUNCTION TEST_TYPE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.TEST_TYPE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEST_TYPE;
   FUNCTION VALUE_10(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_10      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_11(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_11      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_11;
   FUNCTION VALUE_14(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_14      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_14;
   FUNCTION VALUE_24(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_24      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_24;
   FUNCTION VALUE_35(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_35      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_35;
   FUNCTION VALUE_41(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_41      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_41;
   FUNCTION VALUE_50(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_50      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_50;
   FUNCTION VALUE_53(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_53      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_53;
   FUNCTION VALUE_57(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_57      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_57;
   FUNCTION VALUE_64(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_64      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_64;
   FUNCTION VALUE_8(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_WEBO_INT_PRESSURE_TEST.VALUE_8      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_8;

END RP_WEBO_INT_PRESSURE_TEST;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_WEBO_INT_PRESSURE_TEST TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 05.23.48 AM


