
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.33.21 AM


CREATE or REPLACE PACKAGE RPBP_WELL_SUBDAILY
IS

   FUNCTION GETLASTSTOREDVALUE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ATTRIBUTE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETPERIODHRS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;

END RPBP_WELL_SUBDAILY;

/



CREATE or REPLACE PACKAGE BODY RPBP_WELL_SUBDAILY
IS

   FUNCTION GETLASTSTOREDVALUE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ATTRIBUTE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_SUBDAILY.GETLASTSTOREDVALUE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ATTRIBUTE );
         RETURN ret_value;
   END GETLASTSTOREDVALUE;
   FUNCTION GETPERIODHRS(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_SUBDAILY.GETPERIODHRS      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETPERIODHRS;

END RPBP_WELL_SUBDAILY;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_WELL_SUBDAILY TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.33.22 AM


