
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.35.14 AM


CREATE or REPLACE PACKAGE RPBP_IONANALYSIS
IS

   FUNCTION GETINJWATFRACMG(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETSCALEPOTBASO4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETSCALEPOTSRSO4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETDILUTEDBA(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETDILUTEDSR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETINJWATFRACSO4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETTOTDISSOLVED(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETIONBALANCE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER;

END RPBP_IONANALYSIS;

/



CREATE or REPLACE PACKAGE BODY RPBP_IONANALYSIS
IS

   FUNCTION GETINJWATFRACMG(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETINJWATFRACMG      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE,
         P_FORM_ANALYSIS_TYPE,
         P_INJ_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETINJWATFRACMG;
   FUNCTION GETSCALEPOTBASO4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETSCALEPOTBASO4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE,
         P_FORM_ANALYSIS_TYPE,
         P_INJ_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETSCALEPOTBASO4;
   FUNCTION GETSCALEPOTSRSO4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETSCALEPOTSRSO4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE,
         P_FORM_ANALYSIS_TYPE,
         P_INJ_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETSCALEPOTSRSO4;
   FUNCTION GETDILUTEDBA(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETDILUTEDBA      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE,
         P_FORM_ANALYSIS_TYPE,
         P_INJ_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETDILUTEDBA;
   FUNCTION GETDILUTEDSR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETDILUTEDSR      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE,
         P_FORM_ANALYSIS_TYPE,
         P_INJ_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETDILUTEDSR;
   FUNCTION GETINJWATFRACSO4(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_FORM_ANALYSIS_TYPE IN VARCHAR2,
      P_INJ_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETINJWATFRACSO4      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE,
         P_FORM_ANALYSIS_TYPE,
         P_INJ_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETINJWATFRACSO4;
   FUNCTION GETTOTDISSOLVED(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETTOTDISSOLVED      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETTOTDISSOLVED;
   FUNCTION GETIONBALANCE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_IONANALYSIS.GETIONBALANCE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETIONBALANCE;

END RPBP_IONANALYSIS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_IONANALYSIS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.35.17 AM


