
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.35.27 AM


CREATE or REPLACE PACKAGE RPBP_FLUID_ANALYSIS
IS

   FUNCTION GETPERIODCOMPSET(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION GETCOMPSET(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN VARCHAR2;

END RPBP_FLUID_ANALYSIS;

/



CREATE or REPLACE PACKAGE BODY RPBP_FLUID_ANALYSIS
IS

   FUNCTION GETPERIODCOMPSET(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECBP_FLUID_ANALYSIS.GETPERIODCOMPSET      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETPERIODCOMPSET;
   FUNCTION GETCOMPSET(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_ANALYSIS_TYPE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECBP_FLUID_ANALYSIS.GETCOMPSET      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_DAYTIME,
         P_ANALYSIS_TYPE );
         RETURN ret_value;
   END GETCOMPSET;

END RPBP_FLUID_ANALYSIS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_FLUID_ANALYSIS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.35.28 AM


