
 -- START PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.39.51 AM


CREATE or REPLACE PACKAGE RPBP_ACCOUNT_STATUS
IS

   FUNCTION ADJUSTMENT(
      P_STORAGE_ID IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2,
      P_STARTDAY IN DATE,
      P_ENDDAY IN DATE)
      RETURN NUMBER;
   FUNCTION PRODUCER_BALANCE(
      P_STORAGE_ID IN VARCHAR2,
      P_ACCOUNT_NO IN VARCHAR2,
      P_TRANSACTION_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER;
   FUNCTION REFINERY_OFFTAKE(
      P_STORAGE_ID IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2,
      P_STARTDAY IN DATE,
      P_ENDDAY IN DATE)
      RETURN NUMBER;

END RPBP_ACCOUNT_STATUS;

/



CREATE or REPLACE PACKAGE BODY RPBP_ACCOUNT_STATUS
IS

   FUNCTION ADJUSTMENT(
      P_STORAGE_ID IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2,
      P_STARTDAY IN DATE,
      P_ENDDAY IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_ACCOUNT_STATUS.ADJUSTMENT      (
         P_STORAGE_ID,
         P_COMPANY_ID,
         P_STARTDAY,
         P_ENDDAY );
         RETURN ret_value;
   END ADJUSTMENT;
   FUNCTION PRODUCER_BALANCE(
      P_STORAGE_ID IN VARCHAR2,
      P_ACCOUNT_NO IN VARCHAR2,
      P_TRANSACTION_TYPE IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_ACCOUNT_STATUS.PRODUCER_BALANCE      (
         P_STORAGE_ID,
         P_ACCOUNT_NO,
         P_TRANSACTION_TYPE,
         P_FROM_DAY,
         P_TO_DAY );
         RETURN ret_value;
   END PRODUCER_BALANCE;
   FUNCTION REFINERY_OFFTAKE(
      P_STORAGE_ID IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2,
      P_STARTDAY IN DATE,
      P_ENDDAY IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_ACCOUNT_STATUS.REFINERY_OFFTAKE      (
         P_STORAGE_ID,
         P_COMPANY_ID,
         P_STARTDAY,
         P_ENDDAY );
         RETURN ret_value;
   END REFINERY_OFFTAKE;

END RPBP_ACCOUNT_STATUS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_ACCOUNT_STATUS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.39.52 AM


