
 -- START PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.13 AM


CREATE or REPLACE PACKAGE RPBP_WET_GAS
IS

   FUNCTION GETDAILYFLOWRATEPRHOUR(
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION GETPROCESSINGUNITFLOWRATEPRHR(
      P_DAYTIME IN DATE,
      P_FLOW_RATE IN NUMBER,
      P_PROCESSING_UNIT IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION PRODUCTIONDATE(
      P_DAYTIME IN DATE,
      P_LIMIT IN VARCHAR2)
      RETURN DATE;

END RPBP_WET_GAS;

/



CREATE or REPLACE PACKAGE BODY RPBP_WET_GAS
IS

   FUNCTION GETDAILYFLOWRATEPRHOUR(
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WET_GAS.GETDAILYFLOWRATEPRHOUR      (
         P_DAYTIME );
         RETURN ret_value;
   END GETDAILYFLOWRATEPRHOUR;
   FUNCTION GETPROCESSINGUNITFLOWRATEPRHR(
      P_DAYTIME IN DATE,
      P_FLOW_RATE IN NUMBER,
      P_PROCESSING_UNIT IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WET_GAS.GETPROCESSINGUNITFLOWRATEPRHR      (
         P_DAYTIME,
         P_FLOW_RATE,
         P_PROCESSING_UNIT );
         RETURN ret_value;
   END GETPROCESSINGUNITFLOWRATEPRHR;
   FUNCTION PRODUCTIONDATE(
      P_DAYTIME IN DATE,
      P_LIMIT IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := ECBP_WET_GAS.PRODUCTIONDATE      (
         P_DAYTIME,
         P_LIMIT );
         RETURN ret_value;
   END PRODUCTIONDATE;

END RPBP_WET_GAS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_WET_GAS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.14 AM


