
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.35.23 AM


CREATE or REPLACE PACKAGE RPBP_FORECAST_EVENT
IS

   FUNCTION COUNTCHILDEVENT(
      P_EVENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION ISASSOCIATEDWITHGROUP(
      P_REASON_GROUP IN VARCHAR2,
      P_REASON_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION GETEVENTLOSSVOLUME(
      P_EVENT_NO IN NUMBER,
      P_PHASE IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION GETPARENTEVENTLOSSRATE(
      P_EVENT_NO IN NUMBER,
      P_EVENT_ATTRIBUTE IN VARCHAR2,
      P_DEFERMENT_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETPOTENTIALRATE(
      P_EVENT_NO IN NUMBER,
      P_POTENTIAL_ATTRIBUTE IN VARCHAR2)
      RETURN NUMBER;

END RPBP_FORECAST_EVENT;

/



CREATE or REPLACE PACKAGE BODY RPBP_FORECAST_EVENT
IS

   FUNCTION COUNTCHILDEVENT(
      P_EVENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_FORECAST_EVENT.COUNTCHILDEVENT      (
         P_EVENT_NO );
         RETURN ret_value;
   END COUNTCHILDEVENT;
   FUNCTION ISASSOCIATEDWITHGROUP(
      P_REASON_GROUP IN VARCHAR2,
      P_REASON_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECBP_FORECAST_EVENT.ISASSOCIATEDWITHGROUP      (
         P_REASON_GROUP,
         P_REASON_CODE );
         RETURN ret_value;
   END ISASSOCIATEDWITHGROUP;
   FUNCTION GETEVENTLOSSVOLUME(
      P_EVENT_NO IN NUMBER,
      P_PHASE IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_FORECAST_EVENT.GETEVENTLOSSVOLUME      (
         P_EVENT_NO,
         P_PHASE,
         P_OBJECT_ID );
         RETURN ret_value;
   END GETEVENTLOSSVOLUME;
   FUNCTION GETPARENTEVENTLOSSRATE(
      P_EVENT_NO IN NUMBER,
      P_EVENT_ATTRIBUTE IN VARCHAR2,
      P_DEFERMENT_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_FORECAST_EVENT.GETPARENTEVENTLOSSRATE      (
         P_EVENT_NO,
         P_EVENT_ATTRIBUTE,
         P_DEFERMENT_TYPE );
         RETURN ret_value;
   END GETPARENTEVENTLOSSRATE;
   FUNCTION GETPOTENTIALRATE(
      P_EVENT_NO IN NUMBER,
      P_POTENTIAL_ATTRIBUTE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_FORECAST_EVENT.GETPOTENTIALRATE      (
         P_EVENT_NO,
         P_POTENTIAL_ATTRIBUTE );
         RETURN ret_value;
   END GETPOTENTIALRATE;

END RPBP_FORECAST_EVENT;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_FORECAST_EVENT TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.35.25 AM


