
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.33.29 AM


CREATE or REPLACE PACKAGE RPBP_WELL_HOOKUP_THEORETICAL
IS

   FUNCTION CALCSUMOPERWELLHOOKDILUENTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPWATDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKGASLIFTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKOILDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKOILMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKWATINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPGASDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPWATINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPWATMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKCO2DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKCO2INJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKCONDDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKSTEAMINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPGASINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPOILDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKGASDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKGASMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPDILUENTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPCO2INJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPCONDDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPCONDMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPGASMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION GETWELLHOOKPHASEMASSFACTORDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_PHASE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKWATDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKWATMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPGASLIFTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPSTEAMINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION GETWELLHOOKPHASEFACTORDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_PHASE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKCONDMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCSUMOPERWELLHOOKGASINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPCO2DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION CALCWELLHOOKUPOILMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;

END RPBP_WELL_HOOKUP_THEORETICAL;

/



CREATE or REPLACE PACKAGE BODY RPBP_WELL_HOOKUP_THEORETICAL
IS

   FUNCTION CALCSUMOPERWELLHOOKDILUENTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKDILUENTDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKDILUENTDAY;
   FUNCTION CALCWELLHOOKUPWATDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPWATDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPWATDAY;
   FUNCTION CALCSUMOPERWELLHOOKGASLIFTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKGASLIFTDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKGASLIFTDAY;
   FUNCTION CALCSUMOPERWELLHOOKOILDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKOILDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKOILDAY;
   FUNCTION CALCSUMOPERWELLHOOKOILMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKOILMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKOILMASSDAY;
   FUNCTION CALCSUMOPERWELLHOOKWATINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKWATINJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKWATINJDAY;
   FUNCTION CALCWELLHOOKUPGASDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPGASDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPGASDAY;
   FUNCTION CALCWELLHOOKUPWATINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPWATINJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCWELLHOOKUPWATINJDAY;
   FUNCTION CALCWELLHOOKUPWATMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPWATMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPWATMASSDAY;
   FUNCTION CALCSUMOPERWELLHOOKCO2DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKCO2DAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKCO2DAY;
   FUNCTION CALCSUMOPERWELLHOOKCO2INJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKCO2INJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKCO2INJDAY;
   FUNCTION CALCSUMOPERWELLHOOKCONDDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKCONDDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKCONDDAY;
   FUNCTION CALCSUMOPERWELLHOOKSTEAMINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKSTEAMINJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKSTEAMINJDAY;
   FUNCTION CALCWELLHOOKUPGASINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPGASINJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCWELLHOOKUPGASINJDAY;
   FUNCTION CALCWELLHOOKUPOILDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPOILDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPOILDAY;
   FUNCTION CALCSUMOPERWELLHOOKGASDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKGASDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKGASDAY;
   FUNCTION CALCSUMOPERWELLHOOKGASMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKGASMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKGASMASSDAY;
   FUNCTION CALCWELLHOOKUPDILUENTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPDILUENTDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPDILUENTDAY;
   FUNCTION CALCWELLHOOKUPCO2INJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPCO2INJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCWELLHOOKUPCO2INJDAY;
   FUNCTION CALCWELLHOOKUPCONDDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPCONDDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPCONDDAY;
   FUNCTION CALCWELLHOOKUPCONDMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPCONDMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPCONDMASSDAY;
   FUNCTION CALCWELLHOOKUPGASMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPGASMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPGASMASSDAY;
   FUNCTION GETWELLHOOKPHASEMASSFACTORDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_PHASE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.GETWELLHOOKPHASEMASSFACTORDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_PHASE );
         RETURN ret_value;
   END GETWELLHOOKPHASEMASSFACTORDAY;
   FUNCTION CALCSUMOPERWELLHOOKWATDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKWATDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKWATDAY;
   FUNCTION CALCSUMOPERWELLHOOKWATMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKWATMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKWATMASSDAY;
   FUNCTION CALCWELLHOOKUPGASLIFTDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPGASLIFTDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPGASLIFTDAY;
   FUNCTION CALCWELLHOOKUPSTEAMINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPSTEAMINJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCWELLHOOKUPSTEAMINJDAY;
   FUNCTION GETWELLHOOKPHASEFACTORDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_PHASE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.GETWELLHOOKPHASEFACTORDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_PHASE );
         RETURN ret_value;
   END GETWELLHOOKPHASEFACTORDAY;
   FUNCTION CALCSUMOPERWELLHOOKCONDMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKCONDMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKCONDMASSDAY;
   FUNCTION CALCSUMOPERWELLHOOKGASINJDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCSUMOPERWELLHOOKGASINJDAY      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSUMOPERWELLHOOKGASINJDAY;
   FUNCTION CALCWELLHOOKUPCO2DAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPCO2DAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPCO2DAY;
   FUNCTION CALCWELLHOOKUPOILMASSDAY(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_STREAM_ID IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_HOOKUP_THEORETICAL.CALCWELLHOOKUPOILMASSDAY      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_STREAM_ID );
         RETURN ret_value;
   END CALCWELLHOOKUPOILMASSDAY;

END RPBP_WELL_HOOKUP_THEORETICAL;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_WELL_HOOKUP_THEORETICAL TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.33.35 AM


