
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.19.23 AM


CREATE or REPLACE PACKAGE RPDP_SYSTEM_KEY
IS

   FUNCTION ASSIGNNEXTKEYVALUE(
      P_TABLE_NAME IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION ASSIGNNEXTNUMBER(
      P_TABLE_NAME IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION SHOWLATESTKEYVALUE
      RETURN NUMBER;
   FUNCTION ASSIGNNEXTNUMBERNONAUTONOMOUS(
      P_TABLE_NAME IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION SHOWNEXTKEYVALUE
      RETURN NUMBER;
   FUNCTION ASSIGNNEXTUNIQUENUMBER(
      P_TABLE_NAME IN VARCHAR2,
      P_COLUMN_NAME IN VARCHAR2,
      P_CODE IN VARCHAR2)
      RETURN NUMBER;

END RPDP_SYSTEM_KEY;

/



CREATE or REPLACE PACKAGE BODY RPDP_SYSTEM_KEY
IS

   FUNCTION ASSIGNNEXTKEYVALUE(
      P_TABLE_NAME IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_SYSTEM_KEY.ASSIGNNEXTKEYVALUE      (
         P_TABLE_NAME );
         RETURN ret_value;
   END ASSIGNNEXTKEYVALUE;
   FUNCTION ASSIGNNEXTNUMBER(
      P_TABLE_NAME IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_SYSTEM_KEY.ASSIGNNEXTNUMBER      (
         P_TABLE_NAME );
         RETURN ret_value;
   END ASSIGNNEXTNUMBER;
   FUNCTION SHOWLATESTKEYVALUE
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN

         ret_value := ECDP_SYSTEM_KEY.SHOWLATESTKEYVALUE ;
         RETURN ret_value;
   END SHOWLATESTKEYVALUE;
   FUNCTION ASSIGNNEXTNUMBERNONAUTONOMOUS(
      P_TABLE_NAME IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_SYSTEM_KEY.ASSIGNNEXTNUMBERNONAUTONOMOUS      (
         P_TABLE_NAME );
         RETURN ret_value;
   END ASSIGNNEXTNUMBERNONAUTONOMOUS;
   FUNCTION SHOWNEXTKEYVALUE
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN

         ret_value := ECDP_SYSTEM_KEY.SHOWNEXTKEYVALUE ;
         RETURN ret_value;
   END SHOWNEXTKEYVALUE;
   FUNCTION ASSIGNNEXTUNIQUENUMBER(
      P_TABLE_NAME IN VARCHAR2,
      P_COLUMN_NAME IN VARCHAR2,
      P_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_SYSTEM_KEY.ASSIGNNEXTUNIQUENUMBER      (
         P_TABLE_NAME,
         P_COLUMN_NAME,
         P_CODE );
         RETURN ret_value;
   END ASSIGNNEXTUNIQUENUMBER;

END RPDP_SYSTEM_KEY;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_SYSTEM_KEY TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.19.24 AM


