
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.22.07 AM


CREATE or REPLACE PACKAGE RPDP_PERFORMANCE_LOCK
IS

   FUNCTION CHKIFONLYANLYSRESETINDUPD(
      P_COL_LIST IN ECDP_MONTH_LOCK.COLUMN_LIST)
      RETURN BOOLEAN;

END RPDP_PERFORMANCE_LOCK;

/



CREATE or REPLACE PACKAGE BODY RPDP_PERFORMANCE_LOCK
IS

   FUNCTION CHKIFONLYANLYSRESETINDUPD(
      P_COL_LIST IN ECDP_MONTH_LOCK.COLUMN_LIST)
      RETURN BOOLEAN
   IS
      ret_value    BOOLEAN ;
   BEGIN
      ret_value := ECDP_PERFORMANCE_LOCK.CHKIFONLYANLYSRESETINDUPD      (
         P_COL_LIST );
         RETURN ret_value;
   END CHKIFONLYANLYSRESETINDUPD;

END RPDP_PERFORMANCE_LOCK;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_PERFORMANCE_LOCK TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.22.08 AM


