
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.51.29 AM


CREATE or REPLACE PACKAGE RPDP_CHEMICAL_TANK
IS

   FUNCTION GETCLOSINGUNIT(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2;
   FUNCTION GETPRODUCTID(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2;
   FUNCTION GETCONSUMEDVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION GETCLOSINGVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION GETDAILYCONSUMPTIONRATE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2;
   FUNCTION GETFILLEDVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION GETOPENINGVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION GETPRODUCTCODE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2;
   FUNCTION GETPRODUCTNAME(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2;
   FUNCTION GETREALCLOSINGVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER;
   FUNCTION GETPREVCONNECTIONDATE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE;
   FUNCTION GETPREVMEASDATE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE;
   FUNCTION GETDEFAULTUOM(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2;

END RPDP_CHEMICAL_TANK;

/



CREATE or REPLACE PACKAGE BODY RPDP_CHEMICAL_TANK
IS

   FUNCTION GETCLOSINGUNIT(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETCLOSINGUNIT      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETCLOSINGUNIT;
   FUNCTION GETPRODUCTID(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETPRODUCTID      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETPRODUCTID;
   FUNCTION GETCONSUMEDVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETCONSUMEDVOL      (
         P_TANK_OBJECT_ID,
         P_DAYTIME,
         P_UOM );
         RETURN ret_value;
   END GETCONSUMEDVOL;
   FUNCTION GETCLOSINGVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETCLOSINGVOL      (
         P_TANK_OBJECT_ID,
         P_DAYTIME,
         P_UOM );
         RETURN ret_value;
   END GETCLOSINGVOL;
   FUNCTION GETDAILYCONSUMPTIONRATE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETDAILYCONSUMPTIONRATE      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETDAILYCONSUMPTIONRATE;
   FUNCTION GETFILLEDVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETFILLEDVOL      (
         P_TANK_OBJECT_ID,
         P_DAYTIME,
         P_UOM );
         RETURN ret_value;
   END GETFILLEDVOL;
   FUNCTION GETOPENINGVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETOPENINGVOL      (
         P_TANK_OBJECT_ID,
         P_DAYTIME,
         P_UOM );
         RETURN ret_value;
   END GETOPENINGVOL;
   FUNCTION GETPRODUCTCODE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETPRODUCTCODE      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETPRODUCTCODE;
   FUNCTION GETPRODUCTNAME(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETPRODUCTNAME      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETPRODUCTNAME;
   FUNCTION GETREALCLOSINGVOL(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_UOM IN VARCHAR2 DEFAULT NULL)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETREALCLOSINGVOL      (
         P_TANK_OBJECT_ID,
         P_DAYTIME,
         P_UOM );
         RETURN ret_value;
   END GETREALCLOSINGVOL;
   FUNCTION GETPREVCONNECTIONDATE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETPREVCONNECTIONDATE      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETPREVCONNECTIONDATE;
   FUNCTION GETPREVMEASDATE(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETPREVMEASDATE      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETPREVMEASDATE;
   FUNCTION GETDEFAULTUOM(
      P_TANK_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE DEFAULT NULL)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_CHEMICAL_TANK.GETDEFAULTUOM      (
         P_TANK_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETDEFAULTUOM;

END RPDP_CHEMICAL_TANK;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_CHEMICAL_TANK TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.51.32 AM


