
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.48.58 AM


CREATE or REPLACE PACKAGE RPDP_GROUPS
IS

   FUNCTION FINDPARENTOBJECTID(
      P_FIND_ITEM_TYPE IN VARCHAR2,
      P_GROUP_TYPE IN VARCHAR2,
      P_ITEM_TYPE IN VARCHAR2,
      P_ITEM_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION ISCHILD(
      P_GROUP_TYPE IN VARCHAR2,
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_PARENT_CLASS IN VARCHAR2,
      P_PARENT_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2;

END RPDP_GROUPS;

/



CREATE or REPLACE PACKAGE BODY RPDP_GROUPS
IS

   FUNCTION FINDPARENTOBJECTID(
      P_FIND_ITEM_TYPE IN VARCHAR2,
      P_GROUP_TYPE IN VARCHAR2,
      P_ITEM_TYPE IN VARCHAR2,
      P_ITEM_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_GROUPS.FINDPARENTOBJECTID      (
         P_FIND_ITEM_TYPE,
         P_GROUP_TYPE,
         P_ITEM_TYPE,
         P_ITEM_ID,
         P_DAYTIME );
         RETURN ret_value;
   END FINDPARENTOBJECTID;
   FUNCTION ISCHILD(
      P_GROUP_TYPE IN VARCHAR2,
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_PARENT_CLASS IN VARCHAR2,
      P_PARENT_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_GROUPS.ISCHILD      (
         P_GROUP_TYPE,
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_DAYTIME,
         P_PARENT_CLASS,
         P_PARENT_OBJECT_ID );
         RETURN ret_value;
   END ISCHILD;

END RPDP_GROUPS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_GROUPS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.48.59 AM


