
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.47.06 AM


CREATE or REPLACE PACKAGE RPDP_READONLY
IS

   FUNCTION ISREADONLY(
      P_USER_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;

END RPDP_READONLY;

/



CREATE or REPLACE PACKAGE BODY RPDP_READONLY
IS

   FUNCTION ISREADONLY(
      P_USER_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_READONLY.ISREADONLY      (
         P_USER_NAME,
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END ISREADONLY;

END RPDP_READONLY;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_READONLY TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.47.06 AM


