
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.44.11 AM


CREATE or REPLACE PACKAGE RPDP_TRANSACTION_QTY
IS

   FUNCTION GETFULLCOMPANYFROMCONTRACT(
      P_CONTRACT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION GENTRANSQTY_I(
      P_OBJECT_ID IN VARCHAR2,
      P_TRANSACTION_ID IN VARCHAR2,
      P_USER IN VARCHAR2,
      P_CONTEXT IN OUT T_REVN_DOC_OP_CONTEXT,
      P_FORCE_UPDATE IN BOOLEAN DEFAULT FALSE)
      RETURN BOOLEAN;
   FUNCTION VERIFYVATCODECOUNTRY(
      P_OBJECT_ID IN VARCHAR2,
      P_VAT_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FINANCIAL_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION GETFIELDSHARE(
      P_TRANSACTION_TMPL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_DIST_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETTRANSPRICEOBJECT(
      P_TRAN_PO_ID IN VARCHAR2,
      P_IFAC_PO_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_SILENCE_IND IN VARCHAR2 DEFAULT 'N',
      P_DOC_CONCEPT IN VARCHAR2 DEFAULT NULL)
      RETURN VARCHAR2;
   FUNCTION GETCOMPANYSHARE(
      P_TRANSACTION_TMPL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FIELD_ID IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION SOURCEENTRYNOEXISTS(
      SOURCE_ENTRY_NO IN NUMBER,
      LTAB IN T_TABLE_NUMBER)
      RETURN VARCHAR2;

END RPDP_TRANSACTION_QTY;

/



CREATE or REPLACE PACKAGE BODY RPDP_TRANSACTION_QTY
IS

   FUNCTION GETFULLCOMPANYFROMCONTRACT(
      P_CONTRACT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_TRANSACTION_QTY.GETFULLCOMPANYFROMCONTRACT      (
         P_CONTRACT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETFULLCOMPANYFROMCONTRACT;
   FUNCTION GENTRANSQTY_I(
      P_OBJECT_ID IN VARCHAR2,
      P_TRANSACTION_ID IN VARCHAR2,
      P_USER IN VARCHAR2,
      P_CONTEXT IN OUT T_REVN_DOC_OP_CONTEXT,
      P_FORCE_UPDATE IN BOOLEAN DEFAULT FALSE)
      RETURN BOOLEAN
   IS
      ret_value    BOOLEAN ;
   BEGIN
      ret_value := ECDP_TRANSACTION_QTY.GENTRANSQTY_I      (
         P_OBJECT_ID,
         P_TRANSACTION_ID,
         P_USER,
         P_CONTEXT,
         P_FORCE_UPDATE );
         RETURN ret_value;
   END GENTRANSQTY_I;
   FUNCTION VERIFYVATCODECOUNTRY(
      P_OBJECT_ID IN VARCHAR2,
      P_VAT_CODE IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FINANCIAL_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_TRANSACTION_QTY.VERIFYVATCODECOUNTRY      (
         P_OBJECT_ID,
         P_VAT_CODE,
         P_DAYTIME,
         P_FINANCIAL_CODE );
         RETURN ret_value;
   END VERIFYVATCODECOUNTRY;
   FUNCTION GETFIELDSHARE(
      P_TRANSACTION_TMPL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_DIST_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_TRANSACTION_QTY.GETFIELDSHARE      (
         P_TRANSACTION_TMPL_ID,
         P_DAYTIME,
         P_DIST_ID );
         RETURN ret_value;
   END GETFIELDSHARE;
   FUNCTION GETTRANSPRICEOBJECT(
      P_TRAN_PO_ID IN VARCHAR2,
      P_IFAC_PO_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_SILENCE_IND IN VARCHAR2 DEFAULT 'N',
      P_DOC_CONCEPT IN VARCHAR2 DEFAULT NULL)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_TRANSACTION_QTY.GETTRANSPRICEOBJECT      (
         P_TRAN_PO_ID,
         P_IFAC_PO_ID,
         P_DAYTIME,
         P_SILENCE_IND,
         P_DOC_CONCEPT );
         RETURN ret_value;
   END GETTRANSPRICEOBJECT;
   FUNCTION GETCOMPANYSHARE(
      P_TRANSACTION_TMPL_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FIELD_ID IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_TRANSACTION_QTY.GETCOMPANYSHARE      (
         P_TRANSACTION_TMPL_ID,
         P_DAYTIME,
         P_FIELD_ID,
         P_COMPANY_ID );
         RETURN ret_value;
   END GETCOMPANYSHARE;
   FUNCTION SOURCEENTRYNOEXISTS(
      SOURCE_ENTRY_NO IN NUMBER,
      LTAB IN T_TABLE_NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_TRANSACTION_QTY.SOURCEENTRYNOEXISTS      (
         SOURCE_ENTRY_NO,
         LTAB );
         RETURN ret_value;
   END SOURCEENTRYNOEXISTS;

END RPDP_TRANSACTION_QTY;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_TRANSACTION_QTY TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.44.13 AM


