
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.18.21 AM


CREATE or REPLACE PACKAGE RPDP_WELL_ANALYSIS
IS

   FUNCTION ERRMAX(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION WARNMAX(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION WARNPCT(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_COLUMN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_VALUE IN NUMBER,
      P_OBJECT_ID IN VARCHAR2,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION ERRCOND(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_COND IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION WARNMIN(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION ERRMAND(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_COND IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION ERRMIN(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2;

END RPDP_WELL_ANALYSIS;

/



CREATE or REPLACE PACKAGE BODY RPDP_WELL_ANALYSIS
IS

   FUNCTION ERRMAX(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_ANALYSIS.ERRMAX      (
         P_ANALYSIS_TYPE,
         P_ATTRIBUTE,
         P_VALUE,
         P_ANALYSIS_NO,
         P_VAL_LIMIT );
         RETURN ret_value;
   END ERRMAX;
   FUNCTION WARNMAX(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_ANALYSIS.WARNMAX      (
         P_ANALYSIS_TYPE,
         P_ATTRIBUTE,
         P_VALUE,
         P_ANALYSIS_NO,
         P_VAL_LIMIT );
         RETURN ret_value;
   END WARNMAX;
   FUNCTION WARNPCT(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_COLUMN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_VALUE IN NUMBER,
      P_OBJECT_ID IN VARCHAR2,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_ANALYSIS.WARNPCT      (
         P_ANALYSIS_TYPE,
         P_ATTRIBUTE,
         P_COLUMN,
         P_DAYTIME,
         P_VALUE,
         P_OBJECT_ID,
         P_VAL_LIMIT );
         RETURN ret_value;
   END WARNPCT;
   FUNCTION ERRCOND(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_COND IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_ANALYSIS.ERRCOND      (
         P_ANALYSIS_TYPE,
         P_ATTRIBUTE,
         P_VALUE,
         P_ANALYSIS_NO,
         P_COND );
         RETURN ret_value;
   END ERRCOND;
   FUNCTION WARNMIN(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_ANALYSIS.WARNMIN      (
         P_ANALYSIS_TYPE,
         P_ATTRIBUTE,
         P_VALUE,
         P_ANALYSIS_NO,
         P_VAL_LIMIT );
         RETURN ret_value;
   END WARNMIN;
   FUNCTION ERRMAND(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_COND IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_ANALYSIS.ERRMAND      (
         P_ANALYSIS_TYPE,
         P_ATTRIBUTE,
         P_VALUE,
         P_ANALYSIS_NO,
         P_COND );
         RETURN ret_value;
   END ERRMAND;
   FUNCTION ERRMIN(
      P_ANALYSIS_TYPE IN VARCHAR2,
      P_ATTRIBUTE IN VARCHAR2,
      P_VALUE IN NUMBER,
      P_ANALYSIS_NO IN NUMBER,
      P_VAL_LIMIT IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_ANALYSIS.ERRMIN      (
         P_ANALYSIS_TYPE,
         P_ATTRIBUTE,
         P_VALUE,
         P_ANALYSIS_NO,
         P_VAL_LIMIT );
         RETURN ret_value;
   END ERRMIN;

END RPDP_WELL_ANALYSIS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_WELL_ANALYSIS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.18.23 AM


