
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.52.39 AM


CREATE or REPLACE PACKAGE RPDP_BALANCE
IS

   FUNCTION GETBETWEENNODEDIRAC(
      P_BALANCE_ID IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_NODE_ID IN VARCHAR2,
      P_TO_NODE_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETSTREAMDIR(
      P_BALANCE_ID IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NODE_ID IN VARCHAR2)
      RETURN NUMBER;

END RPDP_BALANCE;

/



CREATE or REPLACE PACKAGE BODY RPDP_BALANCE
IS

   FUNCTION GETBETWEENNODEDIRAC(
      P_BALANCE_ID IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_FROM_NODE_ID IN VARCHAR2,
      P_TO_NODE_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_BALANCE.GETBETWEENNODEDIRAC      (
         P_BALANCE_ID,
         P_OBJECT_ID,
         P_DAYTIME,
         P_FROM_NODE_ID,
         P_TO_NODE_ID );
         RETURN ret_value;
   END GETBETWEENNODEDIRAC;
   FUNCTION GETSTREAMDIR(
      P_BALANCE_ID IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NODE_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECDP_BALANCE.GETSTREAMDIR      (
         P_BALANCE_ID,
         P_OBJECT_ID,
         P_DAYTIME,
         P_NODE_ID );
         RETURN ret_value;
   END GETSTREAMDIR;

END RPDP_BALANCE;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_BALANCE TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.52.40 AM


