
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.46.26 AM


CREATE or REPLACE PACKAGE RPDP_RR_REVN_COMMON
IS

   FUNCTION GETCURRENTREPORTINGPERIOD(
      P_CONTRACT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE;

END RPDP_RR_REVN_COMMON;

/



CREATE or REPLACE PACKAGE BODY RPDP_RR_REVN_COMMON
IS

   FUNCTION GETCURRENTREPORTINGPERIOD(
      P_CONTRACT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := ECDP_RR_REVN_COMMON.GETCURRENTREPORTINGPERIOD      (
         P_CONTRACT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETCURRENTREPORTINGPERIOD;

END RPDP_RR_REVN_COMMON;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_RR_REVN_COMMON TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.46.27 AM


