
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.20.16 AM


CREATE or REPLACE PACKAGE RPDP_STREAM
IS

   FUNCTION GETSTREAMFACILITY(
      P_STREAM_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION FINDEQUIPMENTFORSTREAM(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION GETANALYSISSTREAM(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION GETSTREAMPHASE(
      P_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION GETSTREAMTANK(
      P_STREAM_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION VALIDSTREAMINSET(
      P_OBJECT_ID IN VARCHAR2,
      P_STREAM_SET IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;

END RPDP_STREAM;

/



CREATE or REPLACE PACKAGE BODY RPDP_STREAM
IS

   FUNCTION GETSTREAMFACILITY(
      P_STREAM_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_STREAM.GETSTREAMFACILITY      (
         P_STREAM_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETSTREAMFACILITY;
   FUNCTION FINDEQUIPMENTFORSTREAM(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_CLASS_NAME IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := ECDP_STREAM.FINDEQUIPMENTFORSTREAM      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_CLASS_NAME );
         RETURN ret_value;
   END FINDEQUIPMENTFORSTREAM;
   FUNCTION GETANALYSISSTREAM(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_STREAM.GETANALYSISSTREAM      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETANALYSISSTREAM;
   FUNCTION GETSTREAMPHASE(
      P_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_STREAM.GETSTREAMPHASE      (
         P_OBJECT_ID );
         RETURN ret_value;
   END GETSTREAMPHASE;
   FUNCTION GETSTREAMTANK(
      P_STREAM_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_STREAM.GETSTREAMTANK      (
         P_STREAM_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETSTREAMTANK;
   FUNCTION VALIDSTREAMINSET(
      P_OBJECT_ID IN VARCHAR2,
      P_STREAM_SET IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_STREAM.VALIDSTREAMINSET      (
         P_OBJECT_ID,
         P_STREAM_SET,
         P_DAYTIME );
         RETURN ret_value;
   END VALIDSTREAMINSET;

END RPDP_STREAM;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_STREAM TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.20.18 AM


