
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.23.46 AM


CREATE or REPLACE PACKAGE RPDP_FLOWLINE_ATTRIBUTE
IS

   FUNCTION GAS_METHOD
      RETURN VARCHAR2;
   FUNCTION FLOWLINE_GOR
      RETURN VARCHAR2;
   FUNCTION FLOWLINE_TYPE
      RETURN VARCHAR2;
   FUNCTION CALC_METHOD
      RETURN VARCHAR2;

END RPDP_FLOWLINE_ATTRIBUTE;

/



CREATE or REPLACE PACKAGE BODY RPDP_FLOWLINE_ATTRIBUTE
IS

   FUNCTION GAS_METHOD
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN

         ret_value := ECDP_FLOWLINE_ATTRIBUTE.GAS_METHOD ;
         RETURN ret_value;
   END GAS_METHOD;
   FUNCTION FLOWLINE_GOR
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN

         ret_value := ECDP_FLOWLINE_ATTRIBUTE.FLOWLINE_GOR ;
         RETURN ret_value;
   END FLOWLINE_GOR;
   FUNCTION FLOWLINE_TYPE
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN

         ret_value := ECDP_FLOWLINE_ATTRIBUTE.FLOWLINE_TYPE ;
         RETURN ret_value;
   END FLOWLINE_TYPE;
   FUNCTION CALC_METHOD
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN

         ret_value := ECDP_FLOWLINE_ATTRIBUTE.CALC_METHOD ;
         RETURN ret_value;
   END CALC_METHOD;

END RPDP_FLOWLINE_ATTRIBUTE;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_FLOWLINE_ATTRIBUTE TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.23.48 AM


