
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.18.10 AM


CREATE or REPLACE PACKAGE RPDP_WELL_EQPM_MASTER_EVENT
IS

   FUNCTION GENEVENTID(
      P_EVENT_TYPE IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;

END RPDP_WELL_EQPM_MASTER_EVENT;

/



CREATE or REPLACE PACKAGE BODY RPDP_WELL_EQPM_MASTER_EVENT
IS

   FUNCTION GENEVENTID(
      P_EVENT_TYPE IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_WELL_EQPM_MASTER_EVENT.GENEVENTID      (
         P_EVENT_TYPE,
         P_DAYTIME );
         RETURN ret_value;
   END GENEVENTID;

END RPDP_WELL_EQPM_MASTER_EVENT;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_WELL_EQPM_MASTER_EVENT TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.18.10 AM


