
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.18.12 AM


CREATE or REPLACE PACKAGE RPDP_WELL_CLASS
IS

   FUNCTION PRODUCER
      RETURN VARCHAR2;
   FUNCTION PRODUCER_INJECTOR
      RETURN VARCHAR2;
   FUNCTION INJECTOR
      RETURN VARCHAR2;

END RPDP_WELL_CLASS;

/



CREATE or REPLACE PACKAGE BODY RPDP_WELL_CLASS
IS

   FUNCTION PRODUCER
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN

         ret_value := ECDP_WELL_CLASS.PRODUCER ;
         RETURN ret_value;
   END PRODUCER;
   FUNCTION PRODUCER_INJECTOR
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN

         ret_value := ECDP_WELL_CLASS.PRODUCER_INJECTOR ;
         RETURN ret_value;
   END PRODUCER_INJECTOR;
   FUNCTION INJECTOR
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN

         ret_value := ECDP_WELL_CLASS.INJECTOR ;
         RETURN ret_value;
   END INJECTOR;

END RPDP_WELL_CLASS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_WELL_CLASS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.18.13 AM


