
 -- START PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.26.02 AM


CREATE or REPLACE PACKAGE RPDP_CARGO_PRICE
IS

   FUNCTION GETCARGOPARCELNAME(
      P_PARCEL_KEY IN VARCHAR2)
      RETURN VARCHAR2;

END RPDP_CARGO_PRICE;

/



CREATE or REPLACE PACKAGE BODY RPDP_CARGO_PRICE
IS

   FUNCTION GETCARGOPARCELNAME(
      P_PARCEL_KEY IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_CARGO_PRICE.GETCARGOPARCELNAME      (
         P_PARCEL_KEY );
         RETURN ret_value;
   END GETCARGOPARCELNAME;

END RPDP_CARGO_PRICE;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_CARGO_PRICE TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:11/16/2018 09.26.03 AM


