CREATE OR REPLACE PACKAGE ec_class_rel_presentation IS
------------------------------------------------------------------------------------
-- Package: ec_class_rel_presentation
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION static_presentation_syntax(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.STATIC_PRESENTATION_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION presentation_syntax(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.PRESENTATION_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION db_pres_syntax(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.DB_PRES_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION label(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.LABEL%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_from_class_name VARCHAR2,
         p_to_class_name VARCHAR2,
         p_role_name VARCHAR2) RETURN CLASS_REL_PRESENTATION%ROWTYPE;

END ec_class_rel_presentation;