CREATE OR REPLACE PACKAGE ec_class_attr_presentation IS
------------------------------------------------------------------------------------
-- Package: ec_class_attr_presentation
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION presentation_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.PRESENTATION_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION static_presentation_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.STATIC_PRESENTATION_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION db_pres_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.DB_PRES_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION sort_order(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.SORT_ORDER%TYPE ;
------------------------------------------------------------------------------------
FUNCTION label_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.LABEL_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION label(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.LABEL%TYPE ;
------------------------------------------------------------------------------------
FUNCTION uom_code(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.UOM_CODE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION%ROWTYPE;

END ec_class_attr_presentation;