CREATE OR REPLACE PACKAGE ec_class_attr_editable IS
------------------------------------------------------------------------------------
-- Package: ec_class_attr_editable
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION prev_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION prev_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION next_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION next_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION row_by_rel_operator(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE%ROWTYPE ;
------------------------------------------------------------------------------------
FUNCTION end_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE.END_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION not_editable_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE.NOT_EDITABLE_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_EDITABLE%ROWTYPE;

END ec_class_attr_editable;