CREATE OR REPLACE PACKAGE EcDp_Curve_Parameter IS

/****************************************************************
** Package        :  EcDp_Curve_Parameter, header part
**
** $Revision: 1.7.46.3 $
**
** Purpose        :  Provides declarations for curve parameters (axis)
**
** Documentation  :  www.energy-components.com
**
** Created  : 22.09.2000 Carl-Fredrik Sørensen
**
** Modification history:
**
** Version  Date     	Whom   	Change description:
** -------  ---------- 	-----  	--------------------------------------
**    	    22.08.2002	ATL    	Added function GL_RATE
** 4.3      19.09.2002	FST    	Added GAS_RATE
** 4.4      16.10.2002	EJJ    	Added function DP_TUBING
********
**          20.02.2004  BIH    	Added function NONE
**          18.04.2005  Toha    Added GL_DIFF_PRESS
**	        03.04.2006  EJJ     Added DP_CHOKE, GL_CHOKE, GL_PRESS, WATERCUT_PCT, LIQUID_RATE
**		    02.12.2007  oonnnng	ECPD-6541: Added AVG_FLOW_MASS
**			30.08.2012 musaamah ECPD-20773: Change function from BH_PRESS to DH_PRESS.
**          22.11.2013 kumarsur ECPD-26104: Added PHASE_CURRENT,AC_FREQUENCY,INTAKE_PRESS,DRIVE_FREQUENCY,DRIVE_CURRENT.
**          02.12.2013 makkkkam ECPD-25991: Added MPM_COND_RATE
*****************************************************************/

FUNCTION ANNULUS_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(ANNULUS_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION NONE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(NONE, WNDS, WNPS, RNPS);

--
FUNCTION DH_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DH_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION CHOKE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(CHOKE, WNDS, WNPS, RNPS);

--

FUNCTION CHOKE_NATURAL

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(CHOKE_NATURAL, WNDS, WNPS, RNPS);

--

FUNCTION DRY_OIL_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DRY_OIL_RATE, WNDS, WNPS, RNPS);

--

FUNCTION GAS_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(GAS_RATE, WNDS, WNPS, RNPS);

--

FUNCTION HXT_WH_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(HXT_WH_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION INJ_VOL_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(INJ_VOL_RATE, WNDS, WNPS, RNPS);

--

FUNCTION MPM_WH_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(MPM_WH_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION SS_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(SS_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION TS_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(TS_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION TS_DSC_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(TS_DSC_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION WH_DSC_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(WH_DSC_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION WH_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(WH_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION WH_TEMP

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(WH_TEMP, WNDS, WNPS, RNPS);

--

FUNCTION GL_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(GL_RATE, WNDS, WNPS, RNPS);

--

FUNCTION DP_TUBING

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DP_TUBING, WNDS, WNPS, RNPS);

--

FUNCTION RPM

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(RPM, WNDS, WNPS, RNPS);

--

FUNCTION GL_DIFF_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(GL_DIFF_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION DP_CHOKE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DP_CHOKE, WNDS, WNPS, RNPS);

--

FUNCTION GL_CHOKE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(GL_CHOKE, WNDS, WNPS, RNPS);

--

FUNCTION GL_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(GL_PRESS, WNDS, WNPS, RNPS);

--

FUNCTION WATERCUT_PCT

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(WATERCUT_PCT, WNDS, WNPS, RNPS);

--

FUNCTION LIQUID_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(LIQUID_RATE, WNDS, WNPS, RNPS);

--

FUNCTION AVG_FLOW_MASS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(AVG_FLOW_MASS, WNDS, WNPS, RNPS);

--

FUNCTION DP_FLOWLINE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DP_FLOWLINE, WNDS, WNPS, RNPS);

--

FUNCTION DT_FLOWLINE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DT_FLOWLINE, WNDS, WNPS, RNPS);

--

FUNCTION MPM_OIL_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(MPM_OIL_RATE, WNDS, WNPS, RNPS);

--

FUNCTION MPM_GAS_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(MPM_GAS_RATE, WNDS, WNPS, RNPS);

--

FUNCTION MPM_WATER_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(MPM_WATER_RATE, WNDS, WNPS, RNPS);

--

FUNCTION MPM_COND_RATE

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(MPM_COND_RATE, WNDS, WNPS, RNPS);

--

FUNCTION PHASE_CURRENT

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(PHASE_CURRENT, WNDS, WNPS, RNPS);

--

FUNCTION AC_FREQUENCY

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(AC_FREQUENCY, WNDS, WNPS, RNPS);

--

FUNCTION DRIVE_CURRENT

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DRIVE_CURRENT, WNDS, WNPS, RNPS);
--

FUNCTION DRIVE_FREQUENCY

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(DRIVE_FREQUENCY, WNDS, WNPS, RNPS);
--

FUNCTION INTAKE_PRESS

RETURN VARCHAR2;

PRAGMA RESTRICT_REFERENCES(INTAKE_PRESS, WNDS, WNPS, RNPS);

END EcDp_Curve_Parameter;