CREATE OR REPLACE PACKAGE BODY EcDp_Well_Attribute IS
/****************************************************************
** Package        :  EcDp_Well_Attribute, body part
**
** $Revision: 1.6 $
**
** Purpose        :  Definition of well attributes
**
** Documentation  :  www.energy-components.com
**
** Created  : 17.01.2000  Carl-Fredrik Sørensen
**
** Modification history:
**
** Version  Date        Whom  Change description:
** -------  ------      ----- -----------------------------------
** 1.0      17.01.2000  CFS   Initial version
** 3.0      06.03.2000  DN    New function: GAS_LIFT_METHOD.
** 3.0      08.03.2000  DN    New function: GAS_LIFT_RATE_METHOD.
** 3.1      10.05.2000  CFS   New functions WELL_ALIAS, SEP_TRAIN_HP, SEP_TRAIN_LP, OFFICIAL_NAME.
** 3.2      31.05.2000  CFS   New functions STD_DENSITY_METHOD, STD_GAS_DENSITY, STD_OIL_DENSITY,
**										        STD_WAT_DENSITY.
** 3.3      09.06.2000  CFS   New function: CONVERSION_METHOD
** x.x		12.07.2000	ÅB		New function: POTENTIAL_METHOD
** x.x      26.09.2000  HS    New function: PRESS_VIRGIN , PUMP_VOL
** 4.3      31.01.2001  CFS   New function: CONDUCTIVITY
** 4.4      15.06.2001  UMF   Modified GAS_WAT_EQUIVALENT to GAS_WAT_EQUIV because it
										returned a string larger than 16 characters...
** 4.5      16.10.2001  HVe   Added DEFERMENT_METHOD, ON_STREAM_HRS, WELL_EVENT
** 4.6      09.11.2001  DN    Added APPROACH_METHOD.
** 4.8      2002-05-07  FBa 	Added GAS_LIFT_HRS_METHOD
** 4.9      2002-05-13  FBa	  Added WELL_INTEREST_METHOD
** 4.10		  2002-05-30	FBa	  Added SHRINK_METHOD
** 1.2      2004-05-25  FBa   Removed GAS_LIFT_METHOD, GAS_LIFT_HRS_METHOD, GAS_LIFT_RATE_METHOD
** 1.3      2004-05-25  FBa   Removed DEFERMENT_METHOD, WELL_EVENT
** 1.4      2004-05-25  FBa   Added function CALC_METHOD_MASS
** 1.5      2004-05-27  FBa   Removed STD_DENSITY_METHOD, added STD_OIL_DENSITY_METHOD and STD_GAS_DENSITY_METHOD
** 1.6      2004-05-27  FBa   Re-added STD_DENSITY_METHOD, used by EcBp_Well_Fluid
*****************************************************************/

FUNCTION APPROACH_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'APPROACH_METHOD';

END APPROACH_METHOD;


FUNCTION WATERCUT_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'WATERCUT_METHOD';

END WATERCUT_METHOD;

--

FUNCTION CALC_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'CALC_METHOD';

END CALC_METHOD;

--

FUNCTION CALC_METHOD_MASS
RETURN VARCHAR2 IS

BEGIN

   RETURN 'CALC_METHOD_MASS';

END CALC_METHOD_MASS;

--

FUNCTION ON_STREAM_HRS
RETURN VARCHAR2 IS

BEGIN

   RETURN 'ON_STREAM_HRS';

END ON_STREAM_HRS;

--

FUNCTION CONDUCTIVITY
RETURN VARCHAR2 IS

BEGIN

   RETURN 'CONDUCTIVITY';

END CONDUCTIVITY;

--

FUNCTION CONVERSION_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'CONV_METHOD';

END CONVERSION_METHOD;

--

FUNCTION DIL_INJ_POS
RETURN VARCHAR2 IS

BEGIN

   RETURN 'DIL_INJ_POS';

END DIL_INJ_POS;


FUNCTION GAS_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'GAS_METHOD';

END GAS_METHOD;

--

FUNCTION GAS_WATER_EQUIVALENT
RETURN VARCHAR2 IS

BEGIN

   RETURN 'GAS_WAT_EQUIV';

END GAS_WATER_EQUIVALENT;

--

FUNCTION OFFICIAL_NAME
RETURN VARCHAR2 IS

BEGIN

   RETURN 'OFFICIAL_NAME';

END OFFICIAL_NAME;

--

FUNCTION POTENTIAL_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'POTENTIAL_METHOD';

END POTENTIAL_METHOD;

--

FUNCTION PUMP_VOL
RETURN VARCHAR2 IS

BEGIN

	RETURN 'PUMP_VOL';

END PUMP_VOL;

--


FUNCTION VIRGIN_PRESS
RETURN VARCHAR2 IS

BEGIN

   RETURN 'VIRGIN_PRESS';

END VIRGIN_PRESS;

--

FUNCTION SEP_TRAIN_HP
RETURN VARCHAR2 IS

BEGIN

   RETURN 'SEP_TRAIN_HP';

END SEP_TRAIN_HP;

--

FUNCTION SEP_TRAIN_LP
RETURN VARCHAR2 IS

BEGIN

   RETURN 'SEP_TRAIN_LP';

END SEP_TRAIN_LP;

--

FUNCTION STD_DENSITY_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'STD_DENSITY_METHOD';

END STD_DENSITY_METHOD;

--

FUNCTION STD_OIL_DENSITY_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'STD_OIL_DENSITY_METHOD';

END STD_OIL_DENSITY_METHOD;

--

FUNCTION STD_GAS_DENSITY_METHOD
RETURN VARCHAR2 IS

BEGIN

   RETURN 'STD_GAS_DENSITY_METHOD';

END STD_GAS_DENSITY_METHOD;

--

FUNCTION STD_GAS_DENSITY
RETURN VARCHAR2 IS

BEGIN

   RETURN 'STD_GAS_DENSITY';

END STD_GAS_DENSITY;

--

FUNCTION STD_OIL_DENSITY
RETURN VARCHAR2 IS

BEGIN

   RETURN 'STD_OIL_DENSITY';

END STD_OIL_DENSITY;

--

FUNCTION STD_WAT_DENSITY
RETURN VARCHAR2 IS

BEGIN

   RETURN 'STD_WAT_DENSITY';

END STD_WAT_DENSITY;

--

FUNCTION USE_FLOWLINE_CURVE
RETURN VARCHAR2 IS

BEGIN

   RETURN 'USE_FLWL_CURVE';

END USE_FLOWLINE_CURVE;

--

FUNCTION WELL_ALIAS
RETURN VARCHAR2 IS

BEGIN

   RETURN 'WELL_ALIAS';

END WELL_ALIAS;

--

FUNCTION WELL_CLASS
RETURN VARCHAR2 IS

BEGIN

   RETURN 'WELL_CLASS';

END WELL_CLASS;

--

FUNCTION WELL_GOR
RETURN VARCHAR2 IS

BEGIN

   RETURN 'WELL_GOR';

END WELL_GOR;

--

FUNCTION WELL_INTEREST_METHOD
RETURN VARCHAR2 IS

BEGIN

	RETURN 'WELL_INTRST_METH';

END WELL_INTEREST_METHOD;

--

FUNCTION SHRINK_METHOD
RETURN VARCHAR2 IS

BEGIN

	RETURN 'SHRINK_METHOD';

END SHRINK_METHOD;

--

FUNCTION WELL_TYPE
RETURN VARCHAR2 IS

BEGIN

   RETURN 'WELL_TYPE';

END WELL_TYPE;

--

END;