
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.17.09 AM


CREATE or REPLACE PACKAGE RP_CALC_COMPONENT_COLUMN
IS

   FUNCTION FORMAT_MASK(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION SORT_ORDER(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION CURRENCY_ID(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION LABEL(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION RECORD_STATUS(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         CALC_CONTEXT_ID VARCHAR2 (32) ,
         TEMPLATE_CODE VARCHAR2 (32) ,
         COLUMN_CODE VARCHAR2 (32) ,
         LABEL VARCHAR2 (240) ,
         FORMAT_MASK VARCHAR2 (240) ,
         UOM VARCHAR2 (32) ,
         CURRENCY_ID VARCHAR2 (32) ,
         SORT_ORDER NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION REC_ID(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION UOM(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2;

END RP_CALC_COMPONENT_COLUMN;

/



CREATE or REPLACE PACKAGE BODY RP_CALC_COMPONENT_COLUMN
IS

   FUNCTION FORMAT_MASK(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.FORMAT_MASK      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END FORMAT_MASK;
   FUNCTION SORT_ORDER(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.SORT_ORDER      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END SORT_ORDER;
   FUNCTION APPROVAL_BY(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.APPROVAL_BY      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.APPROVAL_STATE      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION CURRENCY_ID(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.CURRENCY_ID      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END CURRENCY_ID;
   FUNCTION LABEL(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.LABEL      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END LABEL;
   FUNCTION RECORD_STATUS(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.RECORD_STATUS      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.APPROVAL_DATE      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.ROW_BY_PK      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION REC_ID(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.REC_ID      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END REC_ID;
   FUNCTION UOM(
      P_CALC_CONTEXT_ID IN VARCHAR2,
      P_TEMPLATE_CODE IN VARCHAR2,
      P_COLUMN_CODE IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CALC_COMPONENT_COLUMN.UOM      (
         P_CALC_CONTEXT_ID,
         P_TEMPLATE_CODE,
         P_COLUMN_CODE );
         RETURN ret_value;
   END UOM;

END RP_CALC_COMPONENT_COLUMN;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CALC_COMPONENT_COLUMN TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.17.11 AM


