
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.39.06 AM


CREATE or REPLACE PACKAGE RP_CONT_DOCUMENT_COMPANY
IS

   FUNCTION BANK_ACCOUNT_INFO(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION BANK_INFO(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DUE_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION TEXT_3(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION AMOUNT(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION PAYMENT_CALENDAR_COLL_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION PAYMENT_DUE_BASE_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION PAYMENT_SCHEME_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION COMPANY_CATEGORY_CODE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DOCUMENT_NUMBER(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION OBJECT_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION SPLIT_SHARE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION BANK_ACCOUNT_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION COUNTRY_CODE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_3(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION DATE_5(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION PAYMENT_TERM_BASE_CODE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_6(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION COUNTRY_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_2(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION PAYMENT_TERM_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION PAY_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION PAY_TERM_DAYS(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION RECORD_STATUS(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         DOCUMENT_KEY VARCHAR2 (32) ,
         COMPANY_ID VARCHAR2 (32) ,
         BANK_INFO VARCHAR2 (240) ,
         BANK_ACCOUNT_INFO VARCHAR2 (240) ,
         BANK_ACCOUNT_ID VARCHAR2 (32) ,
         AMOUNT NUMBER ,
         DUE_DATE  DATE ,
         VAT_REG_NO VARCHAR2 (240) ,
         COUNTRY_ID VARCHAR2 (32) ,
         COUNTRY_CODE VARCHAR2 (32) ,
         COMPANY_CATEGORY_CODE VARCHAR2 (32) ,
         COMPANY_ROLE VARCHAR2 (32) ,
         DOCUMENT_NUMBER VARCHAR2 (240) ,
         EXVAT_RECEIVER_ID VARCHAR2 (32) ,
         PAYMENT_CALENDAR_COLL_ID VARCHAR2 (32) ,
         PAYMENT_DUE_BASE_DATE  DATE ,
         PAYMENT_SCHEME_ID VARCHAR2 (32) ,
         PAYMENT_TERM_BASE_CODE VARCHAR2 (32) ,
         PAYMENT_TERM_ID VARCHAR2 (32) ,
         PAY_DATE  DATE ,
         PAY_TERM_DAYS NUMBER ,
         SPLIT_SHARE NUMBER ,
         VAT_RECEIVER_ID VARCHAR2 (32) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION VALUE_2(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VAT_RECEIVER_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_4(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION REC_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VAT_REG_NO(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION COMPANY_ROLE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_1(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE;
   FUNCTION EXVAT_RECEIVER_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER;

END RP_CONT_DOCUMENT_COMPANY;

/



CREATE or REPLACE PACKAGE BODY RP_CONT_DOCUMENT_COMPANY
IS

   FUNCTION BANK_ACCOUNT_INFO(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.BANK_ACCOUNT_INFO      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END BANK_ACCOUNT_INFO;
   FUNCTION BANK_INFO(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.BANK_INFO      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END BANK_INFO;
   FUNCTION DUE_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.DUE_DATE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END DUE_DATE;
   FUNCTION TEXT_3(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.TEXT_3      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.TEXT_4      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION AMOUNT(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.AMOUNT      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END AMOUNT;
   FUNCTION APPROVAL_BY(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.APPROVAL_BY      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.APPROVAL_STATE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION PAYMENT_CALENDAR_COLL_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.PAYMENT_CALENDAR_COLL_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END PAYMENT_CALENDAR_COLL_ID;
   FUNCTION PAYMENT_DUE_BASE_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.PAYMENT_DUE_BASE_DATE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END PAYMENT_DUE_BASE_DATE;
   FUNCTION PAYMENT_SCHEME_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.PAYMENT_SCHEME_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END PAYMENT_SCHEME_ID;
   FUNCTION VALUE_5(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_5      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION COMPANY_CATEGORY_CODE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.COMPANY_CATEGORY_CODE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END COMPANY_CATEGORY_CODE;
   FUNCTION DOCUMENT_NUMBER(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.DOCUMENT_NUMBER      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END DOCUMENT_NUMBER;
   FUNCTION OBJECT_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.OBJECT_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END OBJECT_ID;
   FUNCTION SPLIT_SHARE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.SPLIT_SHARE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END SPLIT_SHARE;
   FUNCTION BANK_ACCOUNT_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.BANK_ACCOUNT_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END BANK_ACCOUNT_ID;
   FUNCTION COUNTRY_CODE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.COUNTRY_CODE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END COUNTRY_CODE;
   FUNCTION DATE_3(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.DATE_3      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.DATE_5      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END DATE_5;
   FUNCTION PAYMENT_TERM_BASE_CODE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.PAYMENT_TERM_BASE_CODE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END PAYMENT_TERM_BASE_CODE;
   FUNCTION VALUE_6(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_6      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION COUNTRY_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.COUNTRY_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END COUNTRY_ID;
   FUNCTION DATE_2(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.DATE_2      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END DATE_2;
   FUNCTION PAYMENT_TERM_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.PAYMENT_TERM_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END PAYMENT_TERM_ID;
   FUNCTION PAY_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.PAY_DATE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END PAY_DATE;
   FUNCTION PAY_TERM_DAYS(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.PAY_TERM_DAYS      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END PAY_TERM_DAYS;
   FUNCTION RECORD_STATUS(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.RECORD_STATUS      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_1      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.APPROVAL_DATE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.ROW_BY_PK      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION VALUE_2(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_2      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_3      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_4      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION VAT_RECEIVER_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VAT_RECEIVER_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VAT_RECEIVER_ID;
   FUNCTION DATE_4(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.DATE_4      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END DATE_4;
   FUNCTION REC_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.REC_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.TEXT_1      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.TEXT_2      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_7(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_7      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_9      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION VAT_REG_NO(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VAT_REG_NO      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VAT_REG_NO;
   FUNCTION COMPANY_ROLE(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.COMPANY_ROLE      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END COMPANY_ROLE;
   FUNCTION DATE_1(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.DATE_1      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END DATE_1;
   FUNCTION EXVAT_RECEIVER_ID(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.EXVAT_RECEIVER_ID      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END EXVAT_RECEIVER_ID;
   FUNCTION VALUE_10(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_10      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_DOCUMENT_KEY IN VARCHAR2,
      P_COMPANY_ID IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_DOCUMENT_COMPANY.VALUE_8      (
         P_DOCUMENT_KEY,
         P_COMPANY_ID );
         RETURN ret_value;
   END VALUE_8;

END RP_CONT_DOCUMENT_COMPANY;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CONT_DOCUMENT_COMPANY TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.39.15 AM


