
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.07.36 AM


CREATE or REPLACE PACKAGE RP_CARGO_DOCUMENT
IS

   FUNCTION DOC_NAME(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION PARCEL_NO(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION COMMENTS(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION VALUE_6(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION CARGO_NO(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION FORMAT(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION PREV_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN DATE;
   FUNCTION DOCUMENT(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN BLOB;
      TYPE REC_ROW_BY_PK IS RECORD (
         CARGO_DOCUMENT_NO NUMBER ,
         DAYTIME  DATE ,
         DOC_NAME VARCHAR2 (32) ,
         CARGO_NO NUMBER ,
         PARCEL_NO NUMBER ,
         FORMAT VARCHAR2 (32) ,
         TYPE VARCHAR2 (32) ,
         GZIP_IND VARCHAR2 (1) ,
         DOCUMENT  BLOB ,
         COMMENTS VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         TEXT_1 VARCHAR2 (16) ,
         TEXT_2 VARCHAR2 (32) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN REC_ROW_BY_PK;
   FUNCTION TYPE(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_2(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN DATE;
   FUNCTION GZIP_IND(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER;

END RP_CARGO_DOCUMENT;

/



CREATE or REPLACE PACKAGE BODY RP_CARGO_DOCUMENT
IS

   FUNCTION DOC_NAME(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.DOC_NAME      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END DOC_NAME;
   FUNCTION PARCEL_NO(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.PARCEL_NO      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END PARCEL_NO;
   FUNCTION TEXT_3(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.TEXT_3      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION TEXT_4(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.TEXT_4      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION APPROVAL_BY(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.APPROVAL_BY      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.APPROVAL_STATE      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION VALUE_5(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_5      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION NEXT_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.NEXT_DAYTIME      (
         P_CARGO_DOCUMENT_NO,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.PREV_EQUAL_DAYTIME      (
         P_CARGO_DOCUMENT_NO,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION COMMENTS(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.COMMENTS      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.NEXT_EQUAL_DAYTIME      (
         P_CARGO_DOCUMENT_NO,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION VALUE_6(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_6      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION CARGO_NO(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.CARGO_NO      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END CARGO_NO;
   FUNCTION FORMAT(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.FORMAT      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END FORMAT;
   FUNCTION PREV_DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.PREV_DAYTIME      (
         P_CARGO_DOCUMENT_NO,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.RECORD_STATUS      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_1      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.APPROVAL_DATE      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION DOCUMENT(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN BLOB
   IS
      ret_value    BLOB ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.DOCUMENT      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END DOCUMENT;
   FUNCTION ROW_BY_PK(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.ROW_BY_PK      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION TYPE(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.TYPE      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END TYPE;
   FUNCTION VALUE_2(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_2      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_3      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_4      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION REC_ID(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.REC_ID      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TEXT_1(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (16) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.TEXT_1      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_2(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.TEXT_2      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION VALUE_7(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_7      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_9      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION DAYTIME(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.DAYTIME      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END DAYTIME;
   FUNCTION GZIP_IND(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.GZIP_IND      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END GZIP_IND;
   FUNCTION VALUE_10(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_10      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_CARGO_DOCUMENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CARGO_DOCUMENT.VALUE_8      (
         P_CARGO_DOCUMENT_NO );
         RETURN ret_value;
   END VALUE_8;

END RP_CARGO_DOCUMENT;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CARGO_DOCUMENT TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.07.43 AM


