
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.31.53 AM


CREATE or REPLACE PACKAGE RP_CT_PORT_RES_USAGE
IS

   FUNCTION DURATION_CODE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_BY(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION DURATION(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION COMMENTS(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PORT_RESOURCE_ID(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION PORT_RESOURCE_TYPE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION PREV_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN DATE;
   FUNCTION PORT_RESOURCE_NAME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
      TYPE REC_ROW_BY_PK IS RECORD (
         CARGO_NO NUMBER ,
         PORT_RESOURCE_NAME VARCHAR2 (2000) ,
         PORT_RESOURCE_TYPE VARCHAR2 (24) ,
         PORT_RESOURCE_ID VARCHAR2 (32) ,
         TIMELINE_CODE VARCHAR2 (32) ,
         DAYTIME  DATE ,
         DURATION_CODE VARCHAR2 (32) ,
         DURATION NUMBER ,
         COMMENTS VARCHAR2 (2000) ,
         SORT_ORDER NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (240) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN REC_ROW_BY_PK;
   FUNCTION REC_ID(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION TIMELINE_CODE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2;
   FUNCTION DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN DATE;

END RP_CT_PORT_RES_USAGE;

/



CREATE or REPLACE PACKAGE BODY RP_CT_PORT_RES_USAGE
IS

   FUNCTION DURATION_CODE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.DURATION_CODE      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END DURATION_CODE;
   FUNCTION APPROVAL_BY(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.APPROVAL_BY      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.APPROVAL_STATE      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION DURATION(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.DURATION      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END DURATION;
   FUNCTION NEXT_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.NEXT_DAYTIME      (
         P_CARGO_NO,
         P_SORT_ORDER,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.PREV_EQUAL_DAYTIME      (
         P_CARGO_NO,
         P_SORT_ORDER,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION COMMENTS(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.COMMENTS      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.NEXT_EQUAL_DAYTIME      (
         P_CARGO_NO,
         P_SORT_ORDER,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION PORT_RESOURCE_ID(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.PORT_RESOURCE_ID      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END PORT_RESOURCE_ID;
   FUNCTION PORT_RESOURCE_TYPE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (24) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.PORT_RESOURCE_TYPE      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END PORT_RESOURCE_TYPE;
   FUNCTION PREV_DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.PREV_DAYTIME      (
         P_CARGO_NO,
         P_SORT_ORDER,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.RECORD_STATUS      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.APPROVAL_DATE      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION PORT_RESOURCE_NAME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.PORT_RESOURCE_NAME      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END PORT_RESOURCE_NAME;
   FUNCTION ROW_BY_PK(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.ROW_BY_PK      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION REC_ID(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.REC_ID      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION TIMELINE_CODE(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.TIMELINE_CODE      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END TIMELINE_CODE;
   FUNCTION DAYTIME(
      P_CARGO_NO IN NUMBER,
      P_SORT_ORDER IN NUMBER)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CT_PORT_RES_USAGE.DAYTIME      (
         P_CARGO_NO,
         P_SORT_ORDER );
         RETURN ret_value;
   END DAYTIME;

END RP_CT_PORT_RES_USAGE;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CT_PORT_RES_USAGE TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.31.57 AM


