
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.59.21 AM


CREATE or REPLACE PACKAGE RP_CNTRACC_PER_DIM3_ALLOC
IS

   FUNCTION MATH_X1_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VOL_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION X3_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION AMOUNT(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION MATH_VALUE_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_4(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_8(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION VALUE_5(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_6(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION TEXT_7(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_8(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION X1_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION COUNT_ROWS(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER;
   FUNCTION DATE_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION ENERGY_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_5(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_7(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_9(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION TEXT_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_14(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_6(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_9(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_6(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_CALC_RUN_NO(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VOL_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION PREV_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION CALC_RUN_NO(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MASS_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MATH_MASS_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_X2_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
      TYPE REC_ROW_BY_PK IS RECORD (
         CLASS_NAME VARCHAR2 (32) ,
         OBJECT_ID VARCHAR2 (32) ,
         ACCOUNT_CODE VARCHAR2 (32) ,
         DIM1_KEY VARCHAR2 (32) ,
         DIM2_KEY VARCHAR2 (32) ,
         DIM3_KEY VARCHAR2 (32) ,
         TIME_SPAN VARCHAR2 (16) ,
         DAYTIME  DATE ,
         VOL_QTY NUMBER ,
         MASS_QTY NUMBER ,
         ENERGY_QTY NUMBER ,
         X1_QTY NUMBER ,
         X2_QTY NUMBER ,
         X3_QTY NUMBER ,
         TEXT_1 VARCHAR2 (240) ,
         TEXT_2 VARCHAR2 (240) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (240) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         TEXT_9 VARCHAR2 (240) ,
         TEXT_10 VARCHAR2 (240) ,
         TEXT_11 VARCHAR2 (2000) ,
         TEXT_12 VARCHAR2 (2000) ,
         TEXT_13 VARCHAR2 (2000) ,
         TEXT_14 VARCHAR2 (2000) ,
         TEXT_15 VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         AMOUNT NUMBER ,
         CALC_RUN_NO NUMBER  );
   FUNCTION ROW_BY_PK(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         CLASS_NAME VARCHAR2 (32) ,
         OBJECT_ID VARCHAR2 (32) ,
         ACCOUNT_CODE VARCHAR2 (32) ,
         DIM1_KEY VARCHAR2 (32) ,
         DIM2_KEY VARCHAR2 (32) ,
         DIM3_KEY VARCHAR2 (32) ,
         TIME_SPAN VARCHAR2 (16) ,
         DAYTIME  DATE ,
         VOL_QTY NUMBER ,
         MASS_QTY NUMBER ,
         ENERGY_QTY NUMBER ,
         X1_QTY NUMBER ,
         X2_QTY NUMBER ,
         X3_QTY NUMBER ,
         TEXT_1 VARCHAR2 (240) ,
         TEXT_2 VARCHAR2 (240) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (240) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         TEXT_9 VARCHAR2 (240) ,
         TEXT_10 VARCHAR2 (240) ,
         TEXT_11 VARCHAR2 (2000) ,
         TEXT_12 VARCHAR2 (2000) ,
         TEXT_13 VARCHAR2 (2000) ,
         TEXT_14 VARCHAR2 (2000) ,
         TEXT_15 VARCHAR2 (2000) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         VALUE_6 NUMBER ,
         VALUE_7 NUMBER ,
         VALUE_8 NUMBER ,
         VALUE_9 NUMBER ,
         VALUE_10 NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_STATE VARCHAR2 (1) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         REC_ID VARCHAR2 (32) ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         AMOUNT NUMBER ,
         CALC_RUN_NO NUMBER  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_13(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_5(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION MATH_ENERGY_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_X3_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_7(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_9(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
   FUNCTION MATH_AMOUNT(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION MATH_VALUE_10(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION TEXT_10(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_11(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_12(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION TEXT_15(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION VALUE_10(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION VALUE_8(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION X2_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;

END RP_CNTRACC_PER_DIM3_ALLOC;

/



CREATE or REPLACE PACKAGE BODY RP_CNTRACC_PER_DIM3_ALLOC
IS

   FUNCTION MATH_X1_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_X1_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_X1_QTY;
   FUNCTION TEXT_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_3      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION VOL_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VOL_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VOL_QTY;
   FUNCTION X3_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.X3_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END X3_QTY;
   FUNCTION AMOUNT(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.AMOUNT      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END AMOUNT;
   FUNCTION APPROVAL_BY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.APPROVAL_BY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.APPROVAL_STATE      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION MATH_VALUE_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_3      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_3;
   FUNCTION MATH_VALUE_4(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_4      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_4;
   FUNCTION MATH_VALUE_8(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_8      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_8;
   FUNCTION VALUE_5(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_5      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION MATH_VALUE_6(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_6      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_6;
   FUNCTION NEXT_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.NEXT_DAYTIME      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.PREV_EQUAL_DAYTIME      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION TEXT_7(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_7      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_7;
   FUNCTION TEXT_8(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_8      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_8;
   FUNCTION X1_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.X1_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END X1_QTY;
   FUNCTION COUNT_ROWS(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.COUNT_ROWS      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY );
         RETURN ret_value;
   END COUNT_ROWS;
   FUNCTION DATE_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.DATE_3      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_3;
   FUNCTION ENERGY_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.ENERGY_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ENERGY_QTY;
   FUNCTION MATH_VALUE_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_1      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_1;
   FUNCTION MATH_VALUE_5(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_5      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_5;
   FUNCTION MATH_VALUE_7(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_7      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_7;
   FUNCTION MATH_VALUE_9(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_9      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_9;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.NEXT_EQUAL_DAYTIME      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION TEXT_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_1      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_14(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_14      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_14;
   FUNCTION TEXT_6(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_6      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_6;
   FUNCTION TEXT_9(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_9      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_9;
   FUNCTION VALUE_6(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_6      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_6;
   FUNCTION DATE_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.DATE_2      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_2;
   FUNCTION MATH_CALC_RUN_NO(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_CALC_RUN_NO      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_CALC_RUN_NO;
   FUNCTION MATH_VOL_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VOL_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VOL_QTY;
   FUNCTION PREV_DAYTIME(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.PREV_DAYTIME      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.RECORD_STATUS      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION VALUE_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_1      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.APPROVAL_DATE      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION CALC_RUN_NO(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.CALC_RUN_NO      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END CALC_RUN_NO;
   FUNCTION MASS_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MASS_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END MASS_QTY;
   FUNCTION MATH_MASS_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_MASS_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_MASS_QTY;
   FUNCTION MATH_VALUE_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_2      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_2;
   FUNCTION MATH_X2_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_X2_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_X2_QTY;
   FUNCTION ROW_BY_PK(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.ROW_BY_PK      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.ROW_BY_REL_OPERATOR      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION TEXT_13(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_13      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_13;
   FUNCTION TEXT_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_2      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION TEXT_4(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_4      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION TEXT_5(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_5      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION VALUE_2(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_2      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_3      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_4      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION MATH_ENERGY_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_ENERGY_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_ENERGY_QTY;
   FUNCTION MATH_X3_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_X3_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_X3_QTY;
   FUNCTION REC_ID(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.REC_ID      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;
   FUNCTION VALUE_7(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_7      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_7;
   FUNCTION VALUE_9(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_9      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_9;
   FUNCTION DATE_1(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.DATE_1      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END DATE_1;
   FUNCTION MATH_AMOUNT(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_AMOUNT      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_AMOUNT;
   FUNCTION MATH_VALUE_10(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.MATH_VALUE_10      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_VALUE_10;
   FUNCTION TEXT_10(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_10      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_10;
   FUNCTION TEXT_11(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_11      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_11;
   FUNCTION TEXT_12(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_12      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_12;
   FUNCTION TEXT_15(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.TEXT_15      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END TEXT_15;
   FUNCTION VALUE_10(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_10      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_10;
   FUNCTION VALUE_8(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.VALUE_8      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END VALUE_8;
   FUNCTION X2_QTY(
      P_CLASS_NAME IN VARCHAR2,
      P_OBJECT_ID IN VARCHAR2,
      P_ACCOUNT_CODE IN VARCHAR2,
      P_DIM1_KEY IN VARCHAR2,
      P_DIM2_KEY IN VARCHAR2,
      P_DIM3_KEY IN VARCHAR2,
      P_TIME_SPAN IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CNTRACC_PER_DIM3_ALLOC.X2_QTY      (
         P_CLASS_NAME,
         P_OBJECT_ID,
         P_ACCOUNT_CODE,
         P_DIM1_KEY,
         P_DIM2_KEY,
         P_DIM3_KEY,
         P_TIME_SPAN,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END X2_QTY;

END RP_CNTRACC_PER_DIM3_ALLOC;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CNTRACC_PER_DIM3_ALLOC TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.59.35 AM


