
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.37.41 AM


CREATE or REPLACE PACKAGE RP_CONT_JOURNAL_SUMMARY
IS

   FUNCTION ACTUAL_QTY_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION AMEND_QTY_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION FIN_COST_CENTER_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION FORECAST_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION FORECAST_QTY_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION AMOUNT_ADJUSTMENT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION CURRENCY_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATASET(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION FIN_WBS_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION FIN_ACCOUNT_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION FIN_REVENUE_ORDER_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PRE_UPDATE_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION QTY_ADJUSTMENT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION UPDATE_CLASS_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE;
   FUNCTION LABEL(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION LIST_ITEM_KEY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION REF_OBJECT_ID_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_9(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION COMPANY_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION REF_OBJECT_ID_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE;
   FUNCTION REF_OBJECT_ID_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         COMPANY_ID VARCHAR2 (32) ,
         FISCAL_YEAR VARCHAR2 (4) ,
         DAYTIME  DATE ,
         PERIOD  DATE ,
         DOCUMENT_KEY VARCHAR2 (32) ,
         LIST_ITEM_KEY VARCHAR2 (32) ,
         SUMMARY_SETUP_ID VARCHAR2 (32) ,
         DATASET VARCHAR2 (32) ,
         FIN_ACCOUNT_ID VARCHAR2 (32) ,
         FIN_COST_CENTER_ID VARCHAR2 (32) ,
         FIN_COST_OBJECT_ID VARCHAR2 (32) ,
         FIN_REVENUE_ORDER_ID VARCHAR2 (32) ,
         FIN_WBS_ID VARCHAR2 (32) ,
         DEBIT_CREDIT VARCHAR2 (1) ,
         ACTUAL_AMOUNT NUMBER ,
         AMOUNT_ADJUSTMENT NUMBER ,
         ACTUAL_QTY_1 NUMBER ,
         QTY_ADJUSTMENT NUMBER ,
         FORECAST_AMOUNT NUMBER ,
         FORECAST_QTY_1 NUMBER ,
         AMEND_AMOUNT NUMBER ,
         AMEND_QTY_1 NUMBER ,
         UOM1_CODE VARCHAR2 (32) ,
         CURRENCY_ID VARCHAR2 (32) ,
         TAG VARCHAR2 (240) ,
         LABEL VARCHAR2 (240) ,
         COMMENTS VARCHAR2 (2000) ,
         TEXT_1 VARCHAR2 (240) ,
         TEXT_2 VARCHAR2 (240) ,
         TEXT_3 VARCHAR2 (240) ,
         TEXT_4 VARCHAR2 (240) ,
         TEXT_5 VARCHAR2 (240) ,
         TEXT_6 VARCHAR2 (240) ,
         TEXT_7 VARCHAR2 (240) ,
         TEXT_8 VARCHAR2 (240) ,
         TEXT_9 VARCHAR2 (240) ,
         TEXT_10 VARCHAR2 (240) ,
         VALUE_1 NUMBER ,
         VALUE_2 NUMBER ,
         VALUE_3 NUMBER ,
         VALUE_4 NUMBER ,
         VALUE_5 NUMBER ,
         DATE_1  DATE ,
         DATE_2  DATE ,
         DATE_3  DATE ,
         DATE_4  DATE ,
         DATE_5  DATE ,
         REF_OBJECT_ID_1 VARCHAR2 (32) ,
         REF_OBJECT_ID_2 VARCHAR2 (32) ,
         REF_OBJECT_ID_3 VARCHAR2 (32) ,
         REF_OBJECT_ID_4 VARCHAR2 (32) ,
         REF_OBJECT_ID_5 VARCHAR2 (32) ,
         UPDATE_CLASS_AMOUNT VARCHAR2 (32) ,
         UPDATE_REF_ID_AMOUNT VARCHAR2 (100) ,
         UPDATE_CLASS_QTY VARCHAR2 (32) ,
         UPDATE_REF_ID_QTY VARCHAR2 (100) ,
         PRE_UPDATE_AMOUNT NUMBER ,
         PRE_UPDATE_QTY1 NUMBER ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION UPDATE_REF_ID_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE;
   FUNCTION DEBIT_CREDIT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION FIN_COST_OBJECT_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION FISCAL_YEAR(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION PRE_UPDATE_QTY1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION UPDATE_CLASS_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION ACTUAL_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION AMEND_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE;
   FUNCTION DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE;
   FUNCTION TEXT_10(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION UOM1_CODE(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION UPDATE_REF_ID_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2;

END RP_CONT_JOURNAL_SUMMARY;

/



CREATE or REPLACE PACKAGE BODY RP_CONT_JOURNAL_SUMMARY
IS

   FUNCTION ACTUAL_QTY_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.ACTUAL_QTY_1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END ACTUAL_QTY_1;
   FUNCTION AMEND_QTY_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.AMEND_QTY_1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END AMEND_QTY_1;
   FUNCTION FIN_COST_CENTER_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FIN_COST_CENTER_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FIN_COST_CENTER_ID;
   FUNCTION FORECAST_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FORECAST_AMOUNT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FORECAST_AMOUNT;
   FUNCTION FORECAST_QTY_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FORECAST_QTY_1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FORECAST_QTY_1;
   FUNCTION TEXT_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_3      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_3;
   FUNCTION AMOUNT_ADJUSTMENT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.AMOUNT_ADJUSTMENT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END AMOUNT_ADJUSTMENT;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.APPROVAL_BY      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION CURRENCY_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.CURRENCY_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END CURRENCY_ID;
   FUNCTION DATASET(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DATASET      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DATASET;
   FUNCTION FIN_WBS_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FIN_WBS_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FIN_WBS_ID;
   FUNCTION REF_OBJECT_ID_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.REF_OBJECT_ID_4      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END REF_OBJECT_ID_4;
   FUNCTION VALUE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.VALUE_5      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END VALUE_5;
   FUNCTION FIN_ACCOUNT_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FIN_ACCOUNT_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FIN_ACCOUNT_ID;
   FUNCTION FIN_REVENUE_ORDER_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FIN_REVENUE_ORDER_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FIN_REVENUE_ORDER_ID;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.NEXT_DAYTIME      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.PREV_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION PRE_UPDATE_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.PRE_UPDATE_AMOUNT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END PRE_UPDATE_AMOUNT;
   FUNCTION QTY_ADJUSTMENT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.QTY_ADJUSTMENT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END QTY_ADJUSTMENT;
   FUNCTION TEXT_7(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_7      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_7;
   FUNCTION TEXT_8(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_8      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_8;
   FUNCTION UPDATE_CLASS_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.UPDATE_CLASS_AMOUNT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END UPDATE_CLASS_AMOUNT;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.COMMENTS      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION DATE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DATE_3      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DATE_3;
   FUNCTION DATE_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DATE_5      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DATE_5;
   FUNCTION LABEL(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.LABEL      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END LABEL;
   FUNCTION LIST_ITEM_KEY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.LIST_ITEM_KEY      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END LIST_ITEM_KEY;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.NEXT_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION REF_OBJECT_ID_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.REF_OBJECT_ID_2      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END REF_OBJECT_ID_2;
   FUNCTION REF_OBJECT_ID_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.REF_OBJECT_ID_3      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END REF_OBJECT_ID_3;
   FUNCTION TEXT_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_1;
   FUNCTION TEXT_6(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_6      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_6;
   FUNCTION TEXT_9(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_9      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_9;
   FUNCTION COMPANY_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.COMPANY_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END COMPANY_ID;
   FUNCTION DATE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DATE_2      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DATE_2;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.PREV_DAYTIME      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.RECORD_STATUS      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION REF_OBJECT_ID_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.REF_OBJECT_ID_5      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END REF_OBJECT_ID_5;
   FUNCTION VALUE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.VALUE_1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END VALUE_1;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION REF_OBJECT_ID_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.REF_OBJECT_ID_1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END REF_OBJECT_ID_1;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.ROW_BY_PK      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION TEXT_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_2      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_2;
   FUNCTION TEXT_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_4      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_4;
   FUNCTION TEXT_5(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_5      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_5;
   FUNCTION UPDATE_REF_ID_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (100) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.UPDATE_REF_ID_QTY      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END UPDATE_REF_ID_QTY;
   FUNCTION VALUE_2(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.VALUE_2      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END VALUE_2;
   FUNCTION VALUE_3(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.VALUE_3      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END VALUE_3;
   FUNCTION VALUE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.VALUE_4      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END VALUE_4;
   FUNCTION DATE_4(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DATE_4      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DATE_4;
   FUNCTION DEBIT_CREDIT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DEBIT_CREDIT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DEBIT_CREDIT;
   FUNCTION FIN_COST_OBJECT_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FIN_COST_OBJECT_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FIN_COST_OBJECT_ID;
   FUNCTION FISCAL_YEAR(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (4) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.FISCAL_YEAR      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END FISCAL_YEAR;
   FUNCTION PRE_UPDATE_QTY1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.PRE_UPDATE_QTY1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END PRE_UPDATE_QTY1;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.REC_ID      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END REC_ID;
   FUNCTION UPDATE_CLASS_QTY(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.UPDATE_CLASS_QTY      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END UPDATE_CLASS_QTY;
   FUNCTION ACTUAL_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.ACTUAL_AMOUNT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END ACTUAL_AMOUNT;
   FUNCTION AMEND_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.AMEND_AMOUNT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END AMEND_AMOUNT;
   FUNCTION DATE_1(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DATE_1      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DATE_1;
   FUNCTION DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.DAYTIME      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END DAYTIME;
   FUNCTION TEXT_10(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (240) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.TEXT_10      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END TEXT_10;
   FUNCTION UOM1_CODE(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.UOM1_CODE      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END UOM1_CODE;
   FUNCTION UPDATE_REF_ID_AMOUNT(
      P_OBJECT_ID IN VARCHAR2,
      P_PERIOD IN DATE,
      P_DOCUMENT_KEY IN VARCHAR2,
      P_SUMMARY_SETUP_ID IN VARCHAR2,
      P_TAG IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (100) ;
   BEGIN
      ret_value := EC_CONT_JOURNAL_SUMMARY.UPDATE_REF_ID_AMOUNT      (
         P_OBJECT_ID,
         P_PERIOD,
         P_DOCUMENT_KEY,
         P_SUMMARY_SETUP_ID,
         P_TAG );
         RETURN ret_value;
   END UPDATE_REF_ID_AMOUNT;

END RP_CONT_JOURNAL_SUMMARY;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_CONT_JOURNAL_SUMMARY TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 10.37.54 AM


