
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 09.50.28 AM


CREATE or REPLACE PACKAGE RP_FCST_SCENARIO_GRAPHS
IS

   FUNCTION APPROVAL_BY(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION RECORD_STATUS(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         SCENARIO_ID VARCHAR2 (32) ,
         FORECAST_ID VARCHAR2 (32) ,
         ASSET_OBJECT_ID VARCHAR2 (32) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN REC_ROW_BY_PK;
   FUNCTION REC_ID(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2;

END RP_FCST_SCENARIO_GRAPHS;

/



CREATE or REPLACE PACKAGE BODY RP_FCST_SCENARIO_GRAPHS
IS

   FUNCTION APPROVAL_BY(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_FCST_SCENARIO_GRAPHS.APPROVAL_BY      (
         P_FORECAST_ID,
         P_SCENARIO_ID,
         P_ASSET_OBJECT_ID );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_FCST_SCENARIO_GRAPHS.APPROVAL_STATE      (
         P_FORECAST_ID,
         P_SCENARIO_ID,
         P_ASSET_OBJECT_ID );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION RECORD_STATUS(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_FCST_SCENARIO_GRAPHS.RECORD_STATUS      (
         P_FORECAST_ID,
         P_SCENARIO_ID,
         P_ASSET_OBJECT_ID );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_FCST_SCENARIO_GRAPHS.APPROVAL_DATE      (
         P_FORECAST_ID,
         P_SCENARIO_ID,
         P_ASSET_OBJECT_ID );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_FCST_SCENARIO_GRAPHS.ROW_BY_PK      (
         P_FORECAST_ID,
         P_SCENARIO_ID,
         P_ASSET_OBJECT_ID );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION REC_ID(
      P_FORECAST_ID IN VARCHAR2,
      P_SCENARIO_ID IN VARCHAR2,
      P_ASSET_OBJECT_ID IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_FCST_SCENARIO_GRAPHS.REC_ID      (
         P_FORECAST_ID,
         P_SCENARIO_ID,
         P_ASSET_OBJECT_ID );
         RETURN ret_value;
   END REC_ID;

END RP_FCST_SCENARIO_GRAPHS;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_FCST_SCENARIO_GRAPHS TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 09.50.30 AM


