
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 06.36.06 AM


CREATE or REPLACE PACKAGE RP_STRM_ORF_COMPONENT
IS

   FUNCTION ORF_FACTOR(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION MATH_ORF_FACTOR(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION COUNT_ROWS(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE;
      TYPE REC_ROW_BY_PK IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         ORF_TYPE VARCHAR2 (16) ,
         COMPONENT_NO VARCHAR2 (16) ,
         DAYTIME  DATE ,
         ORF_FACTOR NUMBER ,
         COMMENTS VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK;
      TYPE REC_ROW_BY_REL_OPERATOR IS RECORD (
         OBJECT_ID VARCHAR2 (32) ,
         ORF_TYPE VARCHAR2 (16) ,
         COMPONENT_NO VARCHAR2 (16) ,
         DAYTIME  DATE ,
         ORF_FACTOR NUMBER ,
         COMMENTS VARCHAR2 (2000) ,
         RECORD_STATUS VARCHAR2 (1) ,
         CREATED_BY VARCHAR2 (30) ,
         CREATED_DATE  DATE ,
         LAST_UPDATED_BY VARCHAR2 (30) ,
         LAST_UPDATED_DATE  DATE ,
         REV_NO NUMBER ,
         REV_TEXT VARCHAR2 (2000) ,
         APPROVAL_BY VARCHAR2 (30) ,
         APPROVAL_DATE  DATE ,
         APPROVAL_STATE VARCHAR2 (1) ,
         REC_ID VARCHAR2 (32)  );
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2;

END RP_STRM_ORF_COMPONENT;

/



CREATE or REPLACE PACKAGE BODY RP_STRM_ORF_COMPONENT
IS

   FUNCTION ORF_FACTOR(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.ORF_FACTOR      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ORF_FACTOR;
   FUNCTION APPROVAL_BY(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (30) ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.APPROVAL_BY      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_BY;
   FUNCTION APPROVAL_STATE(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.APPROVAL_STATE      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_STATE;
   FUNCTION MATH_ORF_FACTOR(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE,
      P_METHOD IN VARCHAR2 DEFAULT 'SUM')
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.MATH_ORF_FACTOR      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_FROM_DAY,
         P_TO_DAY,
         P_METHOD );
         RETURN ret_value;
   END MATH_ORF_FACTOR;
   FUNCTION NEXT_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.NEXT_DAYTIME      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_DAYTIME;
   FUNCTION PREV_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.PREV_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_EQUAL_DAYTIME;
   FUNCTION COMMENTS(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (2000) ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.COMMENTS      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END COMMENTS;
   FUNCTION COUNT_ROWS(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_FROM_DAY IN DATE,
      P_TO_DAY IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.COUNT_ROWS      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_FROM_DAY,
         P_TO_DAY );
         RETURN ret_value;
   END COUNT_ROWS;
   FUNCTION NEXT_EQUAL_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.NEXT_EQUAL_DAYTIME      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END NEXT_EQUAL_DAYTIME;
   FUNCTION PREV_DAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_NUM_ROWS IN NUMBER DEFAULT 1)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.PREV_DAYTIME      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_NUM_ROWS );
         RETURN ret_value;
   END PREV_DAYTIME;
   FUNCTION RECORD_STATUS(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (1) ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.RECORD_STATUS      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END RECORD_STATUS;
   FUNCTION APPROVAL_DATE(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.APPROVAL_DATE      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END APPROVAL_DATE;
   FUNCTION ROW_BY_PK(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_PK
   IS
      ret_value    REC_ROW_BY_PK ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.ROW_BY_PK      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_PK;
   FUNCTION ROW_BY_REL_OPERATOR(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN REC_ROW_BY_REL_OPERATOR
   IS
      ret_value    REC_ROW_BY_REL_OPERATOR ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.ROW_BY_REL_OPERATOR      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END ROW_BY_REL_OPERATOR;
   FUNCTION REC_ID(
      P_OBJECT_ID IN VARCHAR2,
      P_ORF_TYPE IN VARCHAR2,
      P_COMPONENT_NO IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_COMPARE_OPER IN VARCHAR2 DEFAULT '=')
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2 (32) ;
   BEGIN
      ret_value := EC_STRM_ORF_COMPONENT.REC_ID      (
         P_OBJECT_ID,
         P_ORF_TYPE,
         P_COMPONENT_NO,
         P_DAYTIME,
         P_COMPARE_OPER );
         RETURN ret_value;
   END REC_ID;

END RP_STRM_ORF_COMPONENT;

/
--GRANT EXECUTE ON ECKERNEL_WST.RP_STRM_ORF_COMPONENT TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 06.36.22 AM


