
 -- START PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.45 AM


CREATE or REPLACE PACKAGE RPBP_WELL_BLOWDOWN
IS

   FUNCTION COUNTCHILDEVENT(
      P_PARENT_EVENT_NO IN NUMBER)
      RETURN NUMBER;
   FUNCTION VALIDATEBLOWDOWNTIME(
      P_DAYTIME IN DATE,
      P_PARENT_EVENT_NO IN NUMBER)
      RETURN NUMBER;

END RPBP_WELL_BLOWDOWN;

/



CREATE or REPLACE PACKAGE BODY RPBP_WELL_BLOWDOWN
IS

   FUNCTION COUNTCHILDEVENT(
      P_PARENT_EVENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_BLOWDOWN.COUNTCHILDEVENT      (
         P_PARENT_EVENT_NO );
         RETURN ret_value;
   END COUNTCHILDEVENT;
   FUNCTION VALIDATEBLOWDOWNTIME(
      P_DAYTIME IN DATE,
      P_PARENT_EVENT_NO IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_BLOWDOWN.VALIDATEBLOWDOWNTIME      (
         P_DAYTIME,
         P_PARENT_EVENT_NO );
         RETURN ret_value;
   END VALIDATEBLOWDOWNTIME;

END RPBP_WELL_BLOWDOWN;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_WELL_BLOWDOWN TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.46 AM


