
 -- START PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.42 AM


CREATE or REPLACE PACKAGE RPBP_WELL_EVENT_DETAIL
IS

   FUNCTION GETLASTCLOSINGDAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_CLASS_NAME IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE;
   FUNCTION CALCINJECTIONRATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RATE_CALC_METHOD IN VARCHAR2,
      P_EVENT_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETLASTNOTNULLCLOSINGREADING(
      P_OBJECT_ID IN VARCHAR2,
      P_CLASS_NAME IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCINJECTIONVOLUME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RATE_CALC_METHOD IN VARCHAR2,
      P_EVENT_TYPE IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETDURATION(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;

END RPBP_WELL_EVENT_DETAIL;

/



CREATE or REPLACE PACKAGE BODY RPBP_WELL_EVENT_DETAIL
IS

   FUNCTION GETLASTCLOSINGDAYTIME(
      P_OBJECT_ID IN VARCHAR2,
      P_CLASS_NAME IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN DATE
   IS
      ret_value    DATE ;
   BEGIN
      ret_value := ECBP_WELL_EVENT_DETAIL.GETLASTCLOSINGDAYTIME      (
         P_OBJECT_ID,
         P_CLASS_NAME,
         P_DAYTIME );
         RETURN ret_value;
   END GETLASTCLOSINGDAYTIME;
   FUNCTION CALCINJECTIONRATE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RATE_CALC_METHOD IN VARCHAR2,
      P_EVENT_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_EVENT_DETAIL.CALCINJECTIONRATE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RATE_CALC_METHOD,
         P_EVENT_TYPE );
         RETURN ret_value;
   END CALCINJECTIONRATE;
   FUNCTION GETLASTNOTNULLCLOSINGREADING(
      P_OBJECT_ID IN VARCHAR2,
      P_CLASS_NAME IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_EVENT_DETAIL.GETLASTNOTNULLCLOSINGREADING      (
         P_OBJECT_ID,
         P_CLASS_NAME,
         P_DAYTIME );
         RETURN ret_value;
   END GETLASTNOTNULLCLOSINGREADING;
   FUNCTION CALCINJECTIONVOLUME(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RATE_CALC_METHOD IN VARCHAR2,
      P_EVENT_TYPE IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_EVENT_DETAIL.CALCINJECTIONVOLUME      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RATE_CALC_METHOD,
         P_EVENT_TYPE );
         RETURN ret_value;
   END CALCINJECTIONVOLUME;
   FUNCTION GETDURATION(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_WELL_EVENT_DETAIL.GETDURATION      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETDURATION;

END RPBP_WELL_EVENT_DETAIL;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_WELL_EVENT_DETAIL TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.44 AM


