
 -- START PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.56 AM


CREATE or REPLACE PACKAGE RPBP_TRANSACTION
IS

   FUNCTION GET_TRANSACTION_ACCOUNT(
      P_STORAGE_ID IN VARCHAR2,
      P_PARCEL_NO IN NUMBER,
      P_ACCOUNT_NO IN VARCHAR2)
      RETURN NUMBER;

END RPBP_TRANSACTION;

/



CREATE or REPLACE PACKAGE BODY RPBP_TRANSACTION
IS

   FUNCTION GET_TRANSACTION_ACCOUNT(
      P_STORAGE_ID IN VARCHAR2,
      P_PARCEL_NO IN NUMBER,
      P_ACCOUNT_NO IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_TRANSACTION.GET_TRANSACTION_ACCOUNT      (
         P_STORAGE_ID,
         P_PARCEL_NO,
         P_ACCOUNT_NO );
         RETURN ret_value;
   END GET_TRANSACTION_ACCOUNT;

END RPBP_TRANSACTION;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_TRANSACTION TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.56 AM


