
 -- START PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.47 AM


CREATE or REPLACE PACKAGE RPBP_VCF
IS

   FUNCTION CALCAPIGRAVITYOBS(
      P_API_GRAVITY IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CALCVCFOBSAPI(
      P_API_GRAVITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION GETAPIFROMDENSITY(
      P_DENSITY IN NUMBER)
      RETURN NUMBER;
   FUNCTION CALCVCFOBSDENSITY_SI(
      P_DENSITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_TEMP_BASE IN NUMBER DEFAULT 15,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CALCVCFSTDDENSITY_SI(
      P_DENSITY_STD IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_TEMP_BASE IN NUMBER DEFAULT 15,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CONVERTPRESSAPI(
      P_PRESS_OBS IN NUMBER,
      P_FROM_UNIT IN VARCHAR2,
      P_TO_UNIT IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION GETDENSITYFROMAPI(
      P_API IN NUMBER)
      RETURN NUMBER;
   FUNCTION CALCAPIGRAVITYCORR(
      P_API_GRAVITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CALCDELTATEMPIPTS68(
      P_TEMP_OBS IN NUMBER)
      RETURN NUMBER;
   FUNCTION CALCDENSITYCORR_SI(
      P_DENSITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_TEMP_BASE IN NUMBER DEFAULT 15,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CALCTEMPIPTS68(
      P_TEMP_OBS IN NUMBER)
      RETURN NUMBER;
   FUNCTION CALCVCFSTDDENSITY(
      P_DENSITY_STD IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CALCDENSITYCORR(
      P_DENSITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CALCSHRINKAGEFACTOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;
   FUNCTION CALCVCFSTDAPI(
      P_API_GRAVITY_STD IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER;
   FUNCTION CALCAPIBLENDSHRINKAGE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RETURN_CHAR IN VARCHAR2)
      RETURN NUMBER;
   FUNCTION CALCDILUENTCONCENTRATION(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER;

END RPBP_VCF;

/



CREATE or REPLACE PACKAGE BODY RPBP_VCF
IS

   FUNCTION CALCAPIGRAVITYOBS(
      P_API_GRAVITY IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCAPIGRAVITYOBS      (
         P_API_GRAVITY,
         P_TEMP_OBS,
         P_DECIMALS );
         RETURN ret_value;
   END CALCAPIGRAVITYOBS;
   FUNCTION CALCVCFOBSAPI(
      P_API_GRAVITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCVCFOBSAPI      (
         P_API_GRAVITY_OBS,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_DECIMALS );
         RETURN ret_value;
   END CALCVCFOBSAPI;
   FUNCTION GETAPIFROMDENSITY(
      P_DENSITY IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.GETAPIFROMDENSITY      (
         P_DENSITY );
         RETURN ret_value;
   END GETAPIFROMDENSITY;
   FUNCTION CALCVCFOBSDENSITY_SI(
      P_DENSITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_TEMP_BASE IN NUMBER DEFAULT 15,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCVCFOBSDENSITY_SI      (
         P_DENSITY_OBS,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_TEMP_BASE,
         P_DECIMALS );
         RETURN ret_value;
   END CALCVCFOBSDENSITY_SI;
   FUNCTION CALCVCFSTDDENSITY_SI(
      P_DENSITY_STD IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_TEMP_BASE IN NUMBER DEFAULT 15,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCVCFSTDDENSITY_SI      (
         P_DENSITY_STD,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_TEMP_BASE,
         P_DECIMALS );
         RETURN ret_value;
   END CALCVCFSTDDENSITY_SI;
   FUNCTION CONVERTPRESSAPI(
      P_PRESS_OBS IN NUMBER,
      P_FROM_UNIT IN VARCHAR2,
      P_TO_UNIT IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CONVERTPRESSAPI      (
         P_PRESS_OBS,
         P_FROM_UNIT,
         P_TO_UNIT );
         RETURN ret_value;
   END CONVERTPRESSAPI;
   FUNCTION GETDENSITYFROMAPI(
      P_API IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.GETDENSITYFROMAPI      (
         P_API );
         RETURN ret_value;
   END GETDENSITYFROMAPI;
   FUNCTION CALCAPIGRAVITYCORR(
      P_API_GRAVITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCAPIGRAVITYCORR      (
         P_API_GRAVITY_OBS,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_DECIMALS );
         RETURN ret_value;
   END CALCAPIGRAVITYCORR;
   FUNCTION CALCDELTATEMPIPTS68(
      P_TEMP_OBS IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCDELTATEMPIPTS68      (
         P_TEMP_OBS );
         RETURN ret_value;
   END CALCDELTATEMPIPTS68;
   FUNCTION CALCDENSITYCORR_SI(
      P_DENSITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_TEMP_BASE IN NUMBER DEFAULT 15,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCDENSITYCORR_SI      (
         P_DENSITY_OBS,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_TEMP_BASE,
         P_DECIMALS );
         RETURN ret_value;
   END CALCDENSITYCORR_SI;
   FUNCTION CALCTEMPIPTS68(
      P_TEMP_OBS IN NUMBER)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCTEMPIPTS68      (
         P_TEMP_OBS );
         RETURN ret_value;
   END CALCTEMPIPTS68;
   FUNCTION CALCVCFSTDDENSITY(
      P_DENSITY_STD IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCVCFSTDDENSITY      (
         P_DENSITY_STD,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_DECIMALS );
         RETURN ret_value;
   END CALCVCFSTDDENSITY;
   FUNCTION CALCDENSITYCORR(
      P_DENSITY_OBS IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCDENSITYCORR      (
         P_DENSITY_OBS,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_DECIMALS );
         RETURN ret_value;
   END CALCDENSITYCORR;
   FUNCTION CALCSHRINKAGEFACTOR(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCSHRINKAGEFACTOR      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCSHRINKAGEFACTOR;
   FUNCTION CALCVCFSTDAPI(
      P_API_GRAVITY_STD IN NUMBER,
      P_TEMP_OBS IN NUMBER,
      P_PRESS_OBS IN NUMBER DEFAULT NULL,
      P_DAYTIME IN DATE DEFAULT NULL,
      P_DECIMALS IN NUMBER DEFAULT 5)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCVCFSTDAPI      (
         P_API_GRAVITY_STD,
         P_TEMP_OBS,
         P_PRESS_OBS,
         P_DAYTIME,
         P_DECIMALS );
         RETURN ret_value;
   END CALCVCFSTDAPI;
   FUNCTION CALCAPIBLENDSHRINKAGE(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_RETURN_CHAR IN VARCHAR2)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCAPIBLENDSHRINKAGE      (
         P_OBJECT_ID,
         P_DAYTIME,
         P_RETURN_CHAR );
         RETURN ret_value;
   END CALCAPIBLENDSHRINKAGE;
   FUNCTION CALCDILUENTCONCENTRATION(
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN NUMBER
   IS
      ret_value   NUMBER ;
   BEGIN
      ret_value := ECBP_VCF.CALCDILUENTCONCENTRATION      (
         P_OBJECT_ID,
         P_DAYTIME );
         RETURN ret_value;
   END CALCDILUENTCONCENTRATION;

END RPBP_VCF;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPBP_VCF TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/08/2019 03.36.51 AM


