
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.49.16 AM


CREATE or REPLACE PACKAGE RPDP_FLOWLINE_SUB_WELL_CONN
IS

   FUNCTION FLOWLINEIDFORWELL(
      P_WELL_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION GETWELLSONFLOWLINE(
      P_FLOWLINE_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION FLOWLINESFORWELLPRODDAY(
      P_WELL_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;
   FUNCTION FLOWLINESFORWELL(
      P_WELL_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2;

END RPDP_FLOWLINE_SUB_WELL_CONN;

/



CREATE or REPLACE PACKAGE BODY RPDP_FLOWLINE_SUB_WELL_CONN
IS

   FUNCTION FLOWLINEIDFORWELL(
      P_WELL_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_FLOWLINE_SUB_WELL_CONN.FLOWLINEIDFORWELL      (
         P_WELL_ID,
         P_DAYTIME );
         RETURN ret_value;
   END FLOWLINEIDFORWELL;
   FUNCTION GETWELLSONFLOWLINE(
      P_FLOWLINE_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_FLOWLINE_SUB_WELL_CONN.GETWELLSONFLOWLINE      (
         P_FLOWLINE_ID,
         P_DAYTIME );
         RETURN ret_value;
   END GETWELLSONFLOWLINE;
   FUNCTION FLOWLINESFORWELLPRODDAY(
      P_WELL_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_FLOWLINE_SUB_WELL_CONN.FLOWLINESFORWELLPRODDAY      (
         P_WELL_ID,
         P_DAYTIME );
         RETURN ret_value;
   END FLOWLINESFORWELLPRODDAY;
   FUNCTION FLOWLINESFORWELL(
      P_WELL_ID IN VARCHAR2,
      P_DAYTIME IN DATE)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_FLOWLINE_SUB_WELL_CONN.FLOWLINESFORWELL      (
         P_WELL_ID,
         P_DAYTIME );
         RETURN ret_value;
   END FLOWLINESFORWELL;

END RPDP_FLOWLINE_SUB_WELL_CONN;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_FLOWLINE_SUB_WELL_CONN TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.49.17 AM


