
 -- START PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.47.46 AM


CREATE or REPLACE PACKAGE RPDP_OBJECTS_CHECK
IS

   FUNCTION GETOWNERJOINSTARTDATECOLUMN(
      P_DATA_CLASS_NAME IN VARCHAR2)
      RETURN VARCHAR2;
   FUNCTION GETOWNERJOINENDDATECOLUMN(
      P_DATA_CLASS_NAME IN VARCHAR2)
      RETURN VARCHAR2;

END RPDP_OBJECTS_CHECK;

/



CREATE or REPLACE PACKAGE BODY RPDP_OBJECTS_CHECK
IS

   FUNCTION GETOWNERJOINSTARTDATECOLUMN(
      P_DATA_CLASS_NAME IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_OBJECTS_CHECK.GETOWNERJOINSTARTDATECOLUMN      (
         P_DATA_CLASS_NAME );
         RETURN ret_value;
   END GETOWNERJOINSTARTDATECOLUMN;
   FUNCTION GETOWNERJOINENDDATECOLUMN(
      P_DATA_CLASS_NAME IN VARCHAR2)
      RETURN VARCHAR2
   IS
      ret_value   VARCHAR2(4000) ;
   BEGIN
      ret_value := ECDP_OBJECTS_CHECK.GETOWNERJOINENDDATECOLUMN      (
         P_DATA_CLASS_NAME );
         RETURN ret_value;
   END GETOWNERJOINENDDATECOLUMN;

END RPDP_OBJECTS_CHECK;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPDP_OBJECTS_CHECK TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/07/2019 11.47.46 AM


