
 -- START PKG_GEN_PKGS.sf_get_functions at:05/08/2019 04.23.04 AM


CREATE or REPLACE PACKAGE RPTP_CASING_COLLECT_SYSTEM
IS

   FUNCTION ALIGNPARENTVERSIONS(
      P_VT IN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE,
      P_GROUP_TYPE IN VARCHAR2,
      P_FROM_CLASS IN VARCHAR2 DEFAULT NULL)
      RETURN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE;
   FUNCTION SETOBJENDDATE(
      P_VT IN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE,
      P_OBJECT_ID IN VARCHAR2,
      P_END_DATE IN DATE,
      P_LAST_UPDATED_BY IN VARCHAR2 DEFAULT USER,
      P_LAST_UPDATED_DATE IN DATE DEFAULT EcDp_Date_Time.GetCurrentSysDate,
      P_REV_TEXT IN VARCHAR2)
      RETURN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE;
   FUNCTION SETOBJSTARTDATE(
      P_VT IN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_LAST_UPDATED_BY IN VARCHAR2 DEFAULT USER,
      P_LAST_UPDATED_DATE IN DATE DEFAULT EcDp_Date_Time.GetCurrentSysDate)
      RETURN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE;

END RPTP_CASING_COLLECT_SYSTEM;

/



CREATE or REPLACE PACKAGE BODY RPTP_CASING_COLLECT_SYSTEM
IS

   FUNCTION ALIGNPARENTVERSIONS(
      P_VT IN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE,
      P_GROUP_TYPE IN VARCHAR2,
      P_FROM_CLASS IN VARCHAR2 DEFAULT NULL)
      RETURN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE
   IS
      ret_value    ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE ;
   BEGIN
      ret_value := ECTP_CASING_COLLECT_SYSTEM.ALIGNPARENTVERSIONS      (
         P_VT,
         P_GROUP_TYPE,
         P_FROM_CLASS );
         RETURN ret_value;
   END ALIGNPARENTVERSIONS;
   FUNCTION SETOBJENDDATE(
      P_VT IN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE,
      P_OBJECT_ID IN VARCHAR2,
      P_END_DATE IN DATE,
      P_LAST_UPDATED_BY IN VARCHAR2 DEFAULT USER,
      P_LAST_UPDATED_DATE IN DATE DEFAULT EcDp_Date_Time.GetCurrentSysDate,
      P_REV_TEXT IN VARCHAR2)
      RETURN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE
   IS
      ret_value    ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE ;
   BEGIN
      ret_value := ECTP_CASING_COLLECT_SYSTEM.SETOBJENDDATE      (
         P_VT,
         P_OBJECT_ID,
         P_END_DATE,
         P_LAST_UPDATED_BY,
         P_LAST_UPDATED_DATE,
         P_REV_TEXT );
         RETURN ret_value;
   END SETOBJENDDATE;
   FUNCTION SETOBJSTARTDATE(
      P_VT IN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE,
      P_OBJECT_ID IN VARCHAR2,
      P_DAYTIME IN DATE,
      P_LAST_UPDATED_BY IN VARCHAR2 DEFAULT USER,
      P_LAST_UPDATED_DATE IN DATE DEFAULT EcDp_Date_Time.GetCurrentSysDate)
      RETURN ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE
   IS
      ret_value    ECTP_CASING_COLLECT_SYSTEM.VER_TAB_TYPE ;
   BEGIN
      ret_value := ECTP_CASING_COLLECT_SYSTEM.SETOBJSTARTDATE      (
         P_VT,
         P_OBJECT_ID,
         P_DAYTIME,
         P_LAST_UPDATED_BY,
         P_LAST_UPDATED_DATE );
         RETURN ret_value;
   END SETOBJSTARTDATE;

END RPTP_CASING_COLLECT_SYSTEM;

/
--GRANT EXECUTE ON ECKERNEL_WST.RPTP_CASING_COLLECT_SYSTEM TO REPORT_ROLE_XXX;



 -- FINISH PKG_GEN_PKGS.sf_get_functions at:05/08/2019 04.23.05 AM


