!!com.ec.upgrade.schema.dto.TableDTO
name: CLASS_ATTR_PRES_CONFIG
cnstPrimaryKey:
  columns:
  - CONFIG_NO
  name: PK_CLASS_ATTR_PRES_CONFIG
  type: PRIMARYKEY
  status: UNDEFINED
columns:
  APPROVAL_BY:
    columnName: APPROVAL_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '17'
  APPROVAL_DATE:
    columnName: APPROVAL_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '18'
  APPROVAL_STATE:
    columnName: APPROVAL_STATE
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '16'
  ATTRIBUTE_NAME:
    columnName: ATTRIBUTE_NAME
    typeName: VARCHAR2(24)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '3'
  CLASS_NAME:
    columnName: CLASS_NAME
    typeName: VARCHAR2(24)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '2'
  COMPONENT_URL:
    columnName: COMPONENT_URL
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '6'
  CONFIG_NO:
    columnName: CONFIG_NO
    typeName: NUMBER
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '1'
  CREATED_BY:
    columnName: CREATED_BY
    typeName: VARCHAR2(30)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '10'
  CREATED_DATE:
    columnName: CREATED_DATE
    typeName: DATE
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '11'
  LAST_UPDATED_BY:
    columnName: LAST_UPDATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '12'
  LAST_UPDATED_DATE:
    columnName: LAST_UPDATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '13'
  OBJECT_REF_ID:
    columnName: OBJECT_REF_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '4'
  PRES_ATTRIBUTE_NAME:
    columnName: PRES_ATTRIBUTE_NAME
    typeName: VARCHAR2(240)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '7'
  PRES_ATTRIBUTE_VALUE:
    columnName: PRES_ATTRIBUTE_VALUE
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '8'
  PROFILE_CODE:
    columnName: PROFILE_CODE
    typeName: VARCHAR2(255)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '5'
  RECORD_STATUS:
    columnName: RECORD_STATUS
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '9'
  REC_ID:
    columnName: REC_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '19'
  REV_NO:
    columnName: REV_NO
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '14'
  REV_TEXT:
    columnName: REV_TEXT
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '15'
cnstUniqueKeys:
  UK_CLASS_ATTR_PRES_CONFIG_1:
    columns:
    - CLASS_NAME
    - ATTRIBUTE_NAME
    - OBJECT_REF_ID
    - PROFILE_CODE
    - COMPONENT_URL
    - PRES_ATTRIBUTE_NAME
    name: UK_CLASS_ATTR_PRES_CONFIG_1
    type: UNIQUEKEY
    status: UNDEFINED
cnstChecks:
  CHK_CLASS_ATTR_PRES_CONFIG_1:
    searchCondition: APPROVAL_STATE IS NULL OR APPROVAL_STATE IN ('N','O','U','D')
    columns:
    - APPROVAL_STATE
    name: CHK_CLASS_ATTR_PRES_CONFIG_1
    type: CHECK
    status: UNDEFINED
indexes:
  IR_CLASS_ATTR_PRES_CONFIG:
    indexName: IR_CLASS_ATTR_PRES_CONFIG
    columns:
    - REC_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
attributes:
  initialExtent: 65536
  iniTrans: 1
  minExtent: 1
  maxExtent: 2147483645
  maxTrans: 255
  nextExtent: 262144
  pctFree: 10
  pctUsed: 0
  pctIncrease: 0
status: UNDEFINED
