!!com.ec.upgrade.schema.dto.TableDTO
name: PRODUCT_PRICE
cnstPrimaryKey:
  columns:
  - OBJECT_ID
  name: PK_PRODUCT_PRICE
  type: PRIMARYKEY
  status: UNDEFINED
columns:
  APPROVAL_BY:
    columnName: APPROVAL_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '18'
  APPROVAL_DATE:
    columnName: APPROVAL_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '19'
  APPROVAL_STATE:
    columnName: APPROVAL_STATE
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '20'
  CLASS_NAME:
    columnName: CLASS_NAME
    typeName: VARCHAR2(24)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '22'
  CONTRACT_ID:
    columnName: CONTRACT_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '6'
  CREATED_BY:
    columnName: CREATED_BY
    typeName: VARCHAR2(30)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '12'
  CREATED_DATE:
    columnName: CREATED_DATE
    typeName: DATE
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '13'
  DESCRIPTION:
    columnName: DESCRIPTION
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '10'
  END_DATE:
    columnName: END_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '5'
  INVENTORY_ID:
    columnName: INVENTORY_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '9'
  LAST_UPDATED_BY:
    columnName: LAST_UPDATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '14'
  LAST_UPDATED_DATE:
    columnName: LAST_UPDATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '15'
  OBJECT_CODE:
    columnName: OBJECT_CODE
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '2'
  OBJECT_ID:
    columnName: OBJECT_ID
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '1'
  PRICE_CONCEPT_CODE:
    columnName: PRICE_CONCEPT_CODE
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '7'
  PRODUCT_ID:
    columnName: PRODUCT_ID
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '3'
  RECORD_STATUS:
    columnName: RECORD_STATUS
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '11'
  REC_ID:
    columnName: REC_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '21'
  REVN_IND:
    columnName: REVN_IND
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '8'
  REV_NO:
    columnName: REV_NO
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '16'
  REV_TEXT:
    columnName: REV_TEXT
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '17'
  START_DATE:
    columnName: START_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '4'
cnstUniqueKeys:
  UK_PRODUCT_PRICE_1:
    columns:
    - OBJECT_CODE
    name: UK_PRODUCT_PRICE_1
    type: UNIQUEKEY
    status: UNDEFINED
cnstForeignKeys:
  FK_PRODUCT_PRICE_1:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: PRODUCT
    columns:
      PRODUCT_ID: OBJECT_ID
    name: FK_PRODUCT_PRICE_1
    type: FOREIGNKEY
    status: UNDEFINED
  FK_PRODUCT_PRICE_2:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: CONTRACT
    columns:
      CONTRACT_ID: OBJECT_ID
    name: FK_PRODUCT_PRICE_2
    type: FOREIGNKEY
    status: UNDEFINED
  FK_PRODUCT_PRICE_3:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: PRICE_CONCEPT
    columns:
      PRICE_CONCEPT_CODE: PRICE_CONCEPT_CODE
    name: FK_PRODUCT_PRICE_3
    type: FOREIGNKEY
    status: UNDEFINED
cnstChecks:
  CHK_PRODUCT_PRICE_1:
    searchCondition: APPROVAL_STATE IS NULL OR APPROVAL_STATE IN ('N','O','U','D')
    columns:
    - APPROVAL_STATE
    name: CHK_PRODUCT_PRICE_1
    type: CHECK
    status: UNDEFINED
indexes:
  IFK_PRODUCT_PRICE_1:
    indexName: IFK_PRODUCT_PRICE_1
    columns:
    - PRODUCT_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
  IFK_PRODUCT_PRICE_2:
    indexName: IFK_PRODUCT_PRICE_2
    columns:
    - CONTRACT_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
  IFK_PRODUCT_PRICE_3:
    indexName: IFK_PRODUCT_PRICE_3
    columns:
    - PRICE_CONCEPT_CODE
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
  IFK_PRODUCT_PRICE_4:
    indexName: IFK_PRODUCT_PRICE_4
    columns:
    - INVENTORY_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
  IR_PRODUCT_PRICE:
    indexName: IR_PRODUCT_PRICE
    columns:
    - REC_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
attributes:
  initialExtent: 65536
  iniTrans: 1
  minExtent: 1
  maxExtent: 2147483645
  maxTrans: 255
  nextExtent: 262144
  pctFree: 10
  pctUsed: 0
  pctIncrease: 0
status: UNDEFINED
