!!com.ec.upgrade.schema.dto.TableDTO
name: PROD_CARRIER_FIGURES
cnstPrimaryKey:
  columns:
  - OBJECT_ID
  - CARGO_NO
  - ITEM_NAME
  name: PK_PROD_CARRIER_FIGURES
  type: PRIMARYKEY
  status: UNDEFINED
columns:
  APPROVAL_BY:
    columnName: APPROVAL_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '67'
  APPROVAL_DATE:
    columnName: APPROVAL_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '68'
  APPROVAL_STATE:
    columnName: APPROVAL_STATE
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '69'
  CARGO_NO:
    columnName: CARGO_NO
    typeName: NUMBER
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '2'
  CREATED_BY:
    columnName: CREATED_BY
    typeName: VARCHAR2(30)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '61'
  CREATED_DATE:
    columnName: CREATED_DATE
    typeName: DATE
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '62'
  DATE_1:
    columnName: DATE_1
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '50'
  DATE_10:
    columnName: DATE_10
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '59'
  DATE_2:
    columnName: DATE_2
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '51'
  DATE_3:
    columnName: DATE_3
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '52'
  DATE_4:
    columnName: DATE_4
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '53'
  DATE_5:
    columnName: DATE_5
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '54'
  DATE_6:
    columnName: DATE_6
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '55'
  DATE_7:
    columnName: DATE_7
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '56'
  DATE_8:
    columnName: DATE_8
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '57'
  DATE_9:
    columnName: DATE_9
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '58'
  ITEM_NAME:
    columnName: ITEM_NAME
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '3'
  ITEM_VALUE:
    columnName: ITEM_VALUE
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '4'
  LAST_UPDATED_BY:
    columnName: LAST_UPDATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '63'
  LAST_UPDATED_DATE:
    columnName: LAST_UPDATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '64'
  OBJECT_ID:
    columnName: OBJECT_ID
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '1'
  RECORD_STATUS:
    columnName: RECORD_STATUS
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '60'
  REC_ID:
    columnName: REC_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '70'
  REV_NO:
    columnName: REV_NO
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '65'
  REV_TEXT:
    columnName: REV_TEXT
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '66'
  TEXT_1:
    columnName: TEXT_1
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '35'
  TEXT_10:
    columnName: TEXT_10
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '44'
  TEXT_11:
    columnName: TEXT_11
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '45'
  TEXT_12:
    columnName: TEXT_12
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '46'
  TEXT_13:
    columnName: TEXT_13
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '47'
  TEXT_14:
    columnName: TEXT_14
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '48'
  TEXT_15:
    columnName: TEXT_15
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '49'
  TEXT_2:
    columnName: TEXT_2
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '36'
  TEXT_3:
    columnName: TEXT_3
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '37'
  TEXT_4:
    columnName: TEXT_4
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '38'
  TEXT_5:
    columnName: TEXT_5
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '39'
  TEXT_6:
    columnName: TEXT_6
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '40'
  TEXT_7:
    columnName: TEXT_7
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '41'
  TEXT_8:
    columnName: TEXT_8
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '42'
  TEXT_9:
    columnName: TEXT_9
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '43'
  VALUE_1:
    columnName: VALUE_1
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '5'
  VALUE_10:
    columnName: VALUE_10
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '14'
  VALUE_11:
    columnName: VALUE_11
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '15'
  VALUE_12:
    columnName: VALUE_12
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '16'
  VALUE_13:
    columnName: VALUE_13
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '17'
  VALUE_14:
    columnName: VALUE_14
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '18'
  VALUE_15:
    columnName: VALUE_15
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '19'
  VALUE_16:
    columnName: VALUE_16
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '20'
  VALUE_17:
    columnName: VALUE_17
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '21'
  VALUE_18:
    columnName: VALUE_18
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '22'
  VALUE_19:
    columnName: VALUE_19
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '23'
  VALUE_2:
    columnName: VALUE_2
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '6'
  VALUE_20:
    columnName: VALUE_20
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '24'
  VALUE_21:
    columnName: VALUE_21
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '25'
  VALUE_22:
    columnName: VALUE_22
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '26'
  VALUE_23:
    columnName: VALUE_23
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '27'
  VALUE_24:
    columnName: VALUE_24
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '28'
  VALUE_25:
    columnName: VALUE_25
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '29'
  VALUE_26:
    columnName: VALUE_26
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '30'
  VALUE_27:
    columnName: VALUE_27
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '31'
  VALUE_28:
    columnName: VALUE_28
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '32'
  VALUE_29:
    columnName: VALUE_29
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '33'
  VALUE_3:
    columnName: VALUE_3
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '7'
  VALUE_30:
    columnName: VALUE_30
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '34'
  VALUE_4:
    columnName: VALUE_4
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '8'
  VALUE_5:
    columnName: VALUE_5
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '9'
  VALUE_6:
    columnName: VALUE_6
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '10'
  VALUE_7:
    columnName: VALUE_7
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '11'
  VALUE_8:
    columnName: VALUE_8
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '12'
  VALUE_9:
    columnName: VALUE_9
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '13'
cnstForeignKeys:
  FK_PROD_CARRIER_FIGURES_1:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: PRODUCT
    columns:
      OBJECT_ID: OBJECT_ID
    name: FK_PROD_CARRIER_FIGURES_1
    type: FOREIGNKEY
    status: UNDEFINED
  FK_PROD_CARRIER_FIGURES_2:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: CARGO_TRANSPORT
    columns:
      CARGO_NO: CARGO_NO
    name: FK_PROD_CARRIER_FIGURES_2
    type: FOREIGNKEY
    status: UNDEFINED
cnstChecks:
  CHK_PROD_CARRIER_FIGURES_1:
    searchCondition: APPROVAL_STATE IS NULL OR APPROVAL_STATE IN ('N','O','U','D')
    columns:
    - APPROVAL_STATE
    name: CHK_PROD_CARRIER_FIGURES_1
    type: CHECK
    status: UNDEFINED
indexes:
  IFK_PROD_CARRIER_FIGURES_2:
    indexName: IFK_PROD_CARRIER_FIGURES_2
    columns:
    - CARGO_NO
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
  IR_PROD_CARRIER_FIGURES:
    indexName: IR_PROD_CARRIER_FIGURES
    columns:
    - REC_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
attributes:
  initialExtent: 262144
  iniTrans: 1
  minExtent: 1
  maxExtent: 2147483645
  maxTrans: 255
  nextExtent: 262144
  pctFree: 10
  pctUsed: 0
  pctIncrease: 0
status: UNDEFINED
