DECLARE
HASENTRY1 NUMBER;
HASENTRY2 NUMBER;
  cursor cur_stream is 
    select object_id, description
      from strm_version;
BEGIN
  FOR i in cur_stream LOOP
    BEGIN
	
	SELECT COUNT(*) INTO HASENTRY1 FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_STRM_VERSION'; 
		IF HASENTRY1 > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_STRM_VERSION DISABLE';
		END IF;
		
        UPDATE STRM_VERSION 
           SET description = i.description
         WHERE object_id = i.object_id;
		 
	SELECT COUNT(*) INTO HASENTRY1 FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_STRM_VERSION'; 
		IF HASENTRY1 > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_STRM_VERSION ENABLE';
		END IF;	 
         
    SELECT COUNT(*) INTO HASENTRY2 FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_STRM_VERSION_JN'; 
		IF HASENTRY2 > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_STRM_VERSION_JN DISABLE';
		END IF;
		
		UPDATE STRM_VERSION_JN 
           SET description = i.description
         WHERE object_id = i.object_id; 
		 
	SELECT COUNT(*) INTO HASENTRY2 FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_STRM_VERSION_JN'; 
		IF HASENTRY2 > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_STRM_VERSION_JN ENABLE';
		END IF;
		
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END LOOP;
  COMMIT;
EXCEPTION
   WHEN OTHERS 
     THEN

       IF HASENTRY1 > 0 THEN 
           EXECUTE IMMEDIATE 'ALTER TRIGGER IU_STRM_VERSION ENABLE';
       END IF;
	   
	    IF HASENTRY2 > 0 THEN 
           EXECUTE IMMEDIATE 'ALTER TRIGGER IU_STRM_VERSION_JN ENABLE';
       END IF;
        
        raise_application_error(-20000,
                            'ERROR: Some Other fatal error occured :- '||SQLERRM);


END;
/