INSERT INTO APP_SPACE_CNTX (CODE, NAME, OWNER_CNTX, SORT_ORDER) values ('CVX_ENH','Chevron Enhancements',2100,100);
INSERT INTO APP_SPACE_CNTX (CODE, NAME, OWNER_CNTX, SORT_ORDER) VALUES('CVX', 'Chevron Global Template', 2500, 90);
INSERT INTO APP_SPACE_CNTX (CODE, NAME, OWNER_CNTX, SORT_ORDER) VALUES('WST', 'WHEATSTONE Customizations', 2500, 100);
INSERT INTO APP_SPACE_CNTX (CODE, NAME, OWNER_CNTX, SORT_ORDER) VALUES('GORGON', 'GORGON Customizations', 2500, 110);
INSERT INTO APP_SPACE_CNTX (CODE, NAME, OWNER_CNTX, SORT_ORDER) VALUES('DELETE_CANDIDATE', 'To be deleted', 2500, 120);
UPDATE CLASS_DEPENDENCY_CNFG SET APP_SPACE_CNTX ='WST' where APP_SPACE_CNTX IN ('XX_TRAN','XX_PROD');

ALTER TABLE CLASS_ATTRIBUTE_CNFG ADD CONSTRAINT FK_CLASS_ATTRIBUTE_CNFG_1 FOREIGN KEY (APP_SPACE_CNTX) REFERENCES APP_SPACE_CNTX (CODE);
ALTER TABLE CLASS_CNFG ADD CONSTRAINT FK_CLASS_CNFG_1 FOREIGN KEY (APP_SPACE_CNTX) REFERENCES APP_SPACE_CNTX (CODE);
ALTER TABLE CLASS_DEPENDENCY_CNFG ADD CONSTRAINT FK_CLASS_DEPENDENCY_CNFG_1 FOREIGN KEY (APP_SPACE_CNTX) REFERENCES APP_SPACE_CNTX (CODE);
ALTER TABLE CLASS_RELATION_CNFG ADD CONSTRAINT FK_CLASS_RELATION_CNFG_1 FOREIGN KEY (APP_SPACE_CNTX) REFERENCES APP_SPACE_CNTX (CODE);
ALTER TABLE CLASS_TRIGGER_ACTN_CNFG ADD CONSTRAINT FK_CLASS_TRIGGER_ACTN_CNFG_2 FOREIGN KEY (APP_SPACE_CNTX) REFERENCES APP_SPACE_CNTX (CODE);

UPDATE CLASS_TRIGGER_ACTN_CNFG SET APP_SPACE_CNTX='WST' WHERE APP_SPACE_CNTX='GORGON';
DELETE FROM APP_SPACE_CNTX WHERE CODE='GORGON';