   ALTER TABLE deferment_event DISABLE ALL TRIGGERS;

  INSERT INTO deferment_event
(
	 OBJECT_ID
	,CLASS_NAME
	,OBJECT_TYPE
	,EVENT_NO
	,PARENT_EVENT_NO
	,EVENT_TYPE
	,DEFERMENT_TYPE
	,SCHEDULED
	,DAYTIME
	,END_DATE
	,MASTER_EVENT_ID
	,PARENT_DAYTIME
	,PARENT_MASTER_EVENT_ID
	,PARENT_OBJECT_ID
	,REASON_CODE_1
	,REASON_CODE_2
	,REASON_CODE_3
	,REASON_CODE_4
	,OIL_LOSS_RATE
	,COND_LOSS_RATE
	,GAS_LOSS_RATE
	,WATER_LOSS_RATE
	,GAS_INJ_LOSS_RATE
	,WATER_INJ_LOSS_RATE
	,STEAM_INJ_LOSS_RATE
	,STATUS
	,COMMENTS
  ,VALUE_2
  ,TEXT_1	
	,REASON_CODE_TYPE_1
	,REASON_CODE_TYPE_2
	,REASON_CODE_TYPE_3
	,REASON_CODE_TYPE_4
	,DAY
	,END_DAY
	,SUMMER_TIME
	,EQUIPMENT_ID
	,RECORD_STATUS
	,CREATED_BY
	,CREATED_DATE
	,LAST_UPDATED_BY
	,LAST_UPDATED_DATE
	,REV_NO
	,REV_TEXT
	,REC_ID
)
SELECT
	 OBJECT_ID
	,decode(DOWNTIME_CLASS_TYPE,'GROUP_CHILD','WELL_DEFERMENT_CHILD','WELL_DEFERMENT') 
	,OBJECT_TYPE
	,EcDp_System_Key.assignNextNumberNonAutonomous('DEFERMENT_EVENT') as EVENT_NO
	,null as PARENT_EVENT_NO
	,decode(DOWNTIME_CATEG, 'WELL_LOW', 'CONSTRAINT', 'DOWN') as EVENT_TYPE
	,DOWNTIME_CLASS_TYPE as DEFERMENT_TYPE
	,null as SCHEDULED
	,DAYTIME
	,END_DATE
	,MASTER_EVENT_ID
	,PARENT_DAYTIME
	,PARENT_MASTER_EVENT_ID
	,PARENT_OBJECT_ID
	,REASON_CODE_1
	,REASON_CODE_2
	,REASON_CODE_3
	,REASON_CODE_4
	,OIL_LOSS_RATE
	,COND_LOSS_RATE
	,GAS_LOSS_RATE
	,WATER_LOSS_RATE
	,GAS_INJ_LOSS_RATE
	,WATER_INJ_LOSS_RATE
	,STEAM_INJ_LOSS_RATE
	,STATUS
	,COMMENTS
  ,VALUE_2
  ,TEXT_1	
	,'DEFER_SYS_GRP' as REASON_CODE_TYPE_1
	,'DEFER_CAUSE_GRP' as REASON_CODE_TYPE_2
	,'DEFER_CAUSE_CAT' as REASON_CODE_TYPE_3
	,'WELL_DT_REAS_4' as REASON_CODE_TYPE_4
	,trunc(DAYTIME) as DAY
  ,trunc(END_DATE) as END_DAY
	,ecdp_date_time.summertime_flag(DAYTIME, NULL, OBJECT_ID) as SUMMER_TIME
	,EQUIPMENT_ID
	,RECORD_STATUS
	,CREATED_BY
	,CREATED_DATE
	,LAST_UPDATED_BY
	,LAST_UPDATED_DATE
	,REV_NO
	,REV_TEXT
	,REC_ID
from well_equip_downtime_bkup
;

update deferment_event d1
set parent_event_no = (select event_no from deferment_event d2 where d2.object_id = d1.parent_object_id and d2.daytime = d1.daytime)
where parent_object_id is not null;

begin
INSERT INTO ASSIGN_ID (TABLENAME, MAX_ID) VALUES ('DEFERMENT_EVENT', (select max(event_no) from DEFERMENT_EVENT));
exception when others then
UPDATE assign_id SET max_id=(select max(event_no) from DEFERMENT_EVENT) WHERE tablename='DEFERMENT_EVENT' ;
end;
/


ALTER TABLE DEFERMENT_EVENT ENABLE ALL TRIGGERS;