UPDATE CLASS_ATTRIBUTE_CNFG SET DB_SQL_SYNTAX='EcBp_Stream_Fluid.findNetStdMass(V_STRM_DAY_DER_STREAM.object_id, V_STRM_DAY_DER_STREAM.daytime)' WHERE CLASS_NAME='STRM_DAY_STREAM_DER_GAS' AND ATTRIBUTE_NAME='NET_MASS_GAS';

UPDATE CLASS_ATTRIBUTE_CNFG SET DB_SQL_SYNTAX='EcBp_Stream_Fluid.findNetStdMass(strm_day_stream.object_id, strm_day_stream.daytime)' WHERE CLASS_NAME='STRM_DAY_STREAM_MEAS_GAS' AND ATTRIBUTE_NAME='NET_MASS_GAS';

UPDATE CLASS_ATTRIBUTE_CNFG SET DB_SQL_SYNTAX='VALUE_47' WHERE CLASS_NAME='STRM_GAS_ANALYSIS' AND ATTRIBUTE_NAME='WOBBE_INDEX';

UPDATE CLASS_ATTRIBUTE_CNFG SET DATA_TYPE='STRING' WHERE CLASS_NAME='FCST_STOR_LIFT_NOM' AND ATTRIBUTE_NAME='COOLDOWN_QTY';

UPDATE CLASS_ATTRIBUTE_CNFG SET DATA_TYPE='STRING' WHERE CLASS_NAME='FCST_STOR_LIFT_NOM' AND ATTRIBUTE_NAME='PURGE_QTY';

INSERT INTO CLASS_REL_PROPERTY_CNFG (FROM_CLASS_NAME, TO_CLASS_NAME, ROLE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) 
VALUES ('PRODUCTIONUNIT','PROD_SUB_UNIT','OP_PRODUCTIONUNIT','DISABLED_IND',2500,'/','VIEWLAYER','Y');

INSERT INTO CLASS_TRA_PROPERTY_CNFG (CLASS_NAME, TRIGGERING_EVENT, TRIGGER_TYPE, SORT_ORDER, PROPERTY_CODE, OWNER_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) 
VALUES ('STOR_LIFT_NOM_LIGHT','INSERTING OR UPDATING','BEFORE',100,'DISABLED_IND',2500,'VIEWLAYER','Y');

INSERT INTO CLASS_TRA_PROPERTY_CNFG (CLASS_NAME, TRIGGERING_EVENT, TRIGGER_TYPE, SORT_ORDER, PROPERTY_CODE, OWNER_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) 
VALUES ('STOR_LIFT_NOM_LIGHT','INSERTING OR UPDATING','BEFORE',300,'DISABLED_IND',2500,'VIEWLAYER','Y');

