!!com.ec.upgrade.schema.dto.TableDTO
name: PRODUCT_MTH_PRICE
cnstPrimaryKey:
  columns:
  - PRODUCT_ID
  - DAYTIME
  name: PK_PRODUCT_MTH_PRICE
  type: PRIMARYKEY
  status: UNDEFINED
columns:
  APPROVAL_BY:
    columnName: APPROVAL_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '15'
  APPROVAL_DATE:
    columnName: APPROVAL_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '16'
  APPROVAL_STATE:
    columnName: APPROVAL_STATE
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '17'
  CREATED_BY:
    columnName: CREATED_BY
    typeName: VARCHAR2(30)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '9'
  CREATED_DATE:
    columnName: CREATED_DATE
    typeName: DATE
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '10'
  DAYTIME:
    columnName: DAYTIME
    typeName: DATE
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '1'
  LAST_UPDATED_BY:
    columnName: LAST_UPDATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '11'
  LAST_UPDATED_DATE:
    columnName: LAST_UPDATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '12'
  PRICE_USD:
    columnName: PRICE_USD
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '3'
  PRICE_USD_BBLS_HIGH:
    columnName: PRICE_USD_BBLS_HIGH
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '4'
  PRICE_USD_BBLS_LOW:
    columnName: PRICE_USD_BBLS_LOW
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '5'
  PRICE_USD_TONNES_HIGH:
    columnName: PRICE_USD_TONNES_HIGH
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '6'
  PRICE_USD_TONNES_LOW:
    columnName: PRICE_USD_TONNES_LOW
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '7'
  PRODUCT_ID:
    columnName: PRODUCT_ID
    typeName: VARCHAR2(20)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '2'
  RECORD_STATUS:
    columnName: RECORD_STATUS
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '8'
  REC_ID:
    columnName: REC_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '18'
  REV_NO:
    columnName: REV_NO
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '13'
  REV_TEXT:
    columnName: REV_TEXT
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '14'
cnstForeignKeys:
  FK_PRODUCT_MTH_PRICE_1:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: OIL_PRODUCT
    columns:
      PRODUCT_ID: PRODUCT_ID
    name: FK_PRODUCT_MTH_PRICE_1
    type: FOREIGNKEY
    status: UNDEFINED
cnstChecks:
  CHK_PRODUCT_MTH_PRICE_1:
    searchCondition: APPROVAL_STATE IS NULL OR APPROVAL_STATE IN ('N','O','U','D')
    columns:
    - APPROVAL_STATE
    name: CHK_PRODUCT_MTH_PRICE_1
    type: CHECK
    status: UNDEFINED
indexes:
  IR_PRODUCT_MTH_PRICE:
    indexName: IR_PRODUCT_MTH_PRICE
    columns:
    - REC_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
attributes:
  initialExtent: 65536
  iniTrans: 1
  minExtent: 1
  maxExtent: 2147483645
  maxTrans: 255
  nextExtent: 65536
  pctFree: 10
  pctUsed: 0
  pctIncrease: 0
status: UNDEFINED
