!!com.ec.upgrade.schema.dto.TableDTO
name: PRODUCT_FIELD
cnstPrimaryKey:
  columns:
  - OBJECT_ID
  name: PK_PRODUCT_FIELD
  type: PRIMARYKEY
  status: UNDEFINED
columns:
  APPROVAL_BY:
    columnName: APPROVAL_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '17'
  APPROVAL_DATE:
    columnName: APPROVAL_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '18'
  APPROVAL_STATE:
    columnName: APPROVAL_STATE
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '19'
  CLASS_NAME:
    columnName: CLASS_NAME
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '9'
  CONVERSION_TYPE:
    columnName: CONVERSION_TYPE
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '7'
  CREATED_BY:
    columnName: CREATED_BY
    typeName: VARCHAR2(30)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '11'
  CREATED_DATE:
    columnName: CREATED_DATE
    typeName: DATE
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '12'
  DESCRIPTION:
    columnName: DESCRIPTION
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '8'
  END_DATE:
    columnName: END_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '6'
  FIELD_ID:
    columnName: FIELD_ID
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '4'
  LAST_UPDATED_BY:
    columnName: LAST_UPDATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '13'
  LAST_UPDATED_DATE:
    columnName: LAST_UPDATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '14'
  OBJECT_CODE:
    columnName: OBJECT_CODE
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '2'
  OBJECT_ID:
    columnName: OBJECT_ID
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '1'
  PRODUCT_ID:
    columnName: PRODUCT_ID
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '3'
  RECORD_STATUS:
    columnName: RECORD_STATUS
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '10'
  REC_ID:
    columnName: REC_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '20'
  REV_NO:
    columnName: REV_NO
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '15'
  REV_TEXT:
    columnName: REV_TEXT
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '16'
  START_DATE:
    columnName: START_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '5'
cnstUniqueKeys:
  UK_PRODUCT_FIELD_1:
    columns:
    - OBJECT_CODE
    name: UK_PRODUCT_FIELD_1
    type: UNIQUEKEY
    status: UNDEFINED
  UK_PRODUCT_FIELD_2:
    columns:
    - PRODUCT_ID
    - FIELD_ID
    - CONVERSION_TYPE
    name: UK_PRODUCT_FIELD_2
    type: UNIQUEKEY
    status: UNDEFINED
cnstForeignKeys:
  FK_PRODUCT_FIELD_1:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: PRODUCT
    columns:
      PRODUCT_ID: OBJECT_ID
    name: FK_PRODUCT_FIELD_1
    type: FOREIGNKEY
    status: UNDEFINED
  FK_PRODUCT_FIELD_2:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: FIELD
    columns:
      FIELD_ID: OBJECT_ID
    name: FK_PRODUCT_FIELD_2
    type: FOREIGNKEY
    status: UNDEFINED
cnstChecks:
  CHK_PRODUCT_FIELD_1:
    searchCondition: APPROVAL_STATE IS NULL OR APPROVAL_STATE IN ('N','O','U','D')
    columns:
    - APPROVAL_STATE
    name: CHK_PRODUCT_FIELD_1
    type: CHECK
    status: UNDEFINED
indexes:
  IFK_PRODUCT_FIELD_2:
    indexName: IFK_PRODUCT_FIELD_2
    columns:
    - FIELD_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
  IR_PRODUCT_FIELD:
    indexName: IR_PRODUCT_FIELD
    columns:
    - REC_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
attributes:
  initialExtent: 65536
  iniTrans: 1
  minExtent: 1
  maxExtent: 2147483645
  maxTrans: 255
  nextExtent: 262144
  pctFree: 10
  pctUsed: 0
  pctIncrease: 0
status: UNDEFINED
