create table CT_DQ_RULE
( RULE_ID        INTEGER NOT NULL,
  IS_ACTIVE    CHAR(1) DEFAULT 'N', 
  RULE_DESCRIPTION    VARCHAR2(100),
  COMMENTS       VARCHAR2(2000),
  ERROR_TYPE  VARCHAR2(32),
  RULE_CATEGORY  VARCHAR2(32),
  RULE_SUBCATEGORY VARCHAR2(32),
  OBJECT_TYPE      VARCHAR2(32),
  ATTRIBUTE_NAME   VARCHAR2(32),
  OBJECT_ID_SOURCE     VARCHAR2(200) NOT NULL,
  DAYTIME_SOURCE        VARCHAR2(200),
  ALT_UNIQUE_KEY_SOURCE  VARCHAR2(200),
  SQL_FLD_1_SOURCE   VARCHAR2(200),
  SQL_FLD_2_SOURCE   VARCHAR2(200),
  SQL_FLD_3_SOURCE   VARCHAR2(200),
  SQL_FLD_4_SOURCE   VARCHAR2(200),
  SQL_FLD_5_SOURCE   VARCHAR2(200),
  FROM_SQL       VARCHAR2(2000),
  ADDNL_INFO        VARCHAR(500),
  RESULT_RETENTION_DAYS NUMBER,
  APP_ID	NUMBER,
  ROLE_ID        VARCHAR2(30),
  SCREEN_COMPONENT_ID  VARCHAR2(30),
  LOGGING_LEVEL  VARCHAR2(32),
  TEXT_1         VARCHAR2(240),
  TEXT_2         VARCHAR2(240),
  TEXT_3         VARCHAR2(240),
  TEXT_4         VARCHAR2(240),
  TEXT_5         VARCHAR2(240),
  TEXT_6         VARCHAR2(240),
  TEXT_7         VARCHAR2(240),
  TEXT_8         VARCHAR2(240),
  TEXT_9         VARCHAR2(240),
  TEXT_10         VARCHAR2(240),
  VALUE_1         NUMBER,
  VALUE_2         NUMBER,
  VALUE_3         NUMBER,
  VALUE_4         NUMBER,
  VALUE_5         NUMBER,
  DATE_1          DATE,
  DATE_2          DATE,
  DATE_3          DATE,
  DATE_4          DATE,
  DATE_5          DATE,
  RECORD_STATUS VARCHAR2(1),
  CREATED_BY     VARCHAR2(30),
  CREATED_DATE   DATE,
  LAST_UPDATED_BY VARCHAR2(30),
  LAST_UPDATED_DATE DATE,
  REV_NO    NUMBER,
  REV_TEXT   VARCHAR2(240)
)
 INITRANS 1
 MAXTRANS 255
 PCTUSED 40
 PCTFREE 40
 STORAGE
 (
   PCTINCREASE 20
   INITIAL 1048576
   NEXT 1048576
   MAXEXTENTS 240
 )
 TABLESPACE &&ts_data
 NOCACHE
/

CREATE UNIQUE INDEX CT_DQ_RULE_PK ON CT_DQ_RULE
(RULE_ID)
LOGGING
TABLESPACE &&ts_index
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE CT_DQ_RULE ADD (
  CONSTRAINT CT_DQ_RULE_PK
 PRIMARY KEY
 (RULE_ID)
    USING INDEX 
    TABLESPACE &&ts_index
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          1M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

