create table CT_DQ_RULE_RUN_DETAIL_LOG
( RUN_ID        INTEGER NOT NULL,
  RULE_ID   INTEGER NOT NULL,
  LOG_OBJECT_ID   VARCHAR2(32) NOT NULL,
  LOGGING_LEVEL  VARCHAR2(32),
  TOTAL_ERRORS   INTEGER,
  TOTAL_NEW_ERRORS   INTEGER,
  TOTAL_OLD_ERRORS   INTEGER,
  TOTAL_DELETED_ERRORS INTEGER,
  TOTAL_ROLLED_ERRORS INTEGER,
  RECORD_STATUS VARCHAR2(1),
  CREATED_BY     VARCHAR2(30),
  CREATED_DATE   DATE,
  LAST_UPDATED_BY VARCHAR2(30),
  LAST_UPDATED_DATE DATE,
  REV_NO    NUMBER,
  REV_TEXT   VARCHAR2(240)
)
 INITRANS 1
 MAXTRANS 255
 PCTUSED 40
 PCTFREE 40
 STORAGE
 (
   PCTINCREASE 20
   INITIAL 1048576
   NEXT 1048576
   MAXEXTENTS 240
 )
 TABLESPACE &&ts_data
 NOCACHE
/

CREATE UNIQUE INDEX CT_DQ_RULE_RUN_DETAIL_LOG_PK ON CT_DQ_RULE_RUN_DETAIL_LOG
(RUN_ID, RULE_ID, LOG_OBJECT_ID)
LOGGING
TABLESPACE &&ts_index
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE CT_DQ_RULE_RUN_DETAIL_LOG ADD (
  CONSTRAINT CT_DQ_RULE_RUN_DETAIL_LOG_PK
 PRIMARY KEY
(RUN_ID, RULE_ID, LOG_OBJECT_ID)
    USING INDEX 
    TABLESPACE &&ts_index
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          1M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
