create table CT_DQ_RULE_GRP_COMBINATION
( RULE_GROUP_ID    INTEGER NOT NULL,
  RULE_ID          INTEGER NOT NULL,
  RECORD_STATUS VARCHAR2(1),
  CREATED_BY     VARCHAR2(30),
  CREATED_DATE   DATE,
  LAST_UPDATED_BY VARCHAR2(30),
  LAST_UPDATED_DATE DATE,
  REV_NO    NUMBER,
  REV_TEXT   VARCHAR2(240)
)
 INITRANS 1
 MAXTRANS 255
 PCTUSED 40
 PCTFREE 40
 STORAGE
 (
   PCTINCREASE 20
   INITIAL 1048576
   NEXT 1048576
   MAXEXTENTS 240
 )
 TABLESPACE &&ts_data
 NOCACHE
/


ALTER TABLE CT_DQ_RULE_GRP_COMBINATION ADD (
  CONSTRAINT CT_DQ_RULE_GRP_COMBO_PK
 PRIMARY KEY
 (RULE_GROUP_ID, RULE_ID)
    USING INDEX 
    TABLESPACE &&ts_index
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          1M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


ALTER TABLE CT_DQ_RULE_GRP_COMBINATION ADD (
  CONSTRAINT FK_CT_DQ_RULE_GRP_COMBO_1 
 FOREIGN KEY (RULE_ID) 
 REFERENCES CT_DQ_RULE (RULE_ID));


ALTER TABLE CT_DQ_RULE_GRP_COMBINATION ADD (
  CONSTRAINT FK_CT_DQ_RULE_GRP_COMBO_2 
 FOREIGN KEY (RULE_GROUP_ID) 
 REFERENCES CT_DQ_RULE_GROUP (RULE_GROUP_ID));