-- Delete Variable 
DECLARE
BEGIN
    ecdp_calc_mapping.deleteVariable(EcDp_Objects.GetObjIDFromCode('CALC_CONTEXT', 'EC_PROD'), 'OnStrmHrs[ALLOC_NODE,DAY]');
    ecdp_calc_mapping.deleteVariable(EcDp_Objects.GetObjIDFromCode('CALC_CONTEXT', 'EC_PROD'), 'OnStrmHrs[ALLOC_NODE,DAY,LITERAL(INJECTION_TYPE)]');
    ecdp_calc_mapping.deleteVariable(EcDp_Objects.GetObjIDFromCode('CALC_CONTEXT', 'EC_PROD'), 'OnStrmDays[ALLOC_NODE,MTH]');
    ecdp_calc_mapping.deleteVariable(EcDp_Objects.GetObjIDFromCode('CALC_CONTEXT', 'EC_PROD'), 'OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]');
    ecdp_calc_mapping.deleteVariable(EcDp_Objects.GetObjIDFromCode('CALC_CONTEXT', 'EC_PROD'), 'Opr_OnStrmDays[ALLOC_NODE,MTH]');
    ecdp_calc_mapping.deleteVariable(EcDp_Objects.GetObjIDFromCode('CALC_CONTEXT', 'EC_PROD'), 'Opr_OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]');
END;
/
 
-- Insert Variable
-- OnStrmHrs Prod

-- Load CALC_VARIABLE (CALC_VARIABLE)
BEGIN
   insert into CALC_VARIABLE (OBJECT_ID,CALC_VAR_SIGNATURE,NAME,DIM1_OBJECT_TYPE_CODE,DIM2_OBJECT_TYPE_CODE,DIM3_OBJECT_TYPE_CODE,DIM4_OBJECT_TYPE_CODE,DIM5_OBJECT_TYPE_CODE,CALC_VAR_DATA_TYPE,ACTIVE_IND,DESCRIPTION,DEFAULT_PRECISION,CALC_OBJECT_TYPE_CODE,ADVANCED_IND,ALIAS_IND,ALIAS_CLASS_NAME,ALIAS_SQL_SYNTAX)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY]','OnStrmHrs','ALLOC_NODE','DAY',NULL,NULL,NULL,'NUMBER','Y',NULL,2,NULL,NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_READ_MAPPING (CALC_VAR_READ_MAPPING)
BEGIN
   insert into CALC_VAR_READ_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DATE_HANDLING,VALID_FROM_ATTR_NAME,VALID_TO_ATTR_NAME,SUB_DAILY_IND,PROD_DAY_ATTR_NAME,SUMMER_TIME_ATTR_NAME,TO_PROD_DAY_ATTR_NAME,TO_SUMMER_TIME_ATTR_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY]','DEFAULT','PWEL_DAY_DATA','ON_STRM_HRS','FIXED_INTERVALS','DAYTIME',NULL,'N',NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_KEY_RD_MAPPING (CALC_VAR_KEY_READ_MAPPING)
BEGIN
   insert into CALC_VAR_KEY_READ_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY]','DEFAULT','PWEL_DAY_DATA','DAYTIME','DIMENSION',2,NULL,'2',NULL,NULL);

   insert into CALC_VAR_KEY_READ_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY]','DEFAULT','PWEL_DAY_DATA','OBJECT_ID','DIMENSION',1,NULL,'1',NULL,NULL);

END;
/

-- OnStrmHrs Inj

-- Load CALC_VARIABLE (CALC_VARIABLE)
BEGIN
   insert into CALC_VARIABLE (OBJECT_ID,CALC_VAR_SIGNATURE,NAME,DIM1_OBJECT_TYPE_CODE,DIM2_OBJECT_TYPE_CODE,DIM3_OBJECT_TYPE_CODE,DIM4_OBJECT_TYPE_CODE,DIM5_OBJECT_TYPE_CODE,CALC_VAR_DATA_TYPE,ACTIVE_IND,DESCRIPTION,DEFAULT_PRECISION,CALC_OBJECT_TYPE_CODE,ADVANCED_IND,ALIAS_IND,ALIAS_CLASS_NAME,ALIAS_SQL_SYNTAX)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY,LITERAL(INJECTION_TYPE)]','OnStrmHrs','ALLOC_NODE','DAY','LITERAL(INJECTION_TYPE)',NULL,NULL,'NUMBER','Y',NULL,2,NULL,NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_READ_MAPPING (CALC_VAR_READ_MAPPING)
BEGIN
   insert into CALC_VAR_READ_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DATE_HANDLING,VALID_FROM_ATTR_NAME,VALID_TO_ATTR_NAME,SUB_DAILY_IND,PROD_DAY_ATTR_NAME,SUMMER_TIME_ATTR_NAME,TO_PROD_DAY_ATTR_NAME,TO_SUMMER_TIME_ATTR_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_DAY_DATA','ON_STREAM_HRS','FIXED_INTERVALS','DAYTIME',NULL,'N',NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_KEY_RD_MAPPING (CALC_VAR_KEY_READ_MAPPING)
BEGIN
   insert into CALC_VAR_KEY_READ_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_DAY_DATA','DAYTIME','DIMENSION',2,NULL,'2',NULL,NULL);

   insert into CALC_VAR_KEY_READ_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_DAY_DATA','INJ_TYPE','DIMENSION',3,NULL,'3',NULL,NULL);

   insert into CALC_VAR_KEY_READ_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmHrs[ALLOC_NODE,DAY,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_DAY_DATA','OBJECT_ID','DIMENSION',1,NULL,'1',NULL,NULL);

END;
/

-- OnStrmDays Prod

-- Load CALC_VARIABLE (CALC_VARIABLE)
BEGIN
   insert into CALC_VARIABLE (OBJECT_ID,CALC_VAR_SIGNATURE,NAME,DIM1_OBJECT_TYPE_CODE,DIM2_OBJECT_TYPE_CODE,DIM3_OBJECT_TYPE_CODE,DIM4_OBJECT_TYPE_CODE,DIM5_OBJECT_TYPE_CODE,CALC_VAR_DATA_TYPE,ACTIVE_IND,DESCRIPTION,DEFAULT_PRECISION,CALC_OBJECT_TYPE_CODE,ADVANCED_IND,ALIAS_IND,ALIAS_CLASS_NAME,ALIAS_SQL_SYNTAX)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH]','OnStrmDays','ALLOC_NODE','MTH',NULL,NULL,NULL,'NUMBER','Y',NULL,2,NULL,NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_WRITE_MAPPING (CALC_VAR_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,ALWAYS_INSERT_IND,DIM3_TRIGGER_IND,DIM4_TRIGGER_IND,DIM5_TRIGGER_IND,SUB_DAILY_IND,PROD_DAY_ATTR_NAME,SUMMER_TIME_ATTR_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH]','DEFAULT','PWEL_MTH_ALLOC','PROD_DAYS',NULL,NULL,NULL,NULL,'N',NULL,NULL);

END;
/

-- Load CALC_VAR_KEY_WR_MAPPING (CALC_VAR_KEY_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH]','DEFAULT','PWEL_MTH_ALLOC','DAYTIME','DIMENSION',2,NULL,'2',NULL,NULL);

   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH]','DEFAULT','PWEL_MTH_ALLOC','OBJECT_ID','DIMENSION',1,NULL,'1',NULL,NULL);

END;
/

-- OnStrmDays Inj

-- Load CALC_VARIABLE (CALC_VARIABLE)
BEGIN
   insert into CALC_VARIABLE (OBJECT_ID,CALC_VAR_SIGNATURE,NAME,DIM1_OBJECT_TYPE_CODE,DIM2_OBJECT_TYPE_CODE,DIM3_OBJECT_TYPE_CODE,DIM4_OBJECT_TYPE_CODE,DIM5_OBJECT_TYPE_CODE,CALC_VAR_DATA_TYPE,ACTIVE_IND,DESCRIPTION,DEFAULT_PRECISION,CALC_OBJECT_TYPE_CODE,ADVANCED_IND,ALIAS_IND,ALIAS_CLASS_NAME,ALIAS_SQL_SYNTAX)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','OnStrmDays','ALLOC_NODE','MTH','LITERAL(INJECTION_TYPE)',NULL,NULL,'NUMBER','Y',NULL,2,NULL,NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_WRITE_MAPPING (CALC_VAR_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,ALWAYS_INSERT_IND,DIM3_TRIGGER_IND,DIM4_TRIGGER_IND,DIM5_TRIGGER_IND,SUB_DAILY_IND,PROD_DAY_ATTR_NAME,SUMMER_TIME_ATTR_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','INJ_DAYS',NULL,NULL,NULL,NULL,'N',NULL,NULL);

END;
/

-- Load CALC_VAR_KEY_WR_MAPPING (CALC_VAR_KEY_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','DAYTIME','DIMENSION',2,NULL,'2',NULL,NULL);

   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','INJ_TYPE','DIMENSION',3,NULL,'3',NULL,NULL);

   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','OBJECT_ID','DIMENSION',1,NULL,'1',NULL,NULL);

END;
/

-- Opr_OnStrmDays Prod

-- Load CALC_VARIABLE (CALC_VARIABLE)
BEGIN
   insert into CALC_VARIABLE (OBJECT_ID,CALC_VAR_SIGNATURE,NAME,DIM1_OBJECT_TYPE_CODE,DIM2_OBJECT_TYPE_CODE,DIM3_OBJECT_TYPE_CODE,DIM4_OBJECT_TYPE_CODE,DIM5_OBJECT_TYPE_CODE,CALC_VAR_DATA_TYPE,ACTIVE_IND,DESCRIPTION,DEFAULT_PRECISION,CALC_OBJECT_TYPE_CODE,ADVANCED_IND,ALIAS_IND,ALIAS_CLASS_NAME,ALIAS_SQL_SYNTAX)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH]','Opr_OnStrmDays','ALLOC_NODE','MTH',NULL,NULL,NULL,'NUMBER','Y',NULL,3,NULL,NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_WRITE_MAPPING (CALC_VAR_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,ALWAYS_INSERT_IND,DIM3_TRIGGER_IND,DIM4_TRIGGER_IND,DIM5_TRIGGER_IND,SUB_DAILY_IND,PROD_DAY_ATTR_NAME,SUMMER_TIME_ATTR_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH]','DEFAULT','PWEL_MTH_ALLOC','OPERATING_DAYS',NULL,NULL,NULL,NULL,'N',NULL,NULL);

END;
/

-- Load CALC_VAR_KEY_WR_MAPPING (CALC_VAR_KEY_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH]','DEFAULT','PWEL_MTH_ALLOC','DAYTIME','DIMENSION',2,NULL,'2',NULL,NULL);

   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH]','DEFAULT','PWEL_MTH_ALLOC','OBJECT_ID','DIMENSION',1,NULL,'1',NULL,NULL);

END;
/

-- Opr_OnStrmDays Inj

-- Load CALC_VARIABLE (CALC_VARIABLE)
BEGIN
   insert into CALC_VARIABLE (OBJECT_ID,CALC_VAR_SIGNATURE,NAME,DIM1_OBJECT_TYPE_CODE,DIM2_OBJECT_TYPE_CODE,DIM3_OBJECT_TYPE_CODE,DIM4_OBJECT_TYPE_CODE,DIM5_OBJECT_TYPE_CODE,CALC_VAR_DATA_TYPE,ACTIVE_IND,DESCRIPTION,DEFAULT_PRECISION,CALC_OBJECT_TYPE_CODE,ADVANCED_IND,ALIAS_IND,ALIAS_CLASS_NAME,ALIAS_SQL_SYNTAX)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','Opr_OnStrmDays','ALLOC_NODE','MTH','LITERAL(INJECTION_TYPE)',NULL,NULL,'NUMBER','Y',NULL,3,NULL,NULL,NULL,NULL,NULL);

END;
/

-- Load CALC_VAR_WRITE_MAPPING (CALC_VAR_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,ALWAYS_INSERT_IND,DIM3_TRIGGER_IND,DIM4_TRIGGER_IND,DIM5_TRIGGER_IND,SUB_DAILY_IND,PROD_DAY_ATTR_NAME,SUMMER_TIME_ATTR_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','OPERATING_DAYS',NULL,NULL,NULL,NULL,'N',NULL,NULL);

END;
/

-- Load CALC_VAR_KEY_WR_MAPPING (CALC_VAR_KEY_WRITE_MAPPING)
BEGIN
   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','DAYTIME','DIMENSION',2,NULL,'2',NULL,NULL);

   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','INJ_TYPE','DIMENSION',3,NULL,'3',NULL,NULL);

   insert into CALC_VAR_KEY_WRITE_MAPPING (OBJECT_ID,CALC_VAR_SIGNATURE,CALC_DATASET,CLS_NAME,SQL_SYNTAX,CALC_DIM_MAPPING_CODE,DIM_NO,PARAMETER_NAME,MAPPING_DETAIL,ALIAS_CLASS_NAME,ALIAS_ATTRIBUTE_NAME)
   values (EcDp_Objects.getObjIdFromCode('CALC_CONTEXT','EC_PROD'),'Opr_OnStrmDays[ALLOC_NODE,MTH,LITERAL(INJECTION_TYPE)]','DEFAULT','IWEL_MTH_ALLOC','OBJECT_ID','DIMENSION',1,NULL,'1',NULL,NULL);

END;
/
