UPDATE CLASS_ATTRIBUTE_CNFG SET REFERENCE_KEY=NULL,REFERENCE_TYPE=NULL,REFERENCE_VALUE=NULL
where class_name='DEMURRAGE' AND ATTRIBUTE_NAME IN ('LAYTIME_START_BOUNDARY','LAYTIME_END_BOUNDARY');

Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_START_BOUNDARY','PopupDependency',2500,'/EC','STATIC_PRESENTATION','Screen.this.currentRow.LAYTIME_START_BOUNDARY=ReturnField.CODE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_START_BOUNDARY','PopupLayout',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/layout/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_START_BOUNDARY','PopupQueryURL',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/query/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_START_BOUNDARY','PopupReturnColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TEXT');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_START_BOUNDARY','PopupWhereColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TYPE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_START_BOUNDARY','PopupWhereOperator',2500,'/EC','STATIC_PRESENTATION','=');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_START_BOUNDARY','PopupWhereValue',2500,'/EC','STATIC_PRESENTATION','ACTIVITY_BOUNDARY');


Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_END_BOUNDARY','PopupDependency',2500,'/EC','STATIC_PRESENTATION','Screen.this.currentRow.LAYTIME_END_BOUNDARY=ReturnField.CODE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_END_BOUNDARY','PopupLayout',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/layout/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_END_BOUNDARY','PopupQueryURL',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/query/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_END_BOUNDARY','PopupReturnColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TEXT');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_END_BOUNDARY','PopupWhereColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TYPE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_END_BOUNDARY','PopupWhereOperator',2500,'/EC','STATIC_PRESENTATION','=');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE','LAYTIME_END_BOUNDARY','PopupWhereValue',2500,'/EC','STATIC_PRESENTATION','ACTIVITY_BOUNDARY');

update VIEWLAYER_DIRTY_LOG set dirty_ind='Y' where object_name in('DEMURRAGE');
COMMIT;
execute ecdp_viewlayer.buildviewlayer('DEMURRAGE');
execute ecdp_viewlayer.buildreportlayer('DEMURRAGE');

UPDATE CLASS_ATTRIBUTE_CNFG SET REFERENCE_KEY=NULL,REFERENCE_TYPE=NULL,REFERENCE_VALUE=NULL
where class_name='DEMURRAGE_UNLOAD' AND ATTRIBUTE_NAME IN ('LAYTIME_START_BOUNDARY','LAYTIME_END_BOUNDARY','STATUS');

Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_START_BOUNDARY','PopupDependency',2500,'/EC','STATIC_PRESENTATION','Screen.this.currentRow.LAYTIME_START_BOUNDARY=ReturnField.CODE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_START_BOUNDARY','PopupLayout',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/layout/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_START_BOUNDARY','PopupQueryURL',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/query/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_START_BOUNDARY','PopupReturnColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TEXT');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_START_BOUNDARY','PopupWhereColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TYPE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_START_BOUNDARY','PopupWhereOperator',2500,'/EC','STATIC_PRESENTATION','=');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_START_BOUNDARY','PopupWhereValue',2500,'/EC','STATIC_PRESENTATION','ACTIVITY_BOUNDARY');


Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_END_BOUNDARY','PopupDependency',2500,'/EC','STATIC_PRESENTATION','Screen.this.currentRow.LAYTIME_END_BOUNDARY=ReturnField.CODE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_END_BOUNDARY','PopupLayout',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/layout/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_END_BOUNDARY','PopupQueryURL',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/query/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_END_BOUNDARY','PopupReturnColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TEXT');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_END_BOUNDARY','PopupWhereColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TYPE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_END_BOUNDARY','PopupWhereOperator',2500,'/EC','STATIC_PRESENTATION','=');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','LAYTIME_END_BOUNDARY','PopupWhereValue',2500,'/EC','STATIC_PRESENTATION','ACTIVITY_BOUNDARY');

Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','STATUS','PopupDependency',2500,'/EC','STATIC_PRESENTATION','Screen.this.currentRow.STATUS=ReturnField.CODE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','STATUS','PopupLayout',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/layout/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','STATUS','PopupQueryURL',2500,'/EC','STATIC_PRESENTATION','/com.ec.frmw.co.screens/query/ec_code_popup.xml');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','STATUS','PopupReturnColumn',2500,'/EC','STATIC_PRESENTATION','1');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','STATUS','PopupWhereColumn',2500,'/EC','STATIC_PRESENTATION','CODE_TYPE');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','STATUS','PopupWhereOperator',2500,'/EC','STATIC_PRESENTATION','=');
Insert into CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME,ATTRIBUTE_NAME,PROPERTY_CODE,OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE) values ('DEMURRAGE_UNLOAD','STATUS','PopupWhereValue',2500,'/EC','STATIC_PRESENTATION','DEMURRAGE_CLAIM_STATUS');


update VIEWLAYER_DIRTY_LOG set dirty_ind='Y' where object_name in('DEMURRAGE_UNLOAD');
COMMIT;
execute ecdp_viewlayer.buildviewlayer('DEMURRAGE_UNLOAD');
execute ecdp_viewlayer.buildreportlayer('DEMURRAGE_UNLOAD');

