!!com.ec.upgrade.schema.dto.TableDTO
name: BPM_PROC_MONITOR_CONFIG_ATT
cnstPrimaryKey:
  columns:
  - MONITOR_CODE
  - TYPE
  - KEY
  - NAME
  name: PK_BPM_PROC_MONITOR_CONFIG_ATT
  type: PRIMARYKEY
  status: UNDEFINED
columns:
  APPROVAL_BY:
    columnName: APPROVAL_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '13'
  APPROVAL_DATE:
    columnName: APPROVAL_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '14'
  APPROVAL_STATE:
    columnName: APPROVAL_STATE
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '15'
  CREATED_BY:
    columnName: CREATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '7'
  CREATED_DATE:
    columnName: CREATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '8'
  KEY:
    columnName: KEY
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '2'
  LAST_UPDATED_BY:
    columnName: LAST_UPDATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '9'
  LAST_UPDATED_DATE:
    columnName: LAST_UPDATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '10'
  MONITOR_CODE:
    columnName: MONITOR_CODE
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '1'
  NAME:
    columnName: NAME
    typeName: VARCHAR2(64)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '4'
  RECORD_STATUS:
    columnName: RECORD_STATUS
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '6'
  REC_ID:
    columnName: REC_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '16'
  REV_NO:
    columnName: REV_NO
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '11'
  REV_TEXT:
    columnName: REV_TEXT
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '12'
  TYPE:
    columnName: TYPE
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '3'
  VALUE:
    columnName: VALUE
    typeName: VARCHAR2(512)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '5'
attributes:
  initialExtent: 65536
  iniTrans: 1
  minExtent: 1
  maxExtent: 2147483645
  maxTrans: 255
  nextExtent: 1048576
  pctFree: 10
  pctUsed: 0
  pctIncrease: 0
status: UNDEFINED
