!!com.ec.upgrade.schema.dto.TableDTO
name: PRODUCT_MEAS_SETUP
cnstPrimaryKey:
  columns:
  - PRODUCT_MEAS_NO
  name: PK_PRODUCT_MEAS_SETUP
  type: PRIMARYKEY
  status: UNDEFINED
columns:
  APPROVAL_BY:
    columnName: APPROVAL_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '34'
  APPROVAL_DATE:
    columnName: APPROVAL_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '35'
  APPROVAL_STATE:
    columnName: APPROVAL_STATE
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '36'
  BALANCE_QTY_TYPE:
    columnName: BALANCE_QTY_TYPE
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '11'
  BLMR_LIGHT_MAPPING:
    columnName: BLMR_LIGHT_MAPPING
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '10'
  CALC_IND:
    columnName: CALC_IND
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '5'
  CREATED_BY:
    columnName: CREATED_BY
    typeName: VARCHAR2(30)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '28'
  CREATED_DATE:
    columnName: CREATED_DATE
    typeName: DATE
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '29'
  ITEM_CODE:
    columnName: ITEM_CODE
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '3'
  LAST_UPDATED_BY:
    columnName: LAST_UPDATED_BY
    typeName: VARCHAR2(30)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '30'
  LAST_UPDATED_DATE:
    columnName: LAST_UPDATED_DATE
    typeName: DATE
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '31'
  LIFTING_EVENT:
    columnName: LIFTING_EVENT
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '4'
  NOM_UNIT_IND:
    columnName: NOM_UNIT_IND
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '6'
  NOM_UNIT_IND2:
    columnName: NOM_UNIT_IND2
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '7'
  NOM_UNIT_IND3:
    columnName: NOM_UNIT_IND3
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '8'
  OBJECT_ID:
    columnName: OBJECT_ID
    typeName: VARCHAR2(32)
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '2'
  PRODUCT_MEAS_NO:
    columnName: PRODUCT_MEAS_NO
    typeName: NUMBER
    nullable: 'NO'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '1'
  RECORD_STATUS:
    columnName: RECORD_STATUS
    typeName: VARCHAR2(1)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '27'
  REC_ID:
    columnName: REC_ID
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '37'
  REV_NO:
    columnName: REV_NO
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '32'
  REV_QTY_MAPPING:
    columnName: REV_QTY_MAPPING
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '9'
  REV_TEXT:
    columnName: REV_TEXT
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '33'
  SORT_ORDER:
    columnName: SORT_ORDER
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '26'
  TEXT_1:
    columnName: TEXT_1
    typeName: VARCHAR2(16)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '22'
  TEXT_2:
    columnName: TEXT_2
    typeName: VARCHAR2(32)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '23'
  TEXT_3:
    columnName: TEXT_3
    typeName: VARCHAR2(240)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '24'
  TEXT_4:
    columnName: TEXT_4
    typeName: VARCHAR2(2000)
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '25'
  VALUE_1:
    columnName: VALUE_1
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '12'
  VALUE_10:
    columnName: VALUE_10
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '21'
  VALUE_2:
    columnName: VALUE_2
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '13'
  VALUE_3:
    columnName: VALUE_3
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '14'
  VALUE_4:
    columnName: VALUE_4
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '15'
  VALUE_5:
    columnName: VALUE_5
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '16'
  VALUE_6:
    columnName: VALUE_6
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '17'
  VALUE_7:
    columnName: VALUE_7
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '18'
  VALUE_8:
    columnName: VALUE_8
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '19'
  VALUE_9:
    columnName: VALUE_9
    typeName: NUMBER
    nullable: 'YES'
    isGenerated: UNKNOWN
    isAutoIncrement: UNKNOWN
    status: UNDEFINED
    sequence: !!float '20'
cnstUniqueKeys:
  UK_PRODUCT_MEAS_SETUP_1:
    columns:
    - OBJECT_ID
    - ITEM_CODE
    - LIFTING_EVENT
    name: UK_PRODUCT_MEAS_SETUP_1
    type: UNIQUEKEY
    status: UNDEFINED
cnstForeignKeys:
  FK_PRODUCT_MEAS_SETUP_1:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: PRODUCT
    columns:
      OBJECT_ID: OBJECT_ID
    name: FK_PRODUCT_MEAS_SETUP_1
    type: FOREIGNKEY
    status: UNDEFINED
  FK_PRODUCT_MEAS_SETUP_2:
    updateAction: UNKNOWN
    deleteAction: NOACTION
    primaryTable: LIFTING_MEASUREMENT_ITEM
    columns:
      ITEM_CODE: ITEM_CODE
    name: FK_PRODUCT_MEAS_SETUP_2
    type: FOREIGNKEY
    status: UNDEFINED
cnstChecks:
  CHK_PRODUCT_MEAS_SETUP_1:
    searchCondition: APPROVAL_STATE IS NULL OR APPROVAL_STATE IN ('N','O','U','D')
    columns:
    - APPROVAL_STATE
    name: CHK_PRODUCT_MEAS_SETUP_1
    type: CHECK
    status: UNDEFINED
indexes:
  IFK_PRODUCT_MEAS_SETUP_2:
    indexName: IFK_PRODUCT_MEAS_SETUP_2
    columns:
    - ITEM_CODE
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
  IR_PRODUCT_MEAS_SETUP:
    indexName: IR_PRODUCT_MEAS_SETUP
    columns:
    - REC_ID
    isUnique: NONUNIQUE
    isCompressed: DISABLED
    initialExtent: 65536
    nextExtent: 65536
    minExtent: 1
    maxExtent: 2147483645
    pctFree: 50
    pctIncrease: 0
    indexStatus: VALID
    isPartitioned: 'NO'
    isGenerated: 'NO'
    descend: ASC
    type: NORMAL
    status: UNDEFINED
attributes:
  initialExtent: 65536
  iniTrans: 1
  minExtent: 1
  maxExtent: 2147483645
  maxTrans: 255
  nextExtent: 65536
  pctFree: 10
  pctUsed: 0
  pctIncrease: 0
status: UNDEFINED
