CREATE OR REPLACE PACKAGE ec_class_attr_db_mapping IS
------------------------------------------------------------------------------------
-- Package: ec_class_attr_db_mapping
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION db_mapping_type(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.DB_MAPPING_TYPE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION db_sql_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.DB_SQL_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION sort_order(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.SORT_ORDER%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_DB_MAPPING%ROWTYPE;

END ec_class_attr_db_mapping;