CREATE OR REPLACE PACKAGE ec_class_attr_validation IS
------------------------------------------------------------------------------------
-- Package: ec_class_attr_validation
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION prev_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION prev_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION next_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION next_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION row_by_rel_operator(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION%ROWTYPE ;
------------------------------------------------------------------------------------
FUNCTION end_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.END_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION warn_min(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.WARN_MIN%TYPE ;
------------------------------------------------------------------------------------
FUNCTION warn_max(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.WARN_MAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION warn_pct(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.WARN_PCT%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_conditional_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_CONDITIONAL_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_min(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_MIN%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_max(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_MAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_mandatory_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_MANDATORY_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION req_event(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.REQ_EVENT%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION%ROWTYPE;

END ec_class_attr_validation;