CREATE OR REPLACE PACKAGE ec_class_attribute IS
------------------------------------------------------------------------------------
-- Package: ec_class_attribute
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION name(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.NAME%TYPE ;
------------------------------------------------------------------------------------
FUNCTION is_key(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.IS_KEY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION is_mandatory(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.IS_MANDATORY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION context_code(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.CONTEXT_CODE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION data_type(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.DATA_TYPE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION calc_mapping_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.CALC_MAPPING_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION precision(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.PRECISION%TYPE ;
------------------------------------------------------------------------------------
FUNCTION default_value(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.DEFAULT_VALUE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION default_client_value(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.DEFAULT_CLIENT_VALUE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION disabled_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.DISABLED_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION disabled_calc_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.DISABLED_CALC_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION report_only_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.REPORT_ONLY_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION description(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.DESCRIPTION%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTRIBUTE%ROWTYPE;

END ec_class_attribute;