CREATE OR REPLACE PACKAGE EcDp_Import IS
  ------------------------------------------------------------------------------------
  -- Package body: EcDp_Import
  -- Generated by ROUHAMAJ

  ------------------------------------------------------------------------------------
  PROCEDURE Import_Data(p_interface_code VARCHAR2,
                        p_file_name      VARCHAR2,
                        p_daytime        VARCHAR2,
                        p_user_id        VARCHAR2);

  PROCEDURE Validate_Mapping(p_interface_code VARCHAR2,
                             p_path_origin    VARCHAR2,
                             p_key_1          VARCHAR2,
                             p_key_2          VARCHAR2,
                             p_key_3          VARCHAR2,
                             p_key_4          VARCHAR2,
                             p_key_5          VARCHAR2);

  PROCEDURE UpdateFileStatus(p_interface_code VARCHAR2,
                             p_file_name      VARCHAR2,
                             p_status         VARCHAR2);

  PROCEDURE UpdateFileStatusForced(p_interface_code VARCHAR2,
                             p_file_name      VARCHAR2,
                             p_status         VARCHAR2);

  FUNCTION get_source_type(p_interface_code VARCHAR2) RETURN VARCHAR2;

  FUNCTION isEditableConf(p_interface_code VARCHAR2
      ,p_source_mapping_no NUMBER DEFAULT NULL
      ) RETURN VARCHAR2;

  PROCEDURE Delete_Staging_Data(p_interface_code VARCHAR2,
                             p_user_name      VARCHAR2);

  PROCEDURE Delete_File(p_interface_code VARCHAR2,
                             p_file_name      VARCHAR2,
                             p_file_no        VARCHAR2);

END EcDp_Import;