UPDATE class_attribute_cnfg 
set db_sql_syntax ='nvl(STORAGE_LIFT_NOMINATION.DATE_3,START_LIFTING_DATE - UE_CT_LEADTIME.calc_ETA_LT(STORAGE_LIFT_NOMINATION.OBJECT_ID,STORAGE_LIFT_NOMINATION.PARCEL_NO,NULL,''STOR''))'
Where class_name = 'STORAGE_LIFT_NOMINATION'
and attribute_name = 'ETA';

UPDATE class_attribute_cnfg 
set db_sql_syntax =
'DECODE (ECDP_OBJECTS.GETOBJCODE (STORAGE_LIFT_NOMINATION.OBJECT_ID),''STW_COND'', NVL(STORAGE_LIFT_NOMINATION.DATE_8,TRUNC(nvl(STORAGE_LIFT_NOMINATION.DATE_3,START_LIFTING_DATE - UE_CT_LEADTIME.calc_ETA_LT(STORAGE_LIFT_NOMINATION.OBJECT_ID,STORAGE_LIFT_NOMINATION.PARCEL_NO,NULL,''STOR''))))+(1/(24*60)))'
Where class_name = 'STORAGE_LIFT_NOMINATION'
and attribute_name = 'LDR_START';

UPDATE viewlayer_dirty_log SET DIRTY_IND='Y' WHERE object_name in ('STORAGE_LIFT_NOMINATION');
commit;
EXECUTE EcDp_Viewlayer.BuildViewLayer('STORAGE_LIFT_NOMINATION') ;
EXECUTE EcDp_Viewlayer.BuildReportLayer('STORAGE_LIFT_NOMINATION');

commit;
 
