CREATE OR REPLACE TRIGGER "AUD_TRANS_MAPPING" 
AFTER UPDATE OR DELETE ON TRANS_MAPPING


BEGIN

DELETE from TRANS_SOURCE_TIME ST
WHERE NOT EXISTS (
          SELECT 1 FROM TRANS_MAPPING TM
          WHERE TM.Source_id = ST.source_id
          and   TM.TAG_ID = ST.TAG_ID);

END;

