--******************************************************************************************
--** SQL statements created by EC Configuration utility version 94003
--** Workbook source: G:\IS\Energy\Energy Components\Internal\Services\Chevron\temp upgrade\Class_Config-11_2 - CP.xls
--** Computer name  : WL310802
--** User name      : Agarwal Nikita
--** Date and time  : 1/17/2018 5:24:06 PM
--******************************************************************************************
set define off
--
--Extracting DELETE statements
--
--Extracting INSERT statements
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_AREA_ID', 'viewwidth', 2100, '/EC', 'STATIC_PRESENTATION', '200');
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_AREA_ID', 'vieweditable', 2100, '/EC', 'STATIC_PRESENTATION', 'false');
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_COL_POINT_ID', 'viewwidth', 2100, '/EC', 'STATIC_PRESENTATION', '200');
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_COL_POINT_ID', 'vieweditable', 2100, '/EC', 'STATIC_PRESENTATION', 'false');
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_OPERATOR_ROUTE_ID', 'viewwidth', 2100, '/EC', 'STATIC_PRESENTATION', '200');
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_OPERATOR_ROUTE_ID', 'vieweditable', 2100, '/EC', 'STATIC_PRESENTATION', 'false');
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_SUB_AREA_ID', 'viewwidth', 2100, '/EC', 'STATIC_PRESENTATION', '200');
INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE) VALUES ('CT_DQ_RULE_RESULTS', 'CP_SUB_AREA_ID', 'vieweditable', 2100, '/EC', 'STATIC_PRESENTATION', 'false');
--
--Extracting UPDATE statements
--
--
set define on