OS_EXTRACT_AMT: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '-806998289'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_EXTRACT_AMT' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_EXTRACT_QTY: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '-806982691'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_EXTRACT_QTY' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_BAL_QTY: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '992805234'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_BAL_QTY' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_BAL_QTY_PS: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '1516019696'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_BAL_QTY_PS' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_BAL_VAL: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '992809437'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_BAL_VAL' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_BAL_VAL_PS: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '1641231269'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_BAL_VAL_PS' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_QTY: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '840619972'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_QTY' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_QTY_PS: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '-1044623266'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_QTY_PS' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_VALUE: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '385983231'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_VALUE' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
OS_TRANS_VALUE_PS: !!com.ec.upgrade.ecconfig.model.ConfigurationItemGroupExtended
  fileName: '1199077187'
  keys:
    OBJECT_ID: (SELECT O.OBJECT_ID FROM OBJECTS O WHERE (O.CLASS_NAME='CONFIG_VARIABLE' OR O.CLASS_NAME IN (SELECT CHILD_CLASS FROM CLASS_DEPENDENCY_CNFG WHERE PARENT_CLASS ='CONFIG_VARIABLE' AND DEPENDENCY_TYPE = 'IMPLEMENTS')) AND O.CODE ='OS_TRANS_VALUE_PS' AND ROWNUM < 2)
    T: CONFIG_VARIABLE
  parentKeys: {}
  properties: {}
  related: {}
  status: ADDED
