CREATE OR REPLACE PACKAGE ec_class_attr_presentation IS
------------------------------------------------------------------------------------
-- Package: ec_class_attr_presentation
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION presentation_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.PRESENTATION_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION static_presentation_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.STATIC_PRESENTATION_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION db_pres_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.DB_PRES_SYNTAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION sort_order(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.SORT_ORDER%TYPE ;
------------------------------------------------------------------------------------
FUNCTION label_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.LABEL_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION label(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.LABEL%TYPE ;
------------------------------------------------------------------------------------
FUNCTION uom_code(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.UOM_CODE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2) RETURN CLASS_ATTR_PRESENTATION%ROWTYPE;

END ec_class_attr_presentation;
/
CREATE OR REPLACE PACKAGE BODY ec_class_attr_presentation IS
------------------------------------------------------------------------------------
-- Package body: ec_class_attr_presentation
-- Generated by EC_GENERATE.
------------------------------------------------------------------------------------















------------------------------------------------------------------------------------
FUNCTION presentation_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.PRESENTATION_SYNTAX%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.PRESENTATION_SYNTAX%TYPE ;
   CURSOR c_col_val IS
   SELECT presentation_syntax col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END presentation_syntax;

------------------------------------------------------------------------------------
FUNCTION static_presentation_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.STATIC_PRESENTATION_SYNTAX%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.STATIC_PRESENTATION_SYNTAX%TYPE ;
   CURSOR c_col_val IS
   SELECT static_presentation_syntax col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END static_presentation_syntax;

------------------------------------------------------------------------------------
FUNCTION db_pres_syntax(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.DB_PRES_SYNTAX%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.DB_PRES_SYNTAX%TYPE ;
   CURSOR c_col_val IS
   SELECT db_pres_syntax col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END db_pres_syntax;

------------------------------------------------------------------------------------
FUNCTION sort_order(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.SORT_ORDER%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.SORT_ORDER%TYPE ;
   CURSOR c_col_val IS
   SELECT sort_order col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END sort_order;

------------------------------------------------------------------------------------
FUNCTION label_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.LABEL_ID%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.LABEL_ID%TYPE ;
   CURSOR c_col_val IS
   SELECT label_id col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END label_id;

------------------------------------------------------------------------------------
FUNCTION label(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.LABEL%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.LABEL%TYPE ;
   CURSOR c_col_val IS
   SELECT label col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END label;

------------------------------------------------------------------------------------
FUNCTION uom_code(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.UOM_CODE%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.UOM_CODE%TYPE ;
   CURSOR c_col_val IS
   SELECT uom_code col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END uom_code;

------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.RECORD_STATUS%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.RECORD_STATUS%TYPE ;
   CURSOR c_col_val IS
   SELECT record_status col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END record_status;

------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.APPROVAL_STATE%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.APPROVAL_STATE%TYPE ;
   CURSOR c_col_val IS
   SELECT approval_state col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END approval_state;

------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.APPROVAL_BY%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.APPROVAL_BY%TYPE ;
   CURSOR c_col_val IS
   SELECT approval_by col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END approval_by;

------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.APPROVAL_DATE%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.APPROVAL_DATE%TYPE ;
   CURSOR c_col_val IS
   SELECT approval_date col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END approval_date;

------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION.REC_ID%TYPE  IS
   v_return_val CLASS_ATTR_PRESENTATION.REC_ID%TYPE ;
   CURSOR c_col_val IS
   SELECT rec_id col
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_row IN c_col_val LOOP
      v_return_val := cur_row.col;
   END LOOP;
   RETURN v_return_val;
END rec_id;


------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2)
RETURN CLASS_ATTR_PRESENTATION%ROWTYPE IS
   v_return_rec CLASS_ATTR_PRESENTATION%ROWTYPE;
   CURSOR c_read_row IS
   SELECT *
   FROM CLASS_ATTR_PRESENTATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name;
BEGIN
   FOR cur_rec IN c_read_row LOOP
      v_return_rec := cur_rec;
   END LOOP;
   RETURN v_return_rec;
END row_by_pk;



END ec_class_attr_presentation;
/
