CREATE OR REPLACE PACKAGE ec_class_attr_validation IS
------------------------------------------------------------------------------------
-- Package: ec_class_attr_validation
-- Generated by EC_GENERATE.

-- DO NOT MODIFY THIS PACKAGE! Changes will be lost when the package is regenerated.
-- Packages named pck_<component> will hold all manual written common code.
-- Packages named <sysnam>_<component> will hold all code not beeing common.
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
FUNCTION prev_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION prev_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION next_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION next_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1) RETURN DATE;
------------------------------------------------------------------------------------
FUNCTION row_by_rel_operator(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION%ROWTYPE ;
------------------------------------------------------------------------------------
FUNCTION end_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.END_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION warn_min(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.WARN_MIN%TYPE ;
------------------------------------------------------------------------------------
FUNCTION warn_max(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.WARN_MAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION warn_pct(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.WARN_PCT%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_conditional_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_CONDITIONAL_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_min(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_MIN%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_max(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_MAX%TYPE ;
------------------------------------------------------------------------------------
FUNCTION err_mandatory_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.ERR_MANDATORY_IND%TYPE ;
------------------------------------------------------------------------------------
FUNCTION req_event(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.REQ_EVENT%TYPE ;
------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.RECORD_STATUS%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.APPROVAL_STATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.APPROVAL_BY%TYPE ;
------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.APPROVAL_DATE%TYPE ;
------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION.REC_ID%TYPE ;
------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=') RETURN CLASS_ATTR_VALIDATION%ROWTYPE;

END ec_class_attr_validation;
/
CREATE OR REPLACE PACKAGE BODY ec_class_attr_validation IS
------------------------------------------------------------------------------------
-- Package body: ec_class_attr_validation
-- Generated by EC_GENERATE.
------------------------------------------------------------------------------------


------------------------------------------------------------------------------------
CURSOR c_equal (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE) IS
SELECT *
FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime = p_daytime;

------------------------------------------------------------------------------------
CURSOR c_less_equal (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE) IS
SELECT *
FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime =
   (SELECT max(daytime)
   FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime <= p_daytime);

------------------------------------------------------------------------------------
CURSOR c_less (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE) IS
SELECT *
FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime =
   (SELECT max(daytime)
   FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime < p_daytime);

------------------------------------------------------------------------------------
CURSOR c_greater_equal (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE) IS
SELECT *
FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime =
   (SELECT min(daytime)
   FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime >= p_daytime);

------------------------------------------------------------------------------------
CURSOR c_greater (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE) IS
SELECT *
FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime =
   (SELECT min(daytime)
   FROM CLASS_ATTR_VALIDATION
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime > p_daytime);










------------------------------------------------------------------------------------
FUNCTION prev_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1)
RETURN DATE IS
CURSOR c_compute IS
SELECT daytime
FROM class_attr_validation
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime < p_daytime
ORDER BY daytime DESC;
ld_return_val DATE := NULL;
BEGIN
   IF p_num_rows >= 1 THEN
      FOR cur_rec IN c_compute LOOP
         ld_return_val := cur_rec.daytime;
         IF c_compute%ROWCOUNT = p_num_rows THEN
            EXIT;
         END IF;
      END LOOP;
   END IF;
   RETURN ld_return_val;
END prev_daytime;


------------------------------------------------------------------------------------
FUNCTION prev_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1)
RETURN DATE IS
CURSOR c_compute IS
SELECT daytime
FROM class_attr_validation
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime <= p_daytime
ORDER BY daytime DESC;
ld_return_val DATE := NULL;
BEGIN
   IF p_num_rows >= 1 THEN
      FOR cur_rec IN c_compute LOOP
         ld_return_val := cur_rec.daytime;
         IF c_compute%ROWCOUNT = p_num_rows THEN
            EXIT;
         END IF;
      END LOOP;
   END IF;
   RETURN ld_return_val;
END prev_equal_daytime;


------------------------------------------------------------------------------------
FUNCTION next_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1)
RETURN DATE IS
CURSOR c_compute IS
SELECT daytime
FROM class_attr_validation
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime > p_daytime
ORDER BY daytime ASC;
ld_return_val DATE := NULL;
BEGIN
   IF p_num_rows >= 1 THEN
      FOR cur_rec IN c_compute LOOP
         ld_return_val := cur_rec.daytime;
         IF c_compute%ROWCOUNT = p_num_rows THEN
            EXIT;
         END IF;
      END LOOP;
   END IF;
   RETURN ld_return_val;
END next_daytime;


------------------------------------------------------------------------------------
FUNCTION next_equal_daytime(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_num_rows NUMBER DEFAULT 1)
RETURN DATE IS
CURSOR c_compute IS
SELECT daytime
FROM class_attr_validation
WHERE class_name = p_class_name
AND attribute_name = p_attribute_name
AND daytime >= p_daytime
ORDER BY daytime ASC;
ld_return_val DATE := NULL;
BEGIN
   IF p_num_rows >= 1 THEN
      FOR cur_rec IN c_compute LOOP
         ld_return_val := cur_rec.daytime;
         IF c_compute%ROWCOUNT = p_num_rows THEN
            EXIT;
         END IF;
      END LOOP;
   END IF;
   RETURN ld_return_val;
END next_equal_daytime;


------------------------------------------------------------------------------------
FUNCTION row_by_rel_operator (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION%ROWTYPE  IS
   lr_return_rec CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   IF p_compare_oper = '=' THEN
      FOR cur_row IN c_equal(
         p_class_name,
         p_attribute_name,
         p_daytime) LOOP
         lr_return_rec := cur_row;
      END LOOP;
   ELSIF p_compare_oper IN ('<=','=<') THEN
      FOR cur_row IN c_less_equal(
         p_class_name,
         p_attribute_name,
         p_daytime) LOOP
         lr_return_rec := cur_row;
      END LOOP;
   ELSIF p_compare_oper = '<' THEN
      FOR cur_row IN c_less(
         p_class_name,
         p_attribute_name,
         p_daytime) LOOP
         lr_return_rec := cur_row;
      END LOOP;
   ELSIF p_compare_oper IN ('>=','=>') THEN
      FOR cur_row IN c_greater_equal(
         p_class_name,
         p_attribute_name,
         p_daytime) LOOP
         lr_return_rec := cur_row;
      END LOOP;
   ELSIF p_compare_oper = '>' THEN
      FOR cur_row IN c_greater(
         p_class_name,
         p_attribute_name,
         p_daytime) LOOP
         lr_return_rec := cur_row;
      END LOOP;
   END IF;
   RETURN lr_return_rec;
END row_by_rel_operator;

------------------------------------------------------------------------------------
FUNCTION end_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.END_DATE%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.end_date;
END end_date;

------------------------------------------------------------------------------------
FUNCTION warn_min(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.WARN_MIN%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.warn_min;
END warn_min;

------------------------------------------------------------------------------------
FUNCTION warn_max(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.WARN_MAX%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.warn_max;
END warn_max;

------------------------------------------------------------------------------------
FUNCTION warn_pct(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.WARN_PCT%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.warn_pct;
END warn_pct;

------------------------------------------------------------------------------------
FUNCTION err_conditional_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.ERR_CONDITIONAL_IND%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.err_conditional_ind;
END err_conditional_ind;

------------------------------------------------------------------------------------
FUNCTION err_min(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.ERR_MIN%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.err_min;
END err_min;

------------------------------------------------------------------------------------
FUNCTION err_max(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.ERR_MAX%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.err_max;
END err_max;

------------------------------------------------------------------------------------
FUNCTION err_mandatory_ind(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.ERR_MANDATORY_IND%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.err_mandatory_ind;
END err_mandatory_ind;

------------------------------------------------------------------------------------
FUNCTION req_event(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.REQ_EVENT%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.req_event;
END req_event;

------------------------------------------------------------------------------------
FUNCTION record_status(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.RECORD_STATUS%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.record_status;
END record_status;

------------------------------------------------------------------------------------
FUNCTION approval_state(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.APPROVAL_STATE%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.approval_state;
END approval_state;

------------------------------------------------------------------------------------
FUNCTION approval_by(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.APPROVAL_BY%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.approval_by;
END approval_by;

------------------------------------------------------------------------------------
FUNCTION approval_date(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.APPROVAL_DATE%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.approval_date;
END approval_date;

------------------------------------------------------------------------------------
FUNCTION rec_id(
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION.REC_ID%TYPE  IS
   lr_fields CLASS_ATTR_VALIDATION%ROWTYPE;
BEGIN
   lr_fields := row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
   RETURN lr_fields.rec_id;
END rec_id;


------------------------------------------------------------------------------------
FUNCTION row_by_pk (
         p_class_name VARCHAR2,
         p_attribute_name VARCHAR2,
         p_daytime DATE,
         p_compare_oper VARCHAR2 DEFAULT '=')
RETURN CLASS_ATTR_VALIDATION%ROWTYPE IS
BEGIN
   RETURN row_by_rel_operator(
         p_class_name,
         p_attribute_name,
         p_daytime, p_compare_oper);
END row_by_pk;


END ec_class_attr_validation;
/
