CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_DATA_RULE_VALUES" ("VALUE_CATEGORY", "TRG_CLASS_NAME", "MATCH_DATA_FILTER_ID", "VALUE", "DISPLAY_TEXT", "VALUE_TYPE", "RECORD_STATUS", "CREATED_BY", "CREATED_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "REV_NO", "REV_TEXT") AS 
  SELECT 'CLASS_ATTRIBUTE' AS VALUE_CATEGORY
      ,att.CLASS_NAME AS TRG_CLASS_NAME
      ,NULL AS MATCH_DATA_FILTER_ID
      ,att.ATTRIBUTE_NAME AS VALUE
      ,EcDp_ClassMeta_Cnfg.getLabel(att.class_name, att.attribute_name) AS DISPLAY_TEXT
      ,att.data_type AS VALUE_TYPE
      ,NULL AS RECORD_STATUS
      ,NULL AS CREATED_BY
      ,NULL AS CREATED_DATE
      ,NULL AS LAST_UPDATED_BY
      ,NULL AS LAST_UPDATED_DATE
      ,NULL AS REV_NO
      ,NULL AS REV_TEXT
FROM class_attribute_cnfg att
UNION ALL
SELECT 'PARAMETER' AS VALUE_CATEGORY
      ,NULL AS TRG_CLASS_NAME
      ,object_id AS MATCH_DATA_FILTER_ID
      ,param_name AS VALUE
      ,param_name AS DISPLAY_TEXT
      ,param_value_type AS value_type
      ,NULL AS RECORD_STATUS
      ,NULL AS CREATED_BY
      ,NULL AS CREATED_DATE
      ,NULL AS LAST_UPDATED_BY
      ,NULL AS LAST_UPDATED_DATE
      ,NULL AS REV_NO
      ,NULL AS REV_TEXT
FROM revn_data_filter_param
UNION ALL
SELECT DISTINCT DECODE(ol_ver.CLASS_NAME
             ,'EC_CODE_OBJECT'
             ,'EC_CODE_LIST'
             ,'OBJECT_LIST') AS VALUE_CATEGORY
      ,NULL AS TRG_CLASS_NAME
      ,NULL AS MATCH_DATA_FILTER_ID
      ,ol.object_code AS VALUE
      ,ol_ver.name AS VALUE
      ,'STRING' AS value_type
      ,NULL AS RECORD_STATUS
      ,NULL AS CREATED_BY
      ,NULL AS CREATED_DATE
      ,NULL AS LAST_UPDATED_BY
      ,NULL AS LAST_UPDATED_DATE
      ,NULL AS REV_NO
      ,NULL AS REV_TEXT
FROM OBJECT_LIST ol, OBJECT_LIST_VERSION ol_ver
WHERE ol.OBJECT_ID = ol_ver.OBJECT_ID