CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_TRACING_REPORT" ("HEADING", "PROCESS", "DATA_ENTITY_CAT", "SORT_ORDER", "DATA_ENTITY_DAYTIME", "PERIOD", "DATA_ENTITY_ID", "DATA_ENTITY_TYPE", "PROPERTY_OBJ_CODE", "PROPERTY_OBJ_ID", "PARENT_PROJECT_OBJ_CODE", "PARENT_PROJECT_OBJ_ID", "PROJECT_OBJ_CODE", "PROJECT_OBJ_ID", "DEP_STATUS", "BOX_TEXT_1", "BOX_TEXT_2", "BOX_TEXT_3", "BOX_TEXT_4", "BOX_TEXT_5", "BOX_TEXT_6", "BOX_TEXT_COLOR_1", "BOX_TEXT_COLOR_2", "BOX_TEXT_COLOR_3", "BOX_TEXT_COLOR_4", "BOX_TEXT_COLOR_5", "BOX_TEXT_COLOR_6", "TOP_TEXT_1", "TOP_TEXT_2", "TOP_TEXT_3", "TOP_TEXT_4", "TOP_TEXT_5", "TOP_TEXT_6", "TOP_TEXT_7", "TOP_TEXT_8", "TOP_TEXT_9", "TOP_TEXT_10", "TOP_TEXT_11", "TOP_TEXT_12", "TOP_TEXT_COLOR_1", "TOP_TEXT_COLOR_2", "TOP_TEXT_COLOR_3", "TOP_TEXT_COLOR_4", "TOP_TEXT_COLOR_5", "TOP_TEXT_COLOR_6", "TOP_TEXT_COLOR_7", "TOP_TEXT_COLOR_8", "TOP_TEXT_COLOR_9", "TOP_TEXT_COLOR_10", "TOP_TEXT_COLOR_11", "TOP_TEXT_COLOR_12", "BOTTOM_TEXT_1", "BOTTOM_TEXT_2", "BOTTOM_TEXT_3", "BOTTOM_TEXT_4", "BOTTOM_TEXT_5", "BOTTOM_TEXT_6", "BOTTOM_TEXT_7", "BOTTOM_TEXT_8", "BOTTOM_TEXT_9", "BOTTOM_TEXT_10", "BOTTOM_TEXT_11", "BOTTOM_TEXT_12", "BOTTOM_TEXT_COLOR_1", "BOTTOM_TEXT_COLOR_2", "BOTTOM_TEXT_COLOR_3", "BOTTOM_TEXT_COLOR_4", "BOTTOM_TEXT_COLOR_5", "BOTTOM_TEXT_COLOR_6", "BOTTOM_TEXT_COLOR_7", "BOTTOM_TEXT_COLOR_8", "BOTTOM_TEXT_COLOR_9", "BOTTOM_TEXT_COLOR_10", "BOTTOM_TEXT_COLOR_11", "BOTTOM_TEXT_COLOR_12", "ICON_1", "ICON_2", "ICON_3", "ICON_4", "ICON_5", "ACTUAL_ACCRUAL_CODE", "FORECAST_IND", "DEPRECATED_IND", "RECORD_STATUS", "CREATED_BY", "CREATED_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "REV_NO", "REV_TEXT", "APPROVAL_BY", "APPROVAL_DATE", "APPROVAL_STATE", "REC_ID") AS 
  select
  'Reports'                                                                                                                   as HEADING,
  null                                                                                                                        as PROCESS,
  'RRCA_REPORT'                                                                                                               as DATA_ENTITY_CAT,
  7                                                                                                                           as SORT_ORDER,
  x.daytime                                                                                                                   as DATA_ENTITY_DAYTIME,
  x.daytime                                                                                                                   as PERIOD,
  dfd.reference_id                                                                                                            as DATA_ENTITY_ID,
  dfd.type                                                                                                                    as DATA_ENTITY_TYPE,
  ec_contract_area.object_code(ec_contract_version.contract_area_id(x.OBJECT_ID,x.DAYTIME, '<=' ))                            as PROPERTY_OBJ_CODE,
  ec_contract_version.contract_area_id(x.OBJECT_ID,x.DAYTIME, '<=' )                                                          as PROPERTY_OBJ_ID,
  ec_contract.object_code(ec_contract_version.parent_contract_id(x.object_ID, x.DAYTIME, '<='))                               as PARENT_PROJECT_OBJ_CODE,
  ec_contract_version.parent_contract_id(x.object_ID, x.DAYTIME, '<=')                                                        as PARENT_PROJECT_OBJ_ID,
  ec_contract.object_code(x.object_id)                                                                                        as PROJECT_OBJ_CODE,
  x.object_id                                                                                                                 as PROJECT_OBJ_ID,
  ec_prosty_codes.code_text(nvl(ec_report.accept_status(x.report_no),'P'), 'TRACING_STATUS')                                  as DEP_STATUS,
  'Report ID: ' || to_char(x.report_no)                                                                                       as BOX_TEXT_1,
  'Project: '|| ec_contract_version.name(x.object_id , x.daytime, '<=')                                                       as BOX_TEXT_2,
  'Report: '|| ec_report.report_runable_name(x.report_no)                                                                     as BOX_TEXT_3,
  'Created by: '|| nvl(ec_t_basis_user.given_name(x.created_by),x.created_by) ||' '|| ec_t_basis_user.surname(x.created_by)   as BOX_TEXT_4,
  NULL                                                                                                                        as BOX_TEXT_5,
  NULL                                                                                                                        as BOX_TEXT_6,
  NULL                                                                                                                        as BOX_TEXT_COLOR_1,
  NULL                                                                                                                        as BOX_TEXT_COLOR_2,
  NULL                                                                                                                        as BOX_TEXT_COLOR_3,
  NULL                                                                                                                        as BOX_TEXT_COLOR_4,
  NULL                                                                                                                        as BOX_TEXT_COLOR_5,
  NULL                                                                                                                        as BOX_TEXT_COLOR_6,
  null                                                                                                                        as TOP_TEXT_1,
  null                                                                                                                        as TOP_TEXT_2,
  null                                                                                                                        as TOP_TEXT_3,
  null                                                                                                                        as TOP_TEXT_4,
  null                                                                                                                        as TOP_TEXT_5,
  null                                                                                                                        as TOP_TEXT_6,
  null                                                                                                                        as TOP_TEXT_7,
  null                                                                                                                        as TOP_TEXT_8,
  null                                                                                                                        as TOP_TEXT_9,
  null                                                                                                                        as TOP_TEXT_10,
  null                                                                                                                        as TOP_TEXT_11,
  null                                                                                                                        as TOP_TEXT_12,
  null                                                                                                                        as TOP_TEXT_COLOR_1,
  null                                                                                                                        as TOP_TEXT_COLOR_2,
  null                                                                                                                        as TOP_TEXT_COLOR_3,
  null                                                                                                                        as TOP_TEXT_COLOR_4,
  null                                                                                                                        as TOP_TEXT_COLOR_5,
  null                                                                                                                        as TOP_TEXT_COLOR_6,
  null                                                                                                                        as TOP_TEXT_COLOR_7,
  null                                                                                                                        as TOP_TEXT_COLOR_8,
  null                                                                                                                        as TOP_TEXT_COLOR_9,
  null                                                                                                                        as TOP_TEXT_COLOR_10,
  null                                                                                                                        as TOP_TEXT_COLOR_11,
  null                                                                                                                        as TOP_TEXT_COLOR_12,
  null                                                                                                                        as BOTTOM_TEXT_1,
  null                                                                                                                        as BOTTOM_TEXT_2,
  null                                                                                                                        as BOTTOM_TEXT_3,
  null                                                                                                                        as BOTTOM_TEXT_4,
  null                                                                                                                        as BOTTOM_TEXT_5,
  null                                                                                                                        as BOTTOM_TEXT_6,
  null                                                                                                                        as BOTTOM_TEXT_7,
  null                                                                                                                        as BOTTOM_TEXT_8,
  null                                                                                                                        as BOTTOM_TEXT_9,
  null                                                                                                                        as BOTTOM_TEXT_10,
  null                                                                                                                        as BOTTOM_TEXT_11,
  null                                                                                                                        as BOTTOM_TEXT_12,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_1,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_2,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_3,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_4,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_5,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_6,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_7,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_8,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_9,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_10,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_11,
  null                                                                                                                        as BOTTOM_TEXT_COLOR_12,
  'tracing/OK.png'                                                                                                            as ICON_1,
  'tracing/' || x.record_status || '.png'                                                                                     as ICON_2,
  decode(ecdp_visual_tracing.GetForwardReference(dfd.reference_id, 'RRCA_REPORT'),'true','tracing/LOCK.png','')               as ICON_3,
  decode(ecdp_visual_tracing.GetNotesReference(to_char(x.report_no), 'RRCA_REPORT'),'true','tracing/NOTES.png','')            as ICON_4,
  NULL                                                                                                                        as ICON_5,
  ecdp_visual_tracing.GetReportActualAccrual(x.DOCUMENT_KEY, x.report_no)                                                     as ACTUAL_ACCRUAL_CODE,
  'N'                                                                                                                         as FORECAST_IND,
  decode(ec_dataset_flow_report.status(x.id),'D','Y','N')                                                                     as DEPRECATED_IND,
  x.RECORD_STATUS                                                                                                             as RECORD_STATUS,
  x.CREATED_BY                                                                                                                as CREATED_BY,
  x.CREATED_DATE                                                                                                              as CREATED_DATE,
  x.LAST_UPDATED_BY                                                                                                           as LAST_UPDATED_BY,
  x.LAST_UPDATED_DATE                                                                                                         as LAST_UPDATED_DATE,
  x.REV_NO                                                                                                                    as REV_NO,
  x.REV_TEXT                                                                                                                  as REV_TEXT,
  x.APPROVAL_BY                                                                                                               as APPROVAL_BY,
  x.APPROVAL_DATE                                                                                                             as APPROVAL_DATE,
  x.APPROVAL_STATE                                                                                                            as APPROVAL_STATE,
  x.REC_ID                                                                                                                    as REC_ID
from dataset_flow_report x, DATASET_FLOW_DOCUMENT dfd
where to_char(x.report_no) = to_char(dfd.reference_id)
and ec_report.status(x.report_no) = 'GENERATED'
and dfd.type = 'REPORT'
order by x.daytime, x.CREATED_DATE