CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_TRANS_INV_PROD_STREAM_HISTO" ("CLASS_NAME", "OBJECT_ID", "OBJECT_CODE", "JN_DATETIME", "DAYTIME", "END_DATE", "EXEC_ORDER", "PRODUCT_GROUP_ID", "MESSAGES", "SUMMARIES", "REFERENCES", "POSTINGS", "SUMMARY_IND", "TRANS_INVENTORY_ID", "TRANS_INVENTORY_CODE", "TEMPLATE_SET_ID", "TEMPLATE_SET_CODE", "STREAM_EXTRACT_ID", "STREAM_EXTRACT_CODE", "PROJECT_EXTRACT_ID", "PROJECT_EXTRACT_CODE", "RECORD_STATUS", "CREATED_BY", "CREATED_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "REV_NO", "REV_TEXT", "APPROVAL_STATE", "APPROVAL_BY", "APPROVAL_DATE", "REC_ID") AS 
  (
----------------------------------------------------------------------------------------------------
-- File name: v_trans_inv_prod_stream_history.sql
-- View name: v_trans_inv_prod_stream_history
--
-- $Revision: 1.0 $
--
-- Purpose  : combine both Historical and Current version of records.
--
-- Modification history:
--
-- Date       Whom       Change description:
-- ---------- ----       --------------------------------------------------------------------------------
-- 25.10.2016 hannnyii
-- 18.11.2016 xxskjors	 Messages, summaries, references and postings where added in order for class TRANS_INV_PROD_STREAM_HI to deploy successfully
--						 Proper return values for these columns remains to be added (ECPD-40496)
----------------------------------------------------------------------------------------------------
SELECT
'v_trans_inv_prod_stream_history' AS CLASS_NAME,
V_TRANS_INV_PROD_STREAM_HIST.OBJECT_ID,
o.OBJECT_CODE,
V_TRANS_INV_PROD_STREAM_HIST.JN_DATETIME,
V_TRANS_INV_PROD_STREAM_HIST.DAYTIME AS DAYTIME,
V_TRANS_INV_PROD_STREAM_HIST.END_DATE AS END_DATE,
V_TRANS_INV_PROD_STREAM_HIST.EXEC_ORDER AS EXEC_ORDER,
ec_contract_attribute.attribute_string(V_TRANS_INV_PROD_STREAM_HIST.object_id,'TRANS_INV_PROD_GROUP',V_TRANS_INV_PROD_STREAM_HIST.daytime,'<=') AS PRODUCT_GROUP_ID,
NULL AS MESSAGES,
NULL AS SUMMARIES,
NULL AS REFERENCES,
NULL AS POSTINGS,
decode(instr(NVL(ec_trans_inventory_version.valuation_method(V_TRANS_INV_PROD_STREAM_HIST.inventory_id,V_TRANS_INV_PROD_STREAM_HIST.daytime,'<='),'Z'),'SUMMARY'),0,'N','Y') AS SUMMARY_IND,
V_TRANS_INV_PROD_STREAM_HIST.INVENTORY_ID AS TRANS_INVENTORY_ID,
EC_TRANS_INVENTORY.object_code(V_TRANS_INV_PROD_STREAM_HIST.INVENTORY_ID) AS TRANS_INVENTORY_CODE,
V_TRANS_INV_PROD_STREAM_HIST.TEMPLATE_SET_ID AS TEMPLATE_SET_ID,
EC_TRANS_INV_TMPL_SET.object_code(V_TRANS_INV_PROD_STREAM_HIST.TEMPLATE_SET_ID) AS TEMPLATE_SET_CODE,
V_TRANS_INV_PROD_STREAM_HIST.STREAM_EXTRACT_ID AS STREAM_EXTRACT_ID,
EC_SUMMARY_SETUP.object_code(V_TRANS_INV_PROD_STREAM_HIST.STREAM_EXTRACT_ID) AS STREAM_EXTRACT_CODE,
V_TRANS_INV_PROD_STREAM_HIST.PROJECT_EXTRACT_ID AS PROJECT_EXTRACT_ID,
EC_SUMMARY_SETUP.object_code(V_TRANS_INV_PROD_STREAM_HIST.PROJECT_EXTRACT_ID) AS PROJECT_EXTRACT_CODE,
V_TRANS_INV_PROD_STREAM_HIST.RECORD_STATUS AS RECORD_STATUS,
V_TRANS_INV_PROD_STREAM_HIST.CREATED_BY AS CREATED_BY,
V_TRANS_INV_PROD_STREAM_HIST.CREATED_DATE AS CREATED_DATE,
V_TRANS_INV_PROD_STREAM_HIST.LAST_UPDATED_BY AS LAST_UPDATED_BY,
V_TRANS_INV_PROD_STREAM_HIST.LAST_UPDATED_DATE AS LAST_UPDATED_DATE,
V_TRANS_INV_PROD_STREAM_HIST.REV_NO AS REV_NO,
V_TRANS_INV_PROD_STREAM_HIST.REV_TEXT AS REV_TEXT,
V_TRANS_INV_PROD_STREAM_HIST.APPROVAL_STATE AS APPROVAL_STATE,
V_TRANS_INV_PROD_STREAM_HIST.APPROVAL_BY AS APPROVAL_BY,
V_TRANS_INV_PROD_STREAM_HIST.APPROVAL_DATE AS APPROVAL_DATE,
V_TRANS_INV_PROD_STREAM_HIST.REC_ID AS REC_ID
FROM V_TRANS_INV_PROD_STREAM_HIST
, CONTRACT_VERSION oa, CONTRACT o
WHERE V_TRANS_INV_PROD_STREAM_HIST.object_id = oa.object_id
AND oa.object_id = o.object_id
AND V_TRANS_INV_PROD_STREAM_HIST.daytime >= TRUNC(oa.daytime,'MONTH')
AND oa.daytime = (
SELECT MIN(daytime) FROM CONTRACT_VERSION v2
WHERE v2.object_id = oa.object_id
AND   V_TRANS_INV_PROD_STREAM_HIST.daytime >= trunc(v2.daytime,'MONTH')
AND V_TRANS_INV_PROD_STREAM_HIST.daytime < nvl(v2.end_date,V_TRANS_INV_PROD_STREAM_HIST.daytime + 1)
)
)