CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_TRANS_INV_LI_PR_OVER_H" ("JN_OPERATION", "JN_ORACLE_USER", "JN_DATETIME", "JN_NOTES", "JN_APPLN", "JN_SESSION", "OBJECT_ID", "ID", "DAYTIME", "END_DATE", "TAG", "CONTRACT_ID", "PRODUCT_ID", "COST_TYPE", "TRANS_DEF_DIMENSION", "PRORATE_DIM_TO_PROD_ID", "SEQ_NO", "EXEC_ORDER", "QTY_EXEC_ORDER", "QTY_SOURCE_METHOD", "VALUE_METHOD", "PRICE_INDEX", "VAL_EXTRACT_TAG", "QTY_EXTRACT_TAG", "VAL_EXTRACT_TYPE", "QTY_EXTRACT_TYPE", "EXTR_VAL_NET_ZERO", "EXTRACT_REVRS_VAL", "EXTRACT_REVRS_QTY", "PRORATE_IND", "PRORATE_LINE", "DESCRIPTION", "RECORD_STATUS", "CREATED_BY", "CREATED_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "REV_NO", "REV_TEXT", "APPROVAL_BY", "APPROVAL_DATE", "APPROVAL_STATE", "REC_ID") AS 
  (
----------------------------------------------------------------------------------------------------
-- File name: V_TRANS_INV_LI_PR_OVER_HIST.sql
-- View name: V_TRANS_INV_LI_PR_OVER_HIST
--
-- $Revision: 1.0 $
--
-- Purpose  : combine both Historical and Current version of records.
--
-- Modification history:
--9
-- Date       Whom       Change description:
-- ---------- ----       --------------------------------------------------------------------------------
-- 14.09.2016 lewisbra
----------------------------------------------------------------------------------------------------
  SELECT "JN_OPERATION","JN_ORACLE_USER","JN_DATETIME","JN_NOTES","JN_APPLN","JN_SESSION","OBJECT_ID","ID","DAYTIME","END_DATE","TAG","CONTRACT_ID","PRODUCT_ID","COST_TYPE","TRANS_DEF_DIMENSION","PRORATE_DIM_TO_PROD_ID","SEQ_NO","EXEC_ORDER","QTY_EXEC_ORDER","QTY_SOURCE_METHOD","VALUE_METHOD","PRICE_INDEX","VAL_EXTRACT_TAG","QTY_EXTRACT_TAG","VAL_EXTRACT_TYPE","QTY_EXTRACT_TYPE","EXTR_VAL_NET_ZERO","EXTRACT_REVRS_VAL","EXTRACT_REVRS_QTY","PRORATE_IND","PRORATE_LINE","DESCRIPTION","RECORD_STATUS","CREATED_BY","CREATED_DATE","LAST_UPDATED_BY","LAST_UPDATED_DATE","REV_NO","REV_TEXT","APPROVAL_BY","APPROVAL_DATE","APPROVAL_STATE","REC_ID" FROM (
		SELECT
			'CURRENT' jn_operation
			,NVL(last_updated_by,created_by) jn_oracle_user
			,sysdate  jn_datetime
			,'CURRENT' jn_notes
			,NULL jn_appln
			,NULL jn_session
			,OBJECT_ID,
		ID,
		DAYTIME,
		END_DATE,
		TAG,
		CONTRACT_ID,
		PRODUCT_ID,
		COST_TYPE,
		TRANS_DEF_DIMENSION,
		PRORATE_DIM_TO_PROD_ID,
		SEQ_NO,
		EXEC_ORDER,
		QTY_EXEC_ORDER,
		QTY_SOURCE_METHOD,
		VALUE_METHOD,
		PRICE_INDEX,
		VAL_EXTRACT_TAG,
		QTY_EXTRACT_TAG,
		VAL_EXTRACT_TYPE,
		QTY_EXTRACT_TYPE,
		EXTR_VAL_NET_ZERO,
		EXTRACT_REVRS_VAL,
		EXTRACT_REVRS_QTY,
		PRORATE_IND,
		PRORATE_LINE,
		DESCRIPTION,
		RECORD_STATUS,
		CREATED_BY,
		CREATED_DATE,
		LAST_UPDATED_BY,
		LAST_UPDATED_DATE,
		REV_NO,
		REV_TEXT,
		APPROVAL_BY,
		APPROVAL_DATE,
		APPROVAL_STATE,
		REC_ID
		from
			TRANS_INV_LI_PR_OVER
		UNION
		SELECT
		JN_OPERATION,
		JN_ORACLE_USER,
		ecdp_date_time.getCurrentDBSysdate(JN_DATETIME),
		JN_NOTES,
		JN_APPLN,
		JN_SESSION,
		OBJECT_ID,
		ID,
		DAYTIME,
		END_DATE,
		TAG,
		CONTRACT_ID,
		PRODUCT_ID,
		COST_TYPE,
		TRANS_DEF_DIMENSION,
		PRORATE_DIM_TO_PROD_ID,
		SEQ_NO,
		EXEC_ORDER,
		QTY_EXEC_ORDER,
		QTY_SOURCE_METHOD,
		VALUE_METHOD,
		PRICE_INDEX,
		VAL_EXTRACT_TAG,
		QTY_EXTRACT_TAG,
		VAL_EXTRACT_TYPE,
		QTY_EXTRACT_TYPE,
		EXTR_VAL_NET_ZERO,
		EXTRACT_REVRS_VAL,
		EXTRACT_REVRS_QTY,
		PRORATE_IND,
		PRORATE_LINE,
		DESCRIPTION,
		RECORD_STATUS,
		CREATED_BY,
		CREATED_DATE,
		LAST_UPDATED_BY,
		LAST_UPDATED_DATE,
		REV_NO,
		REV_TEXT,
		APPROVAL_BY,
		APPROVAL_DATE,
		APPROVAL_STATE,
		REC_ID
     FROM
		TRANS_INV_LI_PR_OVER_jn
  )
)