CREATE OR REPLACE FORCE VIEW "V_FLUID_ANALYSIS_COMP" ("ANALYSIS_NO", "OBJECT_ID", "OBJECT_CLASS_NAME", "DAYTIME", "ANALYSIS_TYPE", "SAMPLING_METHOD", "PHASE", "VALID_FROM_DATE", "PRODUCTION_DAY", "ANALYSIS_STATUS", "SAMPLE_PRESS", "SAMPLE_TEMP", "GAS_DENSITY", "OIL_DENSITY", "GROSS_LIQ_DENSITY", "DENSITY_OBS", "SP_GRAV", "API", "SHRINKAGE_FACTOR", "SOLUTION_GOR", "BS_W", "BS_W_WT", "CNPL_MOL_WT", "CNPL_SP_GRAV", "CNPL_DENSITY", "MW_MIX", "SG_MIX", "SULFUR_WT", "GCV", "GCV_FLASH", "GCV_FLASH_PRESS", "GCV_PRESS", "NCV", "GCR", "WDP", "RVP", "H2S", "CO2", "SAND", "SALT", "EMULSION", "EMULSION_FRAC", "EMULSION_FACT", "SCALE_INHIB", "WAX_CONTENT", "CRITICAL_PRESS", "CRITICAL_TEMP", "LABORATORY", "LAB_REF_NO", "SAMPLED_BY", "SAMPLED_DATE", "OIL_IN_WATER", "O2", "CHLORINE", "ALUMINIUM", "BARIUM", "BICARBONATE", "BORON", "CALCIUM", "CARBONATE", "CHLORIDE", "HYDROXIDE", "IRON", "IRON_TOTAL", "LITHIUM", "MAGNESIUM", "ORGANIC_ACID", "POTASSIUM", "SILICON", "SODIUM", "STRONTIUM", "SULFATE", "PHOSPHORUS", "CNPL_GCV", "CNPL_API", "VAPOUR", "SALINITY", "FLASH_GAS_FACTOR", "OIL_IN_WATER_CONTENT", "BUTANOATE", "DISS_SOLIDS", "ETHANOATE", "HEXANOATE", "METHANOATE", "PENTANOATE", "PH", "PROPIONATE", "RESISTIVITY", "SULFATE_2", "SUSP_SOLIDS", "TOT_ALKALINITY", "SAMPLING_POINT", "FLUID_STATE", "CHECK_UNIQUE", "COMPONENT_SET", "COMMENTS", "OFA_VALUE_1", "OFA_VALUE_2", "OFA_VALUE_3", "OFA_VALUE_4", "OFA_VALUE_5", "OFA_VALUE_6", "OFA_VALUE_7", "OFA_VALUE_8", "OFA_VALUE_9", "OFA_VALUE_10", "OFA_VALUE_11", "OFA_VALUE_12", "OFA_VALUE_13", "OFA_VALUE_14", "OFA_VALUE_15", "OFA_VALUE_16", "OFA_VALUE_17", "OFA_VALUE_18", "OFA_VALUE_19", "OFA_VALUE_20", "OFA_VALUE_21", "OFA_VALUE_22", "OFA_VALUE_23", "OFA_VALUE_24", "OFA_VALUE_25", "OFA_VALUE_26", "OFA_VALUE_27", "OFA_VALUE_28", "OFA_VALUE_29", "OFA_VALUE_30", "OFA_VALUE_31", "OFA_VALUE_32", "OFA_VALUE_33", "OFA_VALUE_34", "OFA_VALUE_35", "OFA_VALUE_36", "OFA_VALUE_37", "OFA_VALUE_38", "OFA_VALUE_39", "OFA_VALUE_40", "OFA_VALUE_41", "OFA_VALUE_42", "OFA_VALUE_43", "OFA_VALUE_44", "OFA_VALUE_45", "OFA_VALUE_46", "OFA_VALUE_47", "OFA_TEXT_1", "OFA_TEXT_2", "OFA_TEXT_3", "OFA_TEXT_4", "OFA_TEXT_5", "OFA_TEXT_6", "OFA_TEXT_7", "OFA_TEXT_8", "OFA_TEXT_9", "OFA_TEXT_10", "OFA_TEXT_11", "OFA_TEXT_12", "OFA_TEXT_13", "OFA_TEXT_14", "OFA_TEXT_15", "OFA_TEXT_16", "OFA_TEXT_17", "OFA_TEXT_18", "OFA_TEXT_19", "OFA_TEXT_20", "OFA_TEXT_21", "OFA_TEXT_22", "OFA_TEXT_23", "OFA_TEXT_24", "OFA_TEXT_25", "OFA_TEXT_26", "OFA_TEXT_27", "OFA_TEXT_28", "OFA_TEXT_29", "OFA_TEXT_30", "OFA_TEXT_31", "OFA_TEXT_32", "OFA_TEXT_33", "OFA_TEXT_34", "OFA_TEXT_35", "OFA_TEXT_36", "OFA_TEXT_37", "OFA_TEXT_38", "OFA_TEXT_39", "OFA_TEXT_40", "OFA_TEXT_41", "OFA_TEXT_42", "DATE_1", "DATE_2", "DATE_3", "DATE_4", "DATE_5", "DATE_6", "DATE_7", "DATE_8", "DATE_9", "DATE_10", "DATE_11", "MEAS_MOL_WT", "MEAS_SPECIFIC_GRAVITY", "COMPONENT_NO", "WT_PCT", "MOL_PCT", "DENSITY", "MOL_WT", "VOL_PCT", "ENERGY_PCT", "VALUE_1", "VALUE_2", "VALUE_3", "VALUE_4", "VALUE_5", "VALUE_6", "VALUE_7", "VALUE_8", "VALUE_9", "VALUE_10", "TEXT_1", "TEXT_2", "TEXT_3", "TEXT_4", "CREATED_DATE", "LAST_UPDATED_DATE", "CREATED_BY", "LAST_UPDATED_BY", "REV_TEXT", "REV_NO", "RECORD_STATUS") AS 
  (
-------------------------------------------------------------------------------------
--  v_fluid_analysis_comp
--
-- $Revision: 1.12.2.1 $
--
--  Purpose:   Used by TagCollector to insert component analysis data
--
--  Note:
--
--  Created by: HAK 23.08.2005
-------------------------------------------------------------------------------------
SELECT
    ofa.analysis_no,         --TRIGGER
    ofa.object_id,           --NAVIGATOR
    ofa.object_class_name,   --FUNCTION
    ofa.daytime,             --TAGCOLL
    ofa.analysis_type,       --POPUP
    ofa.sampling_method,     --POPUP
    ofa.phase,               --POPUP
    ofa.valid_from_date,
    ofa.production_day,
    ofa.analysis_status,
    ofa.sample_press,
    ofa.sample_temp,
    ofa.gas_density,
    ofa.oil_density,
    ofa.gross_liq_density,
    ofa.density_obs,
    ofa.sp_grav,
    ofa.api,
    ofa.shrinkage_factor,
    ofa.solution_gor,
    ofa.bs_w,
    ofa.bs_w_wt,
    ofa.cnpl_mol_wt,
    ofa.cnpl_sp_grav,
    ofa.cnpl_density,
    ofa.mw_mix,
    ofa.sg_mix,
    ofa.sulfur_wt,
    ofa.gcv,
    ofa.gcv_flash,
    ofa.gcv_flash_press,
    ofa.gcv_press,
    ofa.ncv,
    ofa.gcr,
    ofa.wdp,
    ofa.rvp,
    ofa.h2s,
    ofa.co2,
    ofa.sand,
    ofa.salt,
    ofa.emulsion,
    ofa.emulsion_frac,
    ofa.emulsion_fact,
    ofa.scale_inhib,
    ofa.wax_content,
    ofa.critical_press,
    ofa.critical_temp,
    ofa.laboratory,
    ofa.lab_ref_no,
    ofa.sampled_by,
    ofa.sampled_date,
    ofa.oil_in_water,
    ofa.o2,
    ofa.chlorine,
    ofa.aluminium,
    ofa.barium,
    ofa.bicarbonate,
    ofa.boron,
    ofa.calcium,
    ofa.carbonate,
    ofa.chloride,
    ofa.hydroxide,
    ofa.iron,
    ofa.iron_total,
    ofa.lithium,
    ofa.magnesium,
    ofa.organic_acid,
    ofa.potassium,
    ofa.silicon,
    ofa.sodium,
    ofa.strontium,
    ofa.sulfate,
    ofa.phosphorus,
    ofa.cnpl_gcv,
    ofa.cnpl_api,
    ofa.vapour,
    ofa.salinity,
    ofa.flash_gas_factor,
    ofa.oil_in_water_content,
    ofa.butanoate,
    ofa.diss_solids,
    ofa.ethanoate,
    ofa.hexanoate,
    ofa.methanoate,
    ofa.pentanoate,
    ofa.ph,
    ofa.propionate,
    ofa.resistivity,
    ofa.sulfate_2,
    ofa.susp_solids,
    ofa.tot_alkalinity,
    ofa.sampling_point,
    ofa.fluid_state,
    ofa.check_unique,
    ofa.component_set,
    ofa.comments,
    ofa.value_1 ofa_value_1,
    ofa.value_2 ofa_value_2,
    ofa.value_3 ofa_value_3,
    ofa.value_4 ofa_value_4,
    ofa.value_5 ofa_value_5,
    ofa.value_6 ofa_value_6,
    ofa.value_7 ofa_value_7,
    ofa.value_8 ofa_value_8,
    ofa.value_9 ofa_value_9,
    ofa.value_10 ofa_value_10,
    ofa.value_11 ofa_value_11,
    ofa.value_12 ofa_value_12,
    ofa.value_13 ofa_value_13,
    ofa.value_14 ofa_value_14,
    ofa.value_15 ofa_value_15,
    ofa.value_16 ofa_value_16,
    ofa.value_17 ofa_value_17,
    ofa.value_18 ofa_value_18,
    ofa.value_19 ofa_value_19,
    ofa.value_20 ofa_value_20,
    ofa.value_21 ofa_value_21,
    ofa.value_22 ofa_value_22,
    ofa.value_23 ofa_value_23,
    ofa.value_24 ofa_value_24,
    ofa.value_25 ofa_value_25,
    ofa.value_26 ofa_value_26,
    ofa.value_27 ofa_value_27,
    ofa.value_28 ofa_value_28,
    ofa.value_29 ofa_value_29,
    ofa.value_30 ofa_value_30,
    ofa.value_31 ofa_value_31,
    ofa.value_32 ofa_value_32,
    ofa.value_33 ofa_value_33,
    ofa.value_34 ofa_value_34,
    ofa.value_35 ofa_value_35,
    ofa.value_36 ofa_value_36,
    ofa.value_37 ofa_value_37,
    ofa.value_38 ofa_value_38,
    ofa.value_39 ofa_value_39,
    ofa.value_40 ofa_value_40,
    ofa.value_41 ofa_value_41,
    ofa.value_42 ofa_value_42,
    ofa.value_43 ofa_value_43,
    ofa.value_44 ofa_value_44,
    ofa.value_45 ofa_value_45,
    ofa.value_46 ofa_value_46,
    ofa.value_47 ofa_value_47,
    ofa.text_1 ofa_text_1,
    ofa.text_2 ofa_text_2,
    ofa.text_3 ofa_text_3,
    ofa.text_4 ofa_text_4,
    ofa.text_5 ofa_text_5,
    ofa.text_6 ofa_text_6,
    ofa.text_7 ofa_text_7,
    ofa.text_8 ofa_text_8,
    ofa.text_9 ofa_text_9,
    ofa.text_10 ofa_text_10,
    ofa.text_11 ofa_text_11,
    ofa.text_12 ofa_text_12,
    ofa.text_13 ofa_text_13,
    ofa.text_14 ofa_text_14,
    ofa.text_15 ofa_text_15,
    ofa.text_16 ofa_text_16,
    ofa.text_17 ofa_text_17,
    ofa.text_18 ofa_text_18,
    ofa.text_19 ofa_text_19,
    ofa.text_20 ofa_text_20,
    ofa.text_21 ofa_text_21,
    ofa.text_22 ofa_text_22,
    ofa.text_23 ofa_text_23,
    ofa.text_24 ofa_text_24,
    ofa.text_25 ofa_text_25,
    ofa.text_26 ofa_text_26,
    ofa.text_27 ofa_text_27,
    ofa.text_28 ofa_text_28,
    ofa.text_29 ofa_text_29,
    ofa.text_30 ofa_text_30,
    ofa.text_31 ofa_text_31,
    ofa.text_32 ofa_text_32,
    ofa.text_33 ofa_text_33,
    ofa.text_34 ofa_text_34,
    ofa.text_35 ofa_text_35,
    ofa.text_36 ofa_text_36,
    ofa.text_37 ofa_text_37,
    ofa.text_38 ofa_text_38,
    ofa.text_39 ofa_text_39,
    ofa.text_40 ofa_text_40,
    ofa.text_41 ofa_text_41,
    ofa.text_42 ofa_text_42,
    ofa.date_1,
    ofa.date_2,
    ofa.date_3,
    ofa.date_4,
    ofa.date_5,
    ofa.date_6,
    ofa.date_7,
    ofa.date_8,
    ofa.date_9,
    ofa.date_10,
    ofa.date_11,
    fac.meas_mol_wt,
    fac.meas_specific_gravity,
		fac.component_no,
		fac.wt_pct,
		fac.mol_pct,
		fac.density,
		fac.mol_wt,
		fac.vol_pct,
		fac.energy_pct,
		fac.value_1,
		fac.value_2,
		fac.value_3,
		fac.value_4,
		fac.value_5,
		fac.value_6,
		fac.value_7,
		fac.value_8,
		fac.value_9,
		fac.value_10,
		fac.text_1,
		fac.text_2,
		fac.text_3,
		fac.text_4,
		fac.created_date,
		fac.last_updated_date,
		fac.created_by,
		fac.last_updated_by,
		fac.rev_text,
		fac.rev_no,
		fac.record_status
  FROM object_fluid_analysis ofa,
       fluid_analysis_component fac
 WHERE ofa.analysis_no = fac.analysis_no
)