DECLARE 
HASENTRY NUMBER;
BEGIN 
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_CNTR_SUB_DAY_CAP'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_CNTR_SUB_DAY_CAP DISABLE';
		END IF;

	UPDATE CNTR_SUB_DAY_CAP C SET C.SUMMER_TIME = ECDP_DATE_TIME.SUMMERTIME_FLAG(C.DAYTIME, NULL, C.OBJECT_ID);
	
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_CNTR_SUB_DAY_CAP'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_CNTR_SUB_DAY_CAP ENABLE';
		END IF;
EXCEPTION
   WHEN OTHERS 
     THEN

       IF HASENTRY > 0 THEN 
           EXECUTE IMMEDIATE 'ALTER TRIGGER IU_CNTR_SUB_DAY_CAP ENABLE';
       END IF;
        
        raise_application_error(-20000,
                            'ERROR: Some Other fatal error occured :- '||SQLERRM);


END;
--~^UTDELIM^~--	