DECLARE 
HASENTRY NUMBER;
BEGIN 
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_LIFTING_ACTIVITY_CODE'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_LIFTING_ACTIVITY_CODE DISABLE';
		END IF;

	UPDATE LIFTING_ACTIVITY_CODE A SET A.LIFTING_EVENT = 'LOAD' WHERE A.LIFTING_EVENT IS NULL;
	
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_LIFTING_ACTIVITY_CODE'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_LIFTING_ACTIVITY_CODE ENABLE';
		END IF;
EXCEPTION
   WHEN OTHERS 
     THEN

       IF HASENTRY > 0 THEN 
           EXECUTE IMMEDIATE 'ALTER TRIGGER IU_LIFTING_ACTIVITY_CODE ENABLE';
       END IF;
        
        raise_application_error(-20000,
                            'ERROR: Some Other fatal error occured :- '||SQLERRM);


END;
--~^UTDELIM^~--	