-- ECPD26333_1_OBJ_TRAN_CODE_CONN_UPGRADE...
DECLARE 
HASENTRY NUMBER;
BEGIN
	--upgrade script obj_tran_code_conn
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_OBJ_TRAN_CODE_CONN'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_OBJ_TRAN_CODE_CONN DISABLE';
		END IF;
	
	UPDATE OBJ_TRAN_CODE_CONN A
	SET A.CODE = EC_PROSTY_CODES.CODE_TEXT(A.CONNECTION_TYPE_CODE, 'NOMPNT_CONN_TYPE')||'_'|| ECDP_SYSTEM_KEY.ASSIGNNEXTNUMBER('TEMP_OBJ_TRAN_CODE_CONN')
	WHERE A.CODE IS NULL;
	
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_OBJ_TRAN_CODE_CONN'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_OBJ_TRAN_CODE_CONN ENABLE';
		END IF;

	ECDP_SYSTEM_KEY.RESETNEXTNUMBER('TEMP_OBJ_TRAN_CODE_CONN', 0);
EXCEPTION
   WHEN OTHERS 
     THEN

       IF HASENTRY > 0 THEN 
           EXECUTE IMMEDIATE 'ALTER TRIGGER IU_OBJ_TRAN_CODE_CONN ENABLE';
       END IF;
        
        raise_application_error(-20000,
                            'ERROR: Some Other fatal error occured :- '||SQLERRM);


END;	
--~^UTDELIM^~--