BEGIN

INSERT INTO PRICE_IN_ITEM_VERSION_JN
(
		JN_NOTES
		, JN_SESSION
		, TEXT_5
		, DATE_4
		, RECORD_STATUS
		, APPROVAL_BY
		, JN_ORACLE_USER
		, FREQUENCY
		, TEXT_3
		, VALUE_2
		, REF_OBJECT_ID_2
		, JN_APPLN
		, DAYTIME
		, END_DATE
		, SORT_ORDER
		, VALUE_9
		, DATE_1
		, REF_OBJECT_ID_3
		, CREATED_DATE
		, JN_DATETIME
		, OBJECT_ID
		, CURRENCY_ID
		, BUSINESS_UNIT_ID
		, VALUE_10
		, DATE_5
		, REF_OBJECT_ID_5
		, CREATED_BY
		, REV_TEXT
		, UPLOAD_TYPE
		, UNIT
		, PRODUCT_ID
		, TEXT_9
		, VALUE_5
		, VALUE_6
		, VALUE_7
		, DATE_2
		, REC_ID
		, TEXT_1
		, TEXT_6
		, TEXT_8
		, VALUE_4
		, DATE_3
		, REF_OBJECT_ID_4
		, LAST_UPDATED_BY
		, REV_NO
		, JN_OPERATION
		, NAME
		, TEXT_4
		, TEXT_10
		, VALUE_1
		, VALUE_3
		, VALUE_8
		, LAST_UPDATED_DATE
		, APPROVAL_DATE
		, SOURCE
		, UPLOAD_ADDRESS
		, COMMENTS
		, TEXT_2
		, TEXT_7
		, REF_OBJECT_ID_1
		, APPROVAL_STATE
)
SELECT 
		JN_NOTES
		, JN_SESSION
		, TEXT_5
		, DATE_4
		, RECORD_STATUS
		, APPROVAL_BY
		, JN_ORACLE_USER
		, FREQUENCY
		, TEXT_3
		, VALUE_2
		, REF_OBJECT_ID_2
		, JN_APPLN
		, DAYTIME
		, END_DATE
		, SORT_ORDER
		, VALUE_9
		, DATE_1
		, REF_OBJECT_ID_3
		, CREATED_DATE
		, JN_DATETIME
		, OBJECT_ID
		, CURRENCY_ID
		, BUSINESS_UNIT_ID
		, VALUE_10
		, DATE_5
		, REF_OBJECT_ID_5
		, CREATED_BY
		, REV_TEXT
		, UPLOAD_TYPE
		, UNIT
		, PRODUCT_ID
		, TEXT_9
		, VALUE_5
		, VALUE_6
		, VALUE_7
		, DATE_2
		, REC_ID
		, TEXT_1
		, TEXT_6
		, TEXT_8
		, VALUE_4
		, DATE_3
		, REF_OBJECT_ID_4
		, LAST_UPDATED_BY
		, REV_NO
		, JN_OPERATION
		, NAME
		, TEXT_4
		, TEXT_10
		, VALUE_1
		, VALUE_3
		, VALUE_8
		, LAST_UPDATED_DATE
		, APPROVAL_DATE
		, SOURCE
		, UPLOAD_ADDRESS
		, COMMENTS
		, TEXT_2
		, TEXT_7
		, REF_OBJECT_ID_1
		, APPROVAL_STATE
FROM PRICE_INDEX_VERSION_JN ;


END;
--~^UTDELIM^~--