-- Loading ./ECPD26769_WELL_REFERENCE...


ALTER TABLE WELL_REFERENCE_VALUE_JN ADD FLARE_FACTOR_1 NUMBER
--~^UTDELIM^~--

DECLARE 
HASENTRY NUMBER;
BEGIN
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_WELL_REFERENCE_VALUE_JN'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_WELL_REFERENCE_VALUE_JN DISABLE';
		END IF;
	
	UPDATE WELL_REFERENCE_VALUE_JN SET FLARE_FACTOR_1 = FLARE_FACTOR; 
	
	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_WELL_REFERENCE_VALUE_JN'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_WELL_REFERENCE_VALUE_JN ENABLE';
		END IF;
EXCEPTION
   WHEN OTHERS 
     THEN

       IF HASENTRY > 0 THEN 
           EXECUTE IMMEDIATE 'ALTER TRIGGER IU_WELL_REFERENCE_VALUE_JN ENABLE';
       END IF;
        
        raise_application_error(-20000,
                            'ERROR: Some Other fatal error occured :- '||SQLERRM);


END;
--~^UTDELIM^~--

ALTER TABLE WELL_REFERENCE_VALUE_JN DROP COLUMN FLARE_FACTOR
--~^UTDELIM^~--

ALTER TABLE WELL_REFERENCE_VALUE_JN RENAME COLUMN FLARE_FACTOR_1 TO FLARE_FACTOR
--~^UTDELIM^~--
