DECLARE 
HASENTRY NUMBER;
BEGIN

FOR CUR IN (SELECT OWNER, CONSTRAINT_NAME , TABLE_NAME 	FROM USER_CONSTRAINTS 	WHERE  TABLE_NAME = 'PRICE_IN_ITEM_VALUE_JN') 
LOOP
	  EXECUTE IMMEDIATE 'ALTER TABLE '||CUR.OWNER||'.'||CUR.TABLE_NAME||' DISABLE CONSTRAINT "'||CUR.CONSTRAINT_NAME||'" ';
END LOOP;

INSERT INTO PRICE_IN_ITEM_VALUE_JN
(
		JN_NOTES
		, JN_SESSION
		, INDEX_VALUE
		, MIN_VALUE
		, DATE_4
		, RECORD_STATUS
		, APPROVAL_BY
		, JN_ORACLE_USER
		, VALUE_2
		, TEXT_3
		, JN_APPLN
		, DAYTIME
		, VALUE_9
		, DATE_1
		, CREATED_DATE
		, JN_DATETIME
		, OBJECT_ID
		, OFFER_VALUE
		, VALUE_10
		, DATE_5
		, CREATED_BY
		, REV_TEXT
		, VALUE_5
		, VALUE_6
		, VALUE_7
		, DATE_2
		, REC_ID
		, VOLUME_VALUE
		, VALUE_4
		, TEXT_1
		, DATE_3
		, LAST_UPDATED_BY
		, REV_NO
		, JN_OPERATION
		, MAX_VALUE
		, VALUE_1
		, VALUE_3
		, VALUE_8
		, TEXT_4
		, LAST_UPDATED_DATE
		, APPROVAL_DATE
		, BID_VALUE
		, TEXT_2
		, APPROVAL_STATE
)
SELECT 
		JN_NOTES
		, JN_SESSION
		, INDEX_VALUE
		, MIN_VALUE
		, DATE_4
		, RECORD_STATUS
		, APPROVAL_BY
		, JN_ORACLE_USER
		, VALUE_2
		, TEXT_3
		, JN_APPLN
		, DAYTIME
		, VALUE_9
		, DATE_1
		, CREATED_DATE
		, JN_DATETIME
		, OBJECT_ID
		, OFFER_VALUE
		, VALUE_10
		, DATE_5
		, CREATED_BY
		, REV_TEXT
		, VALUE_5
		, VALUE_6
		, VALUE_7
		, DATE_2
		, REC_ID
		, VOLUME_VALUE
		, VALUE_4
		, TEXT_1
		, DATE_3
		, LAST_UPDATED_BY
		, REV_NO
		, JN_OPERATION
		, MAX_VALUE
		, VALUE_1
		, VALUE_3
		, VALUE_8
		, TEXT_4
		, LAST_UPDATED_DATE
		, APPROVAL_DATE
		, BID_VALUE
		, TEXT_2
		, APPROVAL_STATE
FROM PRICE_INDEX_VALUE_JN ;

	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_PRICE_IN_ITEM_VALUE_JN'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_PRICE_IN_ITEM_VALUE_JN DISABLE';
		END IF;

		UPDATE PRICE_IN_ITEM_VALUE_JN PIIV 
		SET CLASS_NAME = 'PRICE_INDEX_DAY_VALUE' 
		WHERE PIIV.OBJECT_ID in ( SELECT PV.OBJECT_ID 
								FROM PRICE_IN_ITEM_VERSION PV 
								WHERE PIIV.OBJECT_ID = PV.OBJECT_ID 
								AND FREQUENCY = 'DAY') 
		AND PIIV.CLASS_NAME IS NULL;
		
		UPDATE PRICE_IN_ITEM_VALUE_JN PIIV 
		SET CLASS_NAME = 'PRICE_INDEX_MTH_VALUE' 
		WHERE PIIV.OBJECT_ID in ( SELECT PV.OBJECT_ID 
								FROM PRICE_IN_ITEM_VERSION PV 
								WHERE PIIV.OBJECT_ID = PV.OBJECT_ID 
								AND FREQUENCY = 'MTH') 
		AND PIIV.CLASS_NAME IS NULL;
		
		UPDATE PRICE_IN_ITEM_VALUE_JN PIIV 
		SET CLASS_NAME = 'PRICE_INDEX_YR_VALUE' 
		WHERE PIIV.OBJECT_ID in ( SELECT PV.OBJECT_ID 
								FROM PRICE_IN_ITEM_VERSION PV 
								WHERE PIIV.OBJECT_ID = PV.OBJECT_ID 
								AND FREQUENCY = 'YR') 
		AND PIIV.CLASS_NAME IS NULL;

	SELECT COUNT(*) INTO HASENTRY FROM USER_TRIGGERS 
		WHERE TRIGGER_NAME = 'IU_PRICE_IN_ITEM_VALUE_JN'; 
		IF HASENTRY > 0 THEN 
		EXECUTE IMMEDIATE 'ALTER TRIGGER IU_PRICE_IN_ITEM_VALUE_JN ENABLE';
		END IF;

FOR CUR IN (SELECT OWNER, CONSTRAINT_NAME , TABLE_NAME 	FROM USER_CONSTRAINTS 	WHERE  TABLE_NAME = 'PRICE_IN_ITEM_VALUE_JN') 
LOOP
	  EXECUTE IMMEDIATE 'ALTER TABLE '||CUR.OWNER||'.'||CUR.TABLE_NAME||' ENABLE CONSTRAINT "'||CUR.CONSTRAINT_NAME||'" ';
END LOOP;

EXCEPTION
   WHEN OTHERS 
     THEN

       IF HASENTRY > 0 THEN 
           EXECUTE IMMEDIATE 'ALTER TRIGGER IU_PRICE_IN_ITEM_VALUE_JN ENABLE';
       END IF;
        
        raise_application_error(-20000,
                            'ERROR: Some Other fatal error occured :- '||SQLERRM);


END;
--~^UTDELIM^~--
