--UPGCVX-1580--UPGCVX-1583
UPDATE TV_UOM_SETUP SET DB_UNIT='N',REPORT_UNIT='N',VIEW_UNIT='N' WHERE MEASUREMENT_TYPE='STD_GAS_VOL' AND UNIT='MSCF';
UPDATE TV_UOM_SETUP SET DB_UNIT='Y',REPORT_UNIT='Y',VIEW_UNIT='Y' WHERE MEASUREMENT_TYPE='STD_GAS_VOL' AND UNIT='KSM3';

UPDATE TV_UOM_SETUP SET DB_UNIT='N',REPORT_UNIT='Y',VIEW_UNIT='N' WHERE MEASUREMENT_TYPE='STD_LIQ_VOL' AND UNIT='BBLS';
UPDATE TV_UOM_SETUP SET DB_UNIT='Y',REPORT_UNIT='Y',VIEW_UNIT='Y' WHERE MEASUREMENT_TYPE='STD_LIQ_VOL' AND UNIT='SM3';

INSERT INTO TV_UOM_SETUP (MEASUREMENT_TYPE, UNIT, DB_UNIT, REPORT_UNIT, VIEW_UNIT) VALUES ('LNG_MASS','TONNESPERSM3','N','Y','N');
