UPDATE CLASS_ATTRIBUTE_CNFG SET DB_MAPPING_TYPE='FUNCTION', DB_SQL_SYNTAX='ecbp_stream_fluid.findGrsStdMass(STRM_DAY_STREAM.OBJECT_ID, STRM_DAY_STREAM.DAYTIME)'
WHERE CLASS_NAME='STRM_DAY_STREAM_MEAS_WAT' AND ATTRIBUTE_NAME='GRS_MASS_WAT';

INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE)
VALUES ('STRM_DAY_STREAM_MEAS_WAT','GRS_MASS_WAT','DB_SORT_ORDER',2500,'/','VIEWLAYER',510);

INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE)
VALUES ('STRM_DAY_STREAM_MEAS_WAT','GRS_MASS_WAT','viewcolsumfunc',2500,'/EC','STATIC_PRESENTATION','true');

INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE)
VALUES ('STRM_DAY_STREAM_MEAS_WAT','GRS_MASS_WAT','LABEL',2500,'/EC','APPLICATION','Grs Mass');

DELETE FROM CLASS_ATTR_PROPERTY_CNFG WHERE CLASS_NAME='STRM_DAY_STREAM_MEAS_WAT' AND ATTRIBUTE_NAME='GRS_MASS_WAT' AND PROPERTY_CODE='viewhidden' AND PROPERTY_VALUE='true';

UPDATE TV_UOM_SETUP SET DB_UNIT='N',REPORT_UNIT='Y',VIEW_UNIT='N' WHERE MEASUREMENT_TYPE='WATER_MASS' AND UNIT='KG';
UPDATE TV_UOM_SETUP SET DB_UNIT='N',REPORT_UNIT='Y',VIEW_UNIT='N' WHERE MEASUREMENT_TYPE='WATER_MASS' AND UNIT='LBS';
UPDATE TV_UOM_SETUP SET DB_UNIT='Y',REPORT_UNIT='Y',VIEW_UNIT='Y' WHERE MEASUREMENT_TYPE='WATER_MASS' AND UNIT='TONNES';

--UPGCVX-1666
UPDATE TV_UOM_SETUP SET DB_UNIT='N',REPORT_UNIT='N',VIEW_UNIT='N' WHERE MEASUREMENT_TYPE='ENERGY' AND UNIT='BTU';
UPDATE TV_UOM_SETUP SET DB_UNIT='N',REPORT_UNIT='N',VIEW_UNIT='N' WHERE MEASUREMENT_TYPE='LNG_MASS' AND UNIT='KG';
