--Disabling the product attribute as it is affecting the dv_ct_msg_cpp_cu_jde

INSERT INTO CLASS_ATTR_PROPERTY_CNFG (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX, PRESENTATION_CNTX, PROPERTY_TYPE, PROPERTY_VALUE)
VALUES ('COMPANY','ADDRESS_8','DISABLED_IND',2500,'/','VIEWLAYER','Y');