insert INTO class_attr_property_cnfg  (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE )
VALUES  ('FORECAST_TRAN_CP','PERIOD_TYPE','viewhidden','2500','/EC','STATIC_PRESENTATION','true');
    
insert INTO class_attr_property_cnfg  (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE )
VALUES  ('FORECAST_TRAN_CP','FORECAST_STATUS','viewhidden','2500','/EC','STATIC_PRESENTATION','true');
  
insert INTO class_attr_property_cnfg (CLASS_NAME, ATTRIBUTE_NAME, PROPERTY_CODE, OWNER_CNTX,PRESENTATION_CNTX,PROPERTY_TYPE,PROPERTY_VALUE )
VALUES  ('FORECAST_TRAN_CP','FORECAST_TYPE','viewhidden','2500','/EC','STATIC_PRESENTATION','true');
  
UPDATE viewlayer_dirty_log SET DIRTY_IND='Y' WHERE object_name in ('FORECAST_TRAN_CP');
commit;
EXECUTE EcDp_Viewlayer.BuildViewLayer('FORECAST_TRAN_CP',p_force => 'Y') ;
EXECUTE EcDp_Viewlayer.BuildReportLayer('FORECAST_TRAN_CP',p_force => 'Y');

commit;